// AUTO-GENERATED by `fitz build --target wasm-client`.
// Do NOT edit by hand — regenerate from the source `.fitzv`.
//
// Source: App.fitzv
//
// Composed by `src/view/wasm_build.rs::compose_lib_rs` (Phase 11.5.c).
// The tail below is the `#[wasm_bindgen(start)]` wrapper the CLI
// appends to the emitter output; the emitter itself does NOT emit
// the entry point so future targets (SSR, hybrid) can compose
// their own.

// Generated by fitz view WASM emitter (Fase 11.4.b).
// Do NOT edit — regenerate from the source `.fitzv`.

// Phase 11.5.e (§9.o Debt residual) — crate-level allows for
// the two cosmetic warnings that are structural to the
// emitter output, not correctness bugs:
//   - `non_snake_case`: component names are PascalCase by
//     convention (11.5.d), and the synthesised style helper
//     `__inject_style_<Component>_<scope>` reflects that.
//   - `unused_parens`: BinOp lowering wraps sub-expressions
//     in `(...)` to preserve precedence when nested. When
//     the BinOp is the entire RHS of an assignment the outer
//     parens are redundant but harmless.
#![allow(non_snake_case, unused_parens)]

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::atomic::{AtomicBool, Ordering};
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement};

pub struct App {
    clicks: RefCell<i64>,
    status: RefCell<String>,
    __child_slot_0: RefCell<Option<Rc<Item>>>,
    __child_slot_1: RefCell<Option<Rc<Item>>>,
    __child_slot_2: RefCell<Option<Rc<Item>>>,
    root: RefCell<Option<HtmlElement>>,
}

impl App {
    pub fn new() -> Rc<Self> {
        Rc::new(App {
            clicks: RefCell::new(0i64),
            status: RefCell::new("click an item".to_string()),
            __child_slot_0: RefCell::new(None),
            __child_slot_1: RefCell::new(None),
            __child_slot_2: RefCell::new(None),
            root: RefCell::new(None),
        })
    }

    fn on_pick(self: &Rc<Self>) {
        let __rhs = ((*self.clicks.borrow()) + 1i64);
        *self.clicks.borrow_mut() = __rhs;
        let __rhs = "an item bubbled its choose event".to_string();
        *self.status.borrow_mut() = __rhs;
        self.render();
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_App_app_c_2358986f();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("div").unwrap();
        __el0.set_attribute("class", "picker picker-app-c-2358986f").unwrap();
        let __el1 = document.create_element("h1").unwrap();
        let __t2 = document.create_text_node("Event bubbling on WASM");
        __el1.append_child(&__t2).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el3 = document.create_element("p").unwrap();
        __el3.set_attribute("class", "status status-app-c-2358986f").unwrap();
        let __interp4 = format!("{}", (*self.status.borrow()));
        let __t5 = document.create_text_node(&__interp4);
        __el3.append_child(&__t5).unwrap();
        let __t6 = document.create_text_node(" — clicks: ");
        __el3.append_child(&__t6).unwrap();
        let __interp7 = format!("{}", (*self.clicks.borrow()));
        let __t8 = document.create_text_node(&__interp7);
        __el3.append_child(&__t8).unwrap();
        __el0.append_child(&__el3).unwrap();
        let __el9 = document.create_element("div").unwrap();
        __el9.set_attribute("class", "items items-app-c-2358986f").unwrap();
        let __el10 = document.create_element("div").unwrap();
        __el10.set_attribute("class", "__fitz-child-Item").unwrap();
        __el9.append_child(&__el10).unwrap();
        let __child11 = {
            let mut __slot = self.__child_slot_0.borrow_mut();
            if __slot.is_none() { *__slot = Some(Item::new()); }
            __slot.as_ref().unwrap().clone()
        };
        *__child11.label.borrow_mut() = "Apple".to_string();
        {
            let __parent = self.clone();
            *__child11.__on_choose.borrow_mut() = Some(Box::new(move || {
                App::on_pick(&__parent);
            }));
        }
        let __el10_html = __el10.clone().dyn_into::<HtmlElement>().unwrap();
        __child11.mount_into(__el10_html).unwrap();
        let __el12 = document.create_element("div").unwrap();
        __el12.set_attribute("class", "__fitz-child-Item").unwrap();
        __el9.append_child(&__el12).unwrap();
        let __child13 = {
            let mut __slot = self.__child_slot_1.borrow_mut();
            if __slot.is_none() { *__slot = Some(Item::new()); }
            __slot.as_ref().unwrap().clone()
        };
        *__child13.label.borrow_mut() = "Banana".to_string();
        {
            let __parent = self.clone();
            *__child13.__on_choose.borrow_mut() = Some(Box::new(move || {
                App::on_pick(&__parent);
            }));
        }
        let __el12_html = __el12.clone().dyn_into::<HtmlElement>().unwrap();
        __child13.mount_into(__el12_html).unwrap();
        let __el14 = document.create_element("div").unwrap();
        __el14.set_attribute("class", "__fitz-child-Item").unwrap();
        __el9.append_child(&__el14).unwrap();
        let __child15 = {
            let mut __slot = self.__child_slot_2.borrow_mut();
            if __slot.is_none() { *__slot = Some(Item::new()); }
            __slot.as_ref().unwrap().clone()
        };
        *__child15.label.borrow_mut() = "Cherry".to_string();
        {
            let __parent = self.clone();
            *__child15.__on_choose.borrow_mut() = Some(Box::new(move || {
                App::on_pick(&__parent);
            }));
        }
        let __el14_html = __el14.clone().dyn_into::<HtmlElement>().unwrap();
        __child15.mount_into(__el14_html).unwrap();
        __el0.append_child(&__el9).unwrap();
        root.append_child(&__el0).unwrap();
    }
}

fn __inject_style_App_app_c_2358986f() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .picker-app-c-2358986f { font-family: system-ui, sans-serif; max-width: 460px; }\n    .status-app-c-2358986f { font-weight: 600; }\n    .items-app-c-2358986f { display: flex; gap: 8px; flex-wrap: wrap; }\n  "));
    let _ = head.append_child(&style_el);
}

pub struct Item {
    label: RefCell<String>,
    __on_choose: RefCell<Option<Box<dyn Fn()>>>,
    root: RefCell<Option<HtmlElement>>,
}

impl Item {
    pub fn new() -> Rc<Self> {
        Rc::new(Item {
            label: RefCell::new("".to_string()),
            __on_choose: RefCell::new(None),
            root: RefCell::new(None),
        })
    }

    fn choose(self: &Rc<Self>) {
        self.render();
        if let Some(__cb) = self.__on_choose.borrow().as_ref() { __cb(); }
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_Item_item_c_db46fce0();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("button").unwrap();
        __el0.set_attribute("class", "item item-item-c-db46fce0").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                Item::choose(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __el0.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __interp1 = format!("{}", (*self.label.borrow()));
        let __t2 = document.create_text_node(&__interp1);
        __el0.append_child(&__t2).unwrap();
        root.append_child(&__el0).unwrap();
    }
}

fn __inject_style_Item_item_c_db46fce0() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .item-item-c-db46fce0 { padding: 10px 16px; cursor: pointer; border: 1px solid #999; border-radius: 8px; background: white; font-size: 1rem; }\n    .item-item-c-db46fce0:hover { background: #f0f0f0; }\n  "));
    let _ = head.append_child(&style_el);
}



// Composed entry point — NOT part of emit_module output.
// `fitz build --target wasm-client` (Phase 11.5.c) appends this
// wrapper so the bundle mounts the root component when the
// browser calls the `start` export.
#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    console_error_panic_hook::set_once();
    let root = App::new();
    root.mount("#app")?;
    Ok(())
}
