// AUTO-GENERATED by `fitz build --target wasm-client`.
// Do NOT edit by hand — regenerate from the source `.fitzv`.
//
// Source: App.fitzv
//
// Composed by `src/view/wasm_build.rs::compose_lib_rs` (Phase 11.5.c).
// The tail below is the `#[wasm_bindgen(start)]` wrapper the CLI
// appends to the emitter output; the emitter itself does NOT emit
// the entry point so future targets (SSR, hybrid) can compose
// their own.

// Generated by fitz view WASM emitter (Fase 11.4.b).
// Do NOT edit — regenerate from the source `.fitzv`.

// Phase 11.5.e (§9.o Debt residual) — crate-level allows for
// the two cosmetic warnings that are structural to the
// emitter output, not correctness bugs:
//   - `non_snake_case`: component names are PascalCase by
//     convention (11.5.d), and the synthesised style helper
//     `__inject_style_<Component>_<scope>` reflects that.
//   - `unused_parens`: BinOp lowering wraps sub-expressions
//     in `(...)` to preserve precedence when nested. When
//     the BinOp is the entire RHS of an assignment the outer
//     parens are redundant but harmless.
#![allow(non_snake_case, unused_parens)]

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::atomic::{AtomicBool, Ordering};
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement};

// Phase 11.12 — hydration cursor helpers. Advance a sibling cursor to
// the next element / text node so the adopt walk maps template nodes
// onto the server-painted DOM in DFS order without re-creating them.
fn __flv_next_element(__cursor: &mut Option<web_sys::Node>) -> Option<web_sys::Element> {
    while let Some(__n) = __cursor.clone() {
        *__cursor = __n.next_sibling();
        if let Some(__el) = __n.dyn_ref::<web_sys::Element>() {
            return Some(__el.clone());
        }
    }
    None
}
fn __flv_next_text(__cursor: &mut Option<web_sys::Node>) -> Option<web_sys::Text> {
    while let Some(__n) = __cursor.clone() {
        *__cursor = __n.next_sibling();
        if let Some(__t) = __n.dyn_ref::<web_sys::Text>() {
            return Some(__t.clone());
        }
    }
    None
}

pub struct App {
    clicks: RefCell<i64>,
    last: RefCell<String>,
    __child_slot_0: RefCell<Option<Rc<Item>>>,
    __child_slot_1: RefCell<Option<Rc<Item>>>,
    __child_slot_2: RefCell<Option<Rc<Item>>>,
    root: RefCell<Option<HtmlElement>>,
}

impl App {
    pub fn new() -> Rc<Self> {
        Rc::new(App {
            clicks: RefCell::new(0i64),
            last: RefCell::new("none".to_string()),
            __child_slot_0: RefCell::new(None),
            __child_slot_1: RefCell::new(None),
            __child_slot_2: RefCell::new(None),
            root: RefCell::new(None),
        })
    }

    fn on_pick(self: &Rc<Self>, payload: &std::collections::HashMap<String, String>) {
        let __rhs = ((*self.clicks.borrow()) + 1i64);
        *self.clicks.borrow_mut() = __rhs;
        if payload.contains_key(&("label".to_string())) {
            let __rhs = payload.get(&("label".to_string())).cloned().unwrap_or_default();
            *self.last.borrow_mut() = __rhs;
        }
        self.render();
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_App_app_c_2358986f();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("div").unwrap();
        __el0.set_attribute("class", "picker picker-app-c-2358986f").unwrap();
        let __el1 = document.create_element("h1").unwrap();
        let __t2 = document.create_text_node("Event bubbling with payload on WASM");
        __el1.append_child(&__t2).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el3 = document.create_element("p").unwrap();
        __el3.set_attribute("class", "status status-app-c-2358986f").unwrap();
        let __t4 = document.create_text_node("last picked: ");
        __el3.append_child(&__t4).unwrap();
        let __interp5 = format!("{}", (*self.last.borrow()));
        let __t6 = document.create_text_node(&__interp5);
        __el3.append_child(&__t6).unwrap();
        let __t7 = document.create_text_node(" — clicks: ");
        __el3.append_child(&__t7).unwrap();
        let __interp8 = format!("{}", (*self.clicks.borrow()));
        let __t9 = document.create_text_node(&__interp8);
        __el3.append_child(&__t9).unwrap();
        __el0.append_child(&__el3).unwrap();
        let __el10 = document.create_element("div").unwrap();
        __el10.set_attribute("class", "items items-app-c-2358986f").unwrap();
        let __el11 = document.create_element("div").unwrap();
        __el11.set_attribute("class", "__fitz-child-Item").unwrap();
        __el10.append_child(&__el11).unwrap();
        let __child12 = {
            let mut __slot = self.__child_slot_0.borrow_mut();
            if __slot.is_none() { *__slot = Some(Item::new()); }
            __slot.as_ref().unwrap().clone()
        };
        *__child12.label.borrow_mut() = "Apple".to_string();
        {
            let __parent = self.clone();
            *__child12.__on_choose.borrow_mut() = Some(Box::new(move |__pl: &std::collections::HashMap<String, String>| {
                App::on_pick(&__parent, __pl);
            }));
        }
        let __el11_html = __el11.clone().dyn_into::<HtmlElement>().unwrap();
        __child12.mount_into(__el11_html).unwrap();
        let __el13 = document.create_element("div").unwrap();
        __el13.set_attribute("class", "__fitz-child-Item").unwrap();
        __el10.append_child(&__el13).unwrap();
        let __child14 = {
            let mut __slot = self.__child_slot_1.borrow_mut();
            if __slot.is_none() { *__slot = Some(Item::new()); }
            __slot.as_ref().unwrap().clone()
        };
        *__child14.label.borrow_mut() = "Banana".to_string();
        {
            let __parent = self.clone();
            *__child14.__on_choose.borrow_mut() = Some(Box::new(move |__pl: &std::collections::HashMap<String, String>| {
                App::on_pick(&__parent, __pl);
            }));
        }
        let __el13_html = __el13.clone().dyn_into::<HtmlElement>().unwrap();
        __child14.mount_into(__el13_html).unwrap();
        let __el15 = document.create_element("div").unwrap();
        __el15.set_attribute("class", "__fitz-child-Item").unwrap();
        __el10.append_child(&__el15).unwrap();
        let __child16 = {
            let mut __slot = self.__child_slot_2.borrow_mut();
            if __slot.is_none() { *__slot = Some(Item::new()); }
            __slot.as_ref().unwrap().clone()
        };
        *__child16.label.borrow_mut() = "Cherry".to_string();
        {
            let __parent = self.clone();
            *__child16.__on_choose.borrow_mut() = Some(Box::new(move |__pl: &std::collections::HashMap<String, String>| {
                App::on_pick(&__parent, __pl);
            }));
        }
        let __el15_html = __el15.clone().dyn_into::<HtmlElement>().unwrap();
        __child16.mount_into(__el15_html).unwrap();
        __el0.append_child(&__el10).unwrap();
        root.append_child(&__el0).unwrap();
    }
    fn __apply_state_json(self: &Rc<Self>, __json: &str) {
        let __v: serde_json::Value = match serde_json::from_str(__json) { Ok(__j) => __j, Err(_) => return, };
        let _ = (&__v, self);
        if let Some(__x) = __v.get("clicks").and_then(|__j| __j.as_i64()) { *self.clicks.borrow_mut() = __x; }
        if let Some(__x) = __v.get("last").and_then(|__j| __j.as_str()) { *self.last.borrow_mut() = __x.to_string(); }
    }

    pub fn hydrate(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_App_app_c_2358986f();
        if let Some(__sel) = web_sys::window().unwrap().document().unwrap().get_element_by_id("__flv_state_App") {
            if let Some(__txt) = __sel.text_content() { self.__apply_state_json(&__txt); }
        }
        let mut __cur_root = root.first_child();
        while let Some(__n) = __cur_root.clone() { if __n.dyn_ref::<web_sys::Element>().map(|__e| __e.tag_name() == "STYLE").unwrap_or(false) { __cur_root = __n.next_sibling(); } else { break; } }
        *self.root.borrow_mut() = Some(root);
        if let Some(__hel0) = __flv_next_element(&mut __cur_root) {
        let mut __hcur1 = __hel0.first_child();
        if let Some(__hel2) = __flv_next_element(&mut __hcur1) {
        let mut __hcur3 = __hel2.first_child();
        let _ = __flv_next_text(&mut __hcur3);
        }
        if let Some(__hel4) = __flv_next_element(&mut __hcur1) {
        let mut __hcur5 = __hel4.first_child();
        let _ = __flv_next_text(&mut __hcur5);
        let _ = __flv_next_text(&mut __hcur5);
        let _ = __flv_next_text(&mut __hcur5);
        let _ = __flv_next_text(&mut __hcur5);
        }
        if let Some(__hel6) = __flv_next_element(&mut __hcur1) {
        let mut __hcur7 = __hel6.first_child();
        if let Some(__hchild8) = __flv_next_element(&mut __hcur7) {
        let __child9 = {
            let mut __slot = self.__child_slot_0.borrow_mut();
            if __slot.is_none() { *__slot = Some(Item::new()); }
            __slot.as_ref().unwrap().clone()
        };
        *__child9.label.borrow_mut() = "Apple".to_string();
        {
            let __parent = self.clone();
            *__child9.__on_choose.borrow_mut() = Some(Box::new(move |__pl: &std::collections::HashMap<String, String>| {
                App::on_pick(&__parent, __pl);
            }));
        }
        let __hchild8_html = __hchild8.clone().dyn_into::<HtmlElement>().unwrap();
        __child9.hydrate(__hchild8_html).unwrap();
        }
        if let Some(__hchild10) = __flv_next_element(&mut __hcur7) {
        let __child11 = {
            let mut __slot = self.__child_slot_1.borrow_mut();
            if __slot.is_none() { *__slot = Some(Item::new()); }
            __slot.as_ref().unwrap().clone()
        };
        *__child11.label.borrow_mut() = "Banana".to_string();
        {
            let __parent = self.clone();
            *__child11.__on_choose.borrow_mut() = Some(Box::new(move |__pl: &std::collections::HashMap<String, String>| {
                App::on_pick(&__parent, __pl);
            }));
        }
        let __hchild10_html = __hchild10.clone().dyn_into::<HtmlElement>().unwrap();
        __child11.hydrate(__hchild10_html).unwrap();
        }
        if let Some(__hchild12) = __flv_next_element(&mut __hcur7) {
        let __child13 = {
            let mut __slot = self.__child_slot_2.borrow_mut();
            if __slot.is_none() { *__slot = Some(Item::new()); }
            __slot.as_ref().unwrap().clone()
        };
        *__child13.label.borrow_mut() = "Cherry".to_string();
        {
            let __parent = self.clone();
            *__child13.__on_choose.borrow_mut() = Some(Box::new(move |__pl: &std::collections::HashMap<String, String>| {
                App::on_pick(&__parent, __pl);
            }));
        }
        let __hchild12_html = __hchild12.clone().dyn_into::<HtmlElement>().unwrap();
        __child13.hydrate(__hchild12_html).unwrap();
        }
        }
        }
        Ok(())
    }

}

fn __inject_style_App_app_c_2358986f() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .picker-app-c-2358986f { font-family: system-ui, sans-serif; max-width: 460px; }\n    .status-app-c-2358986f { font-weight: 600; }\n    .items-app-c-2358986f { display: flex; gap: 8px; flex-wrap: wrap; }\n  "));
    let _ = head.append_child(&style_el);
}

pub struct Item {
    label: RefCell<String>,
    __on_choose: RefCell<Option<Box<dyn Fn(&std::collections::HashMap<String, String>)>>>,
    root: RefCell<Option<HtmlElement>>,
}

impl Item {
    pub fn new() -> Rc<Self> {
        Rc::new(Item {
            label: RefCell::new("".to_string()),
            __on_choose: RefCell::new(None),
            root: RefCell::new(None),
        })
    }

    fn choose(self: &Rc<Self>, payload: &std::collections::HashMap<String, String>) {
        self.render();
        if let Some(__cb) = self.__on_choose.borrow().as_ref() { __cb(payload); }
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_Item_item_c_db46fce0();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("button").unwrap();
        __el0.set_attribute("class", "item item-item-c-db46fce0").unwrap();
        __el0.set_attribute("data-flv-value-label", &format!("{}", (*self.label.borrow()))).unwrap();
        {
            let __self_clone = self.clone();
            let __evt_el = __el0.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                let mut __payload = std::collections::HashMap::<String, String>::new();
                __payload.insert("label".to_string(), __evt_el.get_attribute("data-flv-value-label").unwrap_or_default());
                Item::choose(&__self_clone, &__payload);
            }) as Box<dyn FnMut(Event)>);
            __el0.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __interp1 = format!("{}", (*self.label.borrow()));
        let __t2 = document.create_text_node(&__interp1);
        __el0.append_child(&__t2).unwrap();
        root.append_child(&__el0).unwrap();
    }
    fn __apply_state_json(self: &Rc<Self>, __json: &str) {
        let __v: serde_json::Value = match serde_json::from_str(__json) { Ok(__j) => __j, Err(_) => return, };
        let _ = (&__v, self);
        if let Some(__x) = __v.get("label").and_then(|__j| __j.as_str()) { *self.label.borrow_mut() = __x.to_string(); }
    }

    pub fn hydrate(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_Item_item_c_db46fce0();
        if let Some(__sel) = web_sys::window().unwrap().document().unwrap().get_element_by_id("__flv_state_Item") {
            if let Some(__txt) = __sel.text_content() { self.__apply_state_json(&__txt); }
        }
        let mut __cur_root = root.first_child();
        while let Some(__n) = __cur_root.clone() { if __n.dyn_ref::<web_sys::Element>().map(|__e| __e.tag_name() == "STYLE").unwrap_or(false) { __cur_root = __n.next_sibling(); } else { break; } }
        *self.root.borrow_mut() = Some(root);
        if let Some(__hel0) = __flv_next_element(&mut __cur_root) {
        {
            let __self_clone = self.clone();
            let __evt_el = __hel0.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                let mut __payload = std::collections::HashMap::<String, String>::new();
                __payload.insert("label".to_string(), __evt_el.get_attribute("data-flv-value-label").unwrap_or_default());
                Item::choose(&__self_clone, &__payload);
            }) as Box<dyn FnMut(Event)>);
            __hel0.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let mut __hcur1 = __hel0.first_child();
        let _ = __flv_next_text(&mut __hcur1);
        }
        Ok(())
    }

}

fn __inject_style_Item_item_c_db46fce0() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .item-item-c-db46fce0 { padding: 10px 16px; cursor: pointer; border: 1px solid #999; border-radius: 8px; background: white; font-size: 1rem; }\n    .item-item-c-db46fce0:hover { background: #f0f0f0; }\n  "));
    let _ = head.append_child(&style_el);
}



// Composed entry point — NOT part of emit_module output.
// `fitz build --target wasm-client` (Phase 11.5.c) appends this
// wrapper so the bundle mounts the root component when the
// browser calls the `start` export.
#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    console_error_panic_hook::set_once();
    let root = App::new();
    root.mount("#app")?;
    Ok(())
}
