// AUTO-GENERATED by `fitz build --target wasm-client`.
// Do NOT edit by hand — regenerate from the source `.fitzv`.
//
// Source: App.fitzv
//
// Composed by `src/view/wasm_build.rs::compose_lib_rs` (Phase 11.5.c).
// The tail below is the `#[wasm_bindgen(start)]` wrapper the CLI
// appends to the emitter output; the emitter itself does NOT emit
// the entry point so future targets (SSR, hybrid) can compose
// their own.

// Generated by fitz view WASM emitter (Fase 11.4.b).
// Do NOT edit — regenerate from the source `.fitzv`.

// Phase 11.5.e (§9.o Debt residual) — crate-level allows for
// the two cosmetic warnings that are structural to the
// emitter output, not correctness bugs:
//   - `non_snake_case`: component names are PascalCase by
//     convention (11.5.d), and the synthesised style helper
//     `__inject_style_<Component>_<scope>` reflects that.
//   - `unused_parens`: BinOp lowering wraps sub-expressions
//     in `(...)` to preserve precedence when nested. When
//     the BinOp is the entire RHS of an assignment the outer
//     parens are redundant but harmless.
#![allow(non_snake_case, unused_parens)]

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::atomic::{AtomicBool, Ordering};
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement};

#[allow(dead_code)]
#[derive(Clone)]
pub struct Card {
    id: i64,
    title: String,
    done: bool,
}

pub struct App {
    cards: RefCell<Vec<Card>>,
    next_id: RefCell<i64>,
    __child_map_0: RefCell<std::collections::HashMap<String, Rc<CardRow>>>,
    root: RefCell<Option<HtmlElement>>,
}

impl App {
    pub fn new() -> Rc<Self> {
        Rc::new(App {
            cards: RefCell::new(Vec::new()),
            next_id: RefCell::new(1i64),
            __child_map_0: RefCell::new(std::collections::HashMap::new()),
            root: RefCell::new(None),
        })
    }

    fn add(self: &Rc<Self>) {
        self.cards.borrow_mut().push(Card { id: (*self.next_id.borrow()), title: "Task".to_string(), done: false });
        let __rhs = ((*self.next_id.borrow()) + 1i64);
        *self.next_id.borrow_mut() = __rhs;
        self.render();
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_App_app_c_c2cdd401();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("div").unwrap();
        __el0.set_attribute("class", "board board-app-c-c2cdd401").unwrap();
        let __el1 = document.create_element("h1").unwrap();
        let __t2 = document.create_text_node("Nominal list on WASM");
        __el1.append_child(&__t2).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el3 = document.create_element("p").unwrap();
        __el3.set_attribute("class", "hint hint-app-c-c2cdd401").unwrap();
        let __t4 = document.create_text_node("Each row keeps its own tap counter. Tap a few, then add another task — the counters survive because each card id maps to a cached instance.");
        __el3.append_child(&__t4).unwrap();
        __el0.append_child(&__el3).unwrap();
        let __el5 = document.create_element("button").unwrap();
        __el5.set_attribute("class", "add add-app-c-c2cdd401").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                App::add(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __el5.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t6 = document.create_text_node("Add task (");
        __el5.append_child(&__t6).unwrap();
        let __interp7 = format!("{}", (*self.next_id.borrow()));
        let __t8 = document.create_text_node(&__interp7);
        __el5.append_child(&__t8).unwrap();
        let __t9 = document.create_text_node(")");
        __el5.append_child(&__t9).unwrap();
        __el0.append_child(&__el5).unwrap();
        let __el10 = document.create_element("ul").unwrap();
        __el10.set_attribute("class", "rows rows-app-c-c2cdd401").unwrap();
        let mut __seen_0 = std::collections::HashSet::<String>::new();
        let __for11 = (*self.cards.borrow()).clone();
        for c in __for11.iter().cloned() {
        let __el12 = document.create_element("div").unwrap();
        __el12.set_attribute("class", "__fitz-child-CardRow").unwrap();
        __el10.append_child(&__el12).unwrap();
        let __key = format!("{}", c.id.clone());
        __seen_0.insert(__key.clone());
        let __child13 = {
            let mut __map = self.__child_map_0.borrow_mut();
            __map.entry(__key.clone()).or_insert_with(|| CardRow::new()).clone()
        };
        *__child13.n.borrow_mut() = c.id.clone();
        *__child13.title.borrow_mut() = c.title.clone();
        let __el12_html = __el12.clone().dyn_into::<HtmlElement>().unwrap();
        __child13.mount_into(__el12_html).unwrap();
        }
        self.__child_map_0.borrow_mut().retain(|__k, _| __seen_0.contains(__k));
        __el0.append_child(&__el10).unwrap();
        root.append_child(&__el0).unwrap();
    }
}

fn __inject_style_App_app_c_c2cdd401() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .board-app-c-c2cdd401 { font-family: system-ui, sans-serif; max-width: 480px; }\n    .hint-app-c-c2cdd401 { color: #666; font-size: 0.9em; }\n    .add-app-c-c2cdd401 { padding: 8px 16px; cursor: pointer; border: 1px solid #999; border-radius: 6px; background: white; margin-bottom: 16px; }\n    .rows-app-c-c2cdd401 { list-style: none; padding: 0; display: flex; flex-direction: column; gap: 8px; }\n  "));
    let _ = head.append_child(&style_el);
}

pub struct CardRow {
    n: RefCell<i64>,
    title: RefCell<String>,
    taps: RefCell<i64>,
    root: RefCell<Option<HtmlElement>>,
}

impl CardRow {
    pub fn new() -> Rc<Self> {
        Rc::new(CardRow {
            n: RefCell::new(0i64),
            title: RefCell::new("".to_string()),
            taps: RefCell::new(0i64),
            root: RefCell::new(None),
        })
    }

    fn tap(self: &Rc<Self>) {
        let __rhs = ((*self.taps.borrow()) + 1i64);
        *self.taps.borrow_mut() = __rhs;
        self.render();
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_CardRow_card_row_c_a6029705();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("li").unwrap();
        __el0.set_attribute("class", "row row-card-row-c-a6029705").unwrap();
        let __el1 = document.create_element("span").unwrap();
        __el1.set_attribute("class", "id id-card-row-c-a6029705").unwrap();
        let __interp2 = format!("{}", (*self.n.borrow()));
        let __t3 = document.create_text_node(&__interp2);
        __el1.append_child(&__t3).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el4 = document.create_element("span").unwrap();
        __el4.set_attribute("class", "label label-card-row-c-a6029705").unwrap();
        let __interp5 = format!("{}", (*self.title.borrow()));
        let __t6 = document.create_text_node(&__interp5);
        __el4.append_child(&__t6).unwrap();
        __el0.append_child(&__el4).unwrap();
        let __el7 = document.create_element("button").unwrap();
        __el7.set_attribute("class", "tap tap-card-row-c-a6029705").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                CardRow::tap(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __el7.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t8 = document.create_text_node("taps: ");
        __el7.append_child(&__t8).unwrap();
        let __interp9 = format!("{}", (*self.taps.borrow()));
        let __t10 = document.create_text_node(&__interp9);
        __el7.append_child(&__t10).unwrap();
        __el0.append_child(&__el7).unwrap();
        root.append_child(&__el0).unwrap();
    }
}

fn __inject_style_CardRow_card_row_c_a6029705() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .row-card-row-c-a6029705 { display: flex; align-items: center; gap: 12px; border: 1px solid #ddd; border-radius: 8px; padding: 10px 14px; background: #fafafa; }\n    .id-card-row-c-a6029705 { font-variant-numeric: tabular-nums; color: #999; font-size: 0.85em; }\n    .label-card-row-c-a6029705 { flex: 1; }\n    .tap-card-row-c-a6029705 { padding: 6px 12px; cursor: pointer; border: 1px solid #999; border-radius: 6px; background: white; }\n  "));
    let _ = head.append_child(&style_el);
}



// Composed entry point — NOT part of emit_module output.
// `fitz build --target wasm-client` (Phase 11.5.c) appends this
// wrapper so the bundle mounts the root component when the
// browser calls the `start` export.
#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    console_error_panic_hook::set_once();
    let root = App::new();
    root.mount("#app")?;
    Ok(())
}
