// AUTO-GENERATED by `fitz build --target wasm-client`.
// Do NOT edit by hand — regenerate from the source `.fitzv`.
//
// Source: App.fitzv
//
// Composed by `src/view/wasm_build.rs::compose_lib_rs` (Phase 11.5.c).
// The tail below is the `#[wasm_bindgen(start)]` wrapper the CLI
// appends to the emitter output; the emitter itself does NOT emit
// the entry point so future targets (SSR, hybrid) can compose
// their own.

// Generated by fitz view WASM emitter (Fase 11.4.b).
// Do NOT edit — regenerate from the source `.fitzv`.

// Phase 11.5.e (§9.o Debt residual) — crate-level allows for
// the two cosmetic warnings that are structural to the
// emitter output, not correctness bugs:
//   - `non_snake_case`: component names are PascalCase by
//     convention (11.5.d), and the synthesised style helper
//     `__inject_style_<Component>_<scope>` reflects that.
//   - `unused_parens`: BinOp lowering wraps sub-expressions
//     in `(...)` to preserve precedence when nested. When
//     the BinOp is the entire RHS of an assignment the outer
//     parens are redundant but harmless.
#![allow(non_snake_case, unused_parens)]

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::atomic::{AtomicBool, Ordering};
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement};

pub struct App {
    columns: RefCell<Vec<String>>,
    bumps: RefCell<i64>,
    __child_map_0: RefCell<std::collections::HashMap<String, Rc<Column>>>,
    root: RefCell<Option<HtmlElement>>,
}

impl App {
    pub fn new() -> Rc<Self> {
        Rc::new(App {
            columns: RefCell::new(vec!["To Do".to_string(), "In Progress".to_string(), "Done".to_string()]),
            bumps: RefCell::new(0i64),
            __child_map_0: RefCell::new(std::collections::HashMap::new()),
            root: RefCell::new(None),
        })
    }

    fn bump(self: &Rc<Self>) {
        let __rhs = ((*self.bumps.borrow()) + 1i64);
        *self.bumps.borrow_mut() = __rhs;
        self.render();
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_App_app_c_612bcf85();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("div").unwrap();
        __el0.set_attribute("class", "board board-app-c-612bcf85").unwrap();
        let __el1 = document.create_element("h1").unwrap();
        let __t2 = document.create_text_node("Keyed children on WASM");
        __el1.append_child(&__t2).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el3 = document.create_element("p").unwrap();
        __el3.set_attribute("class", "hint hint-app-c-612bcf85").unwrap();
        let __t4 = document.create_text_node("Each column keeps its own tap counter. Tap a column, then re-render the parent — the counters survive because each key maps to a cached instance.");
        __el3.append_child(&__t4).unwrap();
        __el0.append_child(&__el3).unwrap();
        let __el5 = document.create_element("button").unwrap();
        __el5.set_attribute("class", "bump bump-app-c-612bcf85").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                App::bump(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __el5.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t6 = document.create_text_node("re-render parent (");
        __el5.append_child(&__t6).unwrap();
        let __interp7 = format!("{}", (*self.bumps.borrow()));
        let __t8 = document.create_text_node(&__interp7);
        __el5.append_child(&__t8).unwrap();
        let __t9 = document.create_text_node(")");
        __el5.append_child(&__t9).unwrap();
        __el0.append_child(&__el5).unwrap();
        let __el10 = document.create_element("div").unwrap();
        __el10.set_attribute("class", "columns columns-app-c-612bcf85").unwrap();
        let mut __seen_0 = std::collections::HashSet::<String>::new();
        let __for11 = (*self.columns.borrow()).clone();
        for name in __for11.iter().cloned() {
        let __el12 = document.create_element("div").unwrap();
        __el12.set_attribute("class", "__fitz-child-Column").unwrap();
        __el10.append_child(&__el12).unwrap();
        let __key = format!("{}", name);
        __seen_0.insert(__key.clone());
        let __child13 = {
            let mut __map = self.__child_map_0.borrow_mut();
            __map.entry(__key.clone()).or_insert_with(|| Column::new()).clone()
        };
        *__child13.title.borrow_mut() = name.clone();
        let __el12_html = __el12.clone().dyn_into::<HtmlElement>().unwrap();
        __child13.mount_into(__el12_html).unwrap();
        }
        self.__child_map_0.borrow_mut().retain(|__k, _| __seen_0.contains(__k));
        __el0.append_child(&__el10).unwrap();
        root.append_child(&__el0).unwrap();
    }
}

fn __inject_style_App_app_c_612bcf85() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .board-app-c-612bcf85 { font-family: system-ui, sans-serif; }\n    .hint-app-c-612bcf85 { color: #666; font-size: 0.9em; }\n    .bump-app-c-612bcf85 { padding: 8px 16px; cursor: pointer; border: 1px solid #999; border-radius: 6px; background: white; margin-bottom: 16px; }\n    .columns-app-c-612bcf85 { display: flex; flex-wrap: wrap; gap: 12px; }\n  "));
    let _ = head.append_child(&style_el);
}

pub struct Column {
    title: RefCell<String>,
    taps: RefCell<i64>,
    root: RefCell<Option<HtmlElement>>,
}

impl Column {
    pub fn new() -> Rc<Self> {
        Rc::new(Column {
            title: RefCell::new("".to_string()),
            taps: RefCell::new(0i64),
            root: RefCell::new(None),
        })
    }

    fn tap(self: &Rc<Self>) {
        let __rhs = ((*self.taps.borrow()) + 1i64);
        *self.taps.borrow_mut() = __rhs;
        self.render();
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_Column_column_c_fb6208a2();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("div").unwrap();
        __el0.set_attribute("class", "column column-column-c-fb6208a2").unwrap();
        let __el1 = document.create_element("div").unwrap();
        __el1.set_attribute("class", "title title-column-c-fb6208a2").unwrap();
        let __interp2 = format!("{}", (*self.title.borrow()));
        let __t3 = document.create_text_node(&__interp2);
        __el1.append_child(&__t3).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el4 = document.create_element("button").unwrap();
        __el4.set_attribute("class", "tap tap-column-c-fb6208a2").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                Column::tap(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __el4.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t5 = document.create_text_node("taps: ");
        __el4.append_child(&__t5).unwrap();
        let __interp6 = format!("{}", (*self.taps.borrow()));
        let __t7 = document.create_text_node(&__interp6);
        __el4.append_child(&__t7).unwrap();
        __el0.append_child(&__el4).unwrap();
        root.append_child(&__el0).unwrap();
    }
}

fn __inject_style_Column_column_c_fb6208a2() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .column-column-c-fb6208a2 { flex: 1 1 140px; min-width: 120px; border: 1px solid #ddd; border-radius: 8px; padding: 16px; background: #fafafa; }\n    .title-column-c-fb6208a2 { font-size: 0.85em; text-transform: uppercase; letter-spacing: 0.05em; color: #666; margin-bottom: 8px; }\n    .tap-column-c-fb6208a2 { padding: 6px 12px; cursor: pointer; border: 1px solid #999; border-radius: 6px; background: white; }\n  "));
    let _ = head.append_child(&style_el);
}



// Composed entry point — NOT part of emit_module output.
// `fitz build --target wasm-client` (Phase 11.5.c) appends this
// wrapper so the bundle mounts the root component when the
// browser calls the `start` export.
#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    console_error_panic_hook::set_once();
    let root = App::new();
    root.mount("#app")?;
    Ok(())
}
