// AUTO-GENERATED by `fitz build --target wasm-client`.
// Do NOT edit by hand — regenerate from the source `.fitzv`.
//
// Source: App.fitzv
//
// Composed by `src/view/wasm_build.rs::compose_lib_rs` (Phase 11.5.c).
// The tail below is the `#[wasm_bindgen(start)]` wrapper the CLI
// appends to the emitter output; the emitter itself does NOT emit
// the entry point so future targets (SSR, hybrid) can compose
// their own.

// Generated by fitz view WASM emitter (Fase 11.4.b).
// Do NOT edit — regenerate from the source `.fitzv`.

// Phase 11.5.e (§9.o Debt residual) — crate-level allows for
// the two cosmetic warnings that are structural to the
// emitter output, not correctness bugs:
//   - `non_snake_case`: component names are PascalCase by
//     convention (11.5.d), and the synthesised style helper
//     `__inject_style_<Component>_<scope>` reflects that.
//   - `unused_parens`: BinOp lowering wraps sub-expressions
//     in `(...)` to preserve precedence when nested. When
//     the BinOp is the entire RHS of an assignment the outer
//     parens are redundant but harmless.
#![allow(non_snake_case, unused_parens)]

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::atomic::{AtomicBool, Ordering};
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement};

// Phase 11.12 — hydration cursor helpers. Advance a sibling cursor to
// the next element / text node so the adopt walk maps template nodes
// onto the server-painted DOM in DFS order without re-creating them.
fn __flv_next_element(__cursor: &mut Option<web_sys::Node>) -> Option<web_sys::Element> {
    while let Some(__n) = __cursor.clone() {
        *__cursor = __n.next_sibling();
        if let Some(__el) = __n.dyn_ref::<web_sys::Element>() {
            return Some(__el.clone());
        }
    }
    None
}
fn __flv_next_text(__cursor: &mut Option<web_sys::Node>) -> Option<web_sys::Text> {
    while let Some(__n) = __cursor.clone() {
        *__cursor = __n.next_sibling();
        if let Some(__t) = __n.dyn_ref::<web_sys::Text>() {
            return Some(__t.clone());
        }
    }
    None
}

pub struct Greeter {
    first: RefCell<String>,
    last: RefCell<String>,
    full: RefCell<String>,
    greeting: RefCell<String>,
    __kattr_0: RefCell<Option<web_sys::Element>>,
    __kattr_1: RefCell<Option<web_sys::Element>>,
    __ktext_2: RefCell<Option<web_sys::Text>>,
    __ktext_3: RefCell<Option<web_sys::Text>>,
    __built: RefCell<bool>,
    root: RefCell<Option<HtmlElement>>,
}

impl Greeter {
    pub fn new() -> Rc<Self> {
        Rc::new(Greeter {
            first: RefCell::new("Ada".to_string()),
            last: RefCell::new("Lovelace".to_string()),
            full: RefCell::new(String::new()),
            greeting: RefCell::new(String::new()),
            __kattr_0: RefCell::new(None),
            __kattr_1: RefCell::new(None),
            __ktext_2: RefCell::new(None),
            __ktext_3: RefCell::new(None),
            __built: RefCell::new(false),
            root: RefCell::new(None),
        })
    }

    fn on_first(self: &Rc<Self>, payload: &std::collections::HashMap<String, String>) {
        let __rhs = payload.get(&("value".to_string())).cloned().unwrap_or_default();
        *self.first.borrow_mut() = __rhs;
        self.render();
    }

    fn on_last(self: &Rc<Self>, payload: &std::collections::HashMap<String, String>) {
        let __rhs = payload.get(&("value".to_string())).cloned().unwrap_or_default();
        *self.last.borrow_mut() = __rhs;
        self.render();
    }

    fn __recompute_derived(self: &Rc<Self>) {
        *self.full.borrow_mut() = format!("{} {}", (*self.first.borrow()), (*self.last.borrow()));
        *self.greeting.borrow_mut() = format!("Hello, {}!", (*self.full.borrow()));
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_Greeter_greeter_c_f0dd7508();
        *self.__built.borrow_mut() = false;
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        self.__recompute_derived();
        if *self.__built.borrow() {
            self.__patch();
        } else {
            self.__build();
            *self.__built.borrow_mut() = true;
        }
    }

    fn __build(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("div").unwrap();
        __el0.set_attribute("class", "greeter greeter-greeter-c-f0dd7508").unwrap();
        let __el1 = document.create_element("label").unwrap();
        __el1.set_attribute("class", "row row-greeter-c-f0dd7508").unwrap();
        let __el2 = document.create_element("span").unwrap();
        let __t3 = document.create_text_node("First");
        __el2.append_child(&__t3).unwrap();
        __el1.append_child(&__el2).unwrap();
        let __el4 = document.create_element("input").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |__evt: Event| {
                let mut __payload = std::collections::HashMap::<String, String>::new();
                if let Some(__t) = __evt.target() {
                    if let Some(__el) = __t.dyn_ref::<web_sys::HtmlInputElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlSelectElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlTextAreaElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    }
                }
                Greeter::on_first(&__self_clone, &__payload);
            }) as Box<dyn FnMut(Event)>);
            __el4.add_event_listener_with_callback("input", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        __el4.set_attribute("value", &format!("{}", (*self.first.borrow()))).unwrap();
        *self.__kattr_0.borrow_mut() = Some(__el4.clone());
        __el4.set_attribute("autocomplete", "off").unwrap();
        __el1.append_child(&__el4).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el5 = document.create_element("label").unwrap();
        __el5.set_attribute("class", "row row-greeter-c-f0dd7508").unwrap();
        let __el6 = document.create_element("span").unwrap();
        let __t7 = document.create_text_node("Last");
        __el6.append_child(&__t7).unwrap();
        __el5.append_child(&__el6).unwrap();
        let __el8 = document.create_element("input").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |__evt: Event| {
                let mut __payload = std::collections::HashMap::<String, String>::new();
                if let Some(__t) = __evt.target() {
                    if let Some(__el) = __t.dyn_ref::<web_sys::HtmlInputElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlSelectElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlTextAreaElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    }
                }
                Greeter::on_last(&__self_clone, &__payload);
            }) as Box<dyn FnMut(Event)>);
            __el8.add_event_listener_with_callback("input", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        __el8.set_attribute("value", &format!("{}", (*self.last.borrow()))).unwrap();
        *self.__kattr_1.borrow_mut() = Some(__el8.clone());
        __el8.set_attribute("autocomplete", "off").unwrap();
        __el5.append_child(&__el8).unwrap();
        __el0.append_child(&__el5).unwrap();
        let __el9 = document.create_element("p").unwrap();
        __el9.set_attribute("class", "full full-greeter-c-f0dd7508").unwrap();
        let __t10 = document.create_text_node("Full name: ");
        __el9.append_child(&__t10).unwrap();
        let __interp11 = format!("{}", (*self.full.borrow()));
        let __t12 = document.create_text_node(&__interp11);
        __el9.append_child(&__t12).unwrap();
        *self.__ktext_2.borrow_mut() = Some(__t12.clone());
        __el0.append_child(&__el9).unwrap();
        let __el13 = document.create_element("p").unwrap();
        __el13.set_attribute("class", "greeting greeting-greeter-c-f0dd7508").unwrap();
        let __interp14 = format!("{}", (*self.greeting.borrow()));
        let __t15 = document.create_text_node(&__interp14);
        __el13.append_child(&__t15).unwrap();
        *self.__ktext_3.borrow_mut() = Some(__t15.clone());
        __el0.append_child(&__el13).unwrap();
        root.append_child(&__el0).unwrap();
    }

    fn __patch(self: &Rc<Self>) {
        if let Some(__el) = self.__kattr_0.borrow().as_ref() { let _ = __el.set_attribute("value", &format!("{}", (*self.first.borrow()))); }
        if let Some(__el) = self.__kattr_1.borrow().as_ref() { let _ = __el.set_attribute("value", &format!("{}", (*self.last.borrow()))); }
        if let Some(__n) = self.__ktext_2.borrow().as_ref() { __n.set_data(&format!("{}", (*self.full.borrow()))); }
        if let Some(__n) = self.__ktext_3.borrow().as_ref() { __n.set_data(&format!("{}", (*self.greeting.borrow()))); }
    }

    fn __apply_state_json(self: &Rc<Self>, __json: &str) {
        let __v: serde_json::Value = match serde_json::from_str(__json) { Ok(__j) => __j, Err(_) => return, };
        let _ = (&__v, self);
        if let Some(__x) = __v.get("first").and_then(|__j| __j.as_str()) { *self.first.borrow_mut() = __x.to_string(); }
        if let Some(__x) = __v.get("last").and_then(|__j| __j.as_str()) { *self.last.borrow_mut() = __x.to_string(); }
    }

    pub fn hydrate(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_Greeter_greeter_c_f0dd7508();
        if let Some(__sel) = web_sys::window().unwrap().document().unwrap().get_element_by_id("__flv_state_Greeter") {
            if let Some(__txt) = __sel.text_content() { self.__apply_state_json(&__txt); }
        }
        self.__recompute_derived();
        let mut __cur_root = root.first_child();
        *self.root.borrow_mut() = Some(root);
        if let Some(__hel0) = __flv_next_element(&mut __cur_root) {
        let mut __hcur1 = __hel0.first_child();
        if let Some(__hel2) = __flv_next_element(&mut __hcur1) {
        let mut __hcur3 = __hel2.first_child();
        if let Some(__hel4) = __flv_next_element(&mut __hcur3) {
        let mut __hcur5 = __hel4.first_child();
        let _ = __flv_next_text(&mut __hcur5);
        }
        if let Some(__hel6) = __flv_next_element(&mut __hcur3) {
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |__evt: Event| {
                let mut __payload = std::collections::HashMap::<String, String>::new();
                if let Some(__t) = __evt.target() {
                    if let Some(__el) = __t.dyn_ref::<web_sys::HtmlInputElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlSelectElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlTextAreaElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    }
                }
                Greeter::on_first(&__self_clone, &__payload);
            }) as Box<dyn FnMut(Event)>);
            __hel6.add_event_listener_with_callback("input", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        *self.__kattr_0.borrow_mut() = Some(__hel6.clone());
        }
        }
        if let Some(__hel8) = __flv_next_element(&mut __hcur1) {
        let mut __hcur9 = __hel8.first_child();
        if let Some(__hel10) = __flv_next_element(&mut __hcur9) {
        let mut __hcur11 = __hel10.first_child();
        let _ = __flv_next_text(&mut __hcur11);
        }
        if let Some(__hel12) = __flv_next_element(&mut __hcur9) {
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |__evt: Event| {
                let mut __payload = std::collections::HashMap::<String, String>::new();
                if let Some(__t) = __evt.target() {
                    if let Some(__el) = __t.dyn_ref::<web_sys::HtmlInputElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlSelectElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlTextAreaElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    }
                }
                Greeter::on_last(&__self_clone, &__payload);
            }) as Box<dyn FnMut(Event)>);
            __hel12.add_event_listener_with_callback("input", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        *self.__kattr_1.borrow_mut() = Some(__hel12.clone());
        }
        }
        if let Some(__hel14) = __flv_next_element(&mut __hcur1) {
        let mut __hcur15 = __hel14.first_child();
        let _ = __flv_next_text(&mut __hcur15);
        if let Some(__hn) = __flv_next_text(&mut __hcur15) { *self.__ktext_2.borrow_mut() = Some(__hn); }
        }
        if let Some(__hel16) = __flv_next_element(&mut __hcur1) {
        let mut __hcur17 = __hel16.first_child();
        if let Some(__hn) = __flv_next_text(&mut __hcur17) { *self.__ktext_3.borrow_mut() = Some(__hn); }
        }
        }
        *self.__built.borrow_mut() = true;
        Ok(())
    }

}

fn __inject_style_Greeter_greeter_c_f0dd7508() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .greeter-greeter-c-f0dd7508 { font-family: system-ui, sans-serif; display: grid; gap: 8px; max-width: 360px; }\n    .row-greeter-c-f0dd7508 { display: flex; gap: 8px; align-items: center; }\n    .greeting-greeter-c-f0dd7508 { font-weight: bold; }\n  "));
    let _ = head.append_child(&style_el);
}



// Composed entry point — NOT part of emit_module output.
// `fitz build --target wasm-client` appends this wrapper. Phase
// 11.12: hydrate the server-painted DOM when the mount root
// already has content, else fresh-mount into an empty root.
#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    console_error_panic_hook::set_once();
    let root = Greeter::new();
    let __document = web_sys::window().unwrap().document().unwrap();
    if let Some(__mount) = __document.query_selector("#app")? {
        if __mount.first_element_child().is_some() {
            let __el = __mount.dyn_into::<web_sys::HtmlElement>()?;
            return root.hydrate(__el);
        }
    }
    root.mount("#app")?;
    Ok(())
}
