// AUTO-GENERATED by `tests/view_counter_wasm_smoke.rs`.
// Do NOT edit by hand — regenerate via:
//
//   cargo test --test view_counter_wasm_smoke
//
// The source of truth is `../Counter.fitzv`.

// Generated by fitz view WASM emitter (Fase 11.4.b).
// Do NOT edit — regenerate from the source `.fitzv`.

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::atomic::{AtomicBool, Ordering};
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement};

pub struct Counter {
    count: RefCell<i64>,
    root: RefCell<Option<HtmlElement>>,
}

impl Counter {
    pub fn new() -> Rc<Self> {
        Rc::new(Counter {
            count: RefCell::new(0i64),
            root: RefCell::new(None),
        })
    }

    fn increment(self: &Rc<Self>) {
        let __rhs = ((*self.count.borrow()) + 1i64);
        *self.count.borrow_mut() = __rhs;
        self.render();
    }

    fn decrement(self: &Rc<Self>) {
        let __rhs = ((*self.count.borrow()) - 1i64);
        *self.count.borrow_mut() = __rhs;
        self.render();
    }

    fn reset(self: &Rc<Self>) {
        let __rhs = 0i64;
        *self.count.borrow_mut() = __rhs;
        self.render();
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        __inject_style_Counter_counter_c_8b71bce8();
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("div").unwrap();
        __el0.set_attribute("class", "counter counter-counter-c-8b71bce8").unwrap();
        let __el1 = document.create_element("button").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                Counter::decrement(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __el1.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t2 = document.create_text_node("-");
        __el1.append_child(&__t2).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el3 = document.create_element("span").unwrap();
        __el3.set_attribute("class", "value value-counter-c-8b71bce8").unwrap();
        let __interp4 = format!("{}", (*self.count.borrow()));
        let __t5 = document.create_text_node(&__interp4);
        __el3.append_child(&__t5).unwrap();
        __el0.append_child(&__el3).unwrap();
        let __el6 = document.create_element("button").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                Counter::increment(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __el6.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t7 = document.create_text_node("+");
        __el6.append_child(&__t7).unwrap();
        __el0.append_child(&__el6).unwrap();
        let __el8 = document.create_element("button").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                Counter::reset(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __el8.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t9 = document.create_text_node("reset");
        __el8.append_child(&__t9).unwrap();
        __el0.append_child(&__el8).unwrap();
        root.append_child(&__el0).unwrap();
    }
}

fn __inject_style_Counter_counter_c_8b71bce8() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .counter-counter-c-8b71bce8 { display: flex; gap: 8px; align-items: center; font-family: sans-serif; }\n    .value-counter-c-8b71bce8 { min-width: 3ch; text-align: center; font-weight: bold; font-size: 1.5em; }\n  "));
    let _ = head.append_child(&style_el);
}



// Composed entry point — NOT part of emit_module output.
// Fase 11.5 CLI will emit an equivalent wrapper per target.
#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    console_error_panic_hook::set_once();
    let counter = Counter::new();
    counter.mount("#app")?;
    Ok(())
}
