// AUTO-GENERATED by `fitz build --target wasm-client`.
// Do NOT edit by hand — regenerate from the source `.fitzv`.
//
// Source: App.fitzv
//
// Composed by `src/view/wasm_build.rs::compose_lib_rs` (Phase 11.5.c).
// The tail below is the `#[wasm_bindgen(start)]` wrapper the CLI
// appends to the emitter output; the emitter itself does NOT emit
// the entry point so future targets (SSR, hybrid) can compose
// their own.

// Generated by fitz view WASM emitter (Fase 11.4.b).
// Do NOT edit — regenerate from the source `.fitzv`.

// Phase 11.5.e (§9.o Debt residual) — crate-level allows for
// the two cosmetic warnings that are structural to the
// emitter output, not correctness bugs:
//   - `non_snake_case`: component names are PascalCase by
//     convention (11.5.d), and the synthesised style helper
//     `__inject_style_<Component>_<scope>` reflects that.
//   - `unused_parens`: BinOp lowering wraps sub-expressions
//     in `(...)` to preserve precedence when nested. When
//     the BinOp is the entire RHS of an assignment the outer
//     parens are redundant but harmless.
#![allow(non_snake_case, unused_parens)]

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::atomic::{AtomicBool, Ordering};
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement};

#[allow(dead_code)]
#[derive(Clone)]
pub struct Card {
    id: i64,
    title: String,
    column: String,
}

#[allow(dead_code)]
fn advance(c: Card) -> Card {
    let moved = next_column(c.column.clone());
    return Card { id: c.id.clone(), title: c.title.clone(), column: moved };
}

#[allow(dead_code)]
fn cards_in(all: Vec<Card>, col: String) -> Vec<Card> {
    return (all).clone().into_iter().filter(|__it| { let c = __it.clone(); (c.column.clone() == col) }).collect::<Vec<_>>();
}

#[allow(dead_code)]
fn make_card(id: i64, title: String) -> Card {
    return Card { id: id, title: title, column: "todo".to_string() };
}

#[allow(dead_code)]
fn next_column(current: String) -> String {
    if (current == "todo".to_string()) {
        return "in_progress".to_string();
    }
    if (current == "in_progress".to_string()) {
        return "done".to_string();
    }
    return current;
}

pub struct Board {
    cards: RefCell<Vec<Card>>,
    next_id: RefCell<i64>,
    root: RefCell<Option<HtmlElement>>,
}

impl Board {
    pub fn new() -> Rc<Self> {
        Rc::new(Board {
            cards: RefCell::new(Vec::new()),
            next_id: RefCell::new(1i64),
            root: RefCell::new(None),
        })
    }

    fn add(self: &Rc<Self>) {
        self.cards.borrow_mut().push(make_card((*self.next_id.borrow()).clone(), "Task".to_string()));
        let __rhs = ((*self.next_id.borrow()) + 1i64);
        *self.next_id.borrow_mut() = __rhs;
        self.render();
    }

    fn advance_all(self: &Rc<Self>) {
        let __rhs = ((*self.cards.borrow())).clone().into_iter().map(|c| advance(c.clone())).collect::<Vec<_>>();
        *self.cards.borrow_mut() = __rhs;
        self.render();
    }

    fn reset(self: &Rc<Self>) {
        let __rhs = vec![];
        *self.cards.borrow_mut() = __rhs;
        let __rhs = 1i64;
        *self.next_id.borrow_mut() = __rhs;
        self.render();
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_Board_board_c_bc13d758();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("div").unwrap();
        __el0.set_attribute("class", "board board-board-c-bc13d758").unwrap();
        let __el1 = document.create_element("h1").unwrap();
        let __t2 = document.create_text_node("Mini board on WASM");
        __el1.append_child(&__t2).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el3 = document.create_element("p").unwrap();
        __el3.set_attribute("class", "hint hint-board-c-bc13d758").unwrap();
        let __t4 = document.create_text_node("Every action runs entirely client-side. \"Add\" builds a Card with the imported make_card helper, \"advance all\" moves each card one column by mapping the imported advance helper over the list, and each column is a filtered view over the imported cards_in helper.");
        __el3.append_child(&__t4).unwrap();
        __el0.append_child(&__el3).unwrap();
        let __el5 = document.create_element("div").unwrap();
        __el5.set_attribute("class", "controls controls-board-c-bc13d758").unwrap();
        let __el6 = document.create_element("button").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                Board::add(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __el6.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t7 = document.create_text_node("add task (");
        __el6.append_child(&__t7).unwrap();
        let __interp8 = format!("{}", (*self.next_id.borrow()));
        let __t9 = document.create_text_node(&__interp8);
        __el6.append_child(&__t9).unwrap();
        let __t10 = document.create_text_node(")");
        __el6.append_child(&__t10).unwrap();
        __el5.append_child(&__el6).unwrap();
        let __el11 = document.create_element("button").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                Board::advance_all(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __el11.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t12 = document.create_text_node("advance all");
        __el11.append_child(&__t12).unwrap();
        __el5.append_child(&__el11).unwrap();
        let __el13 = document.create_element("button").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                Board::reset(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __el13.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t14 = document.create_text_node("reset");
        __el13.append_child(&__t14).unwrap();
        __el5.append_child(&__el13).unwrap();
        __el0.append_child(&__el5).unwrap();
        let __el15 = document.create_element("div").unwrap();
        __el15.set_attribute("class", "cols cols-board-c-bc13d758").unwrap();
        let __el16 = document.create_element("section").unwrap();
        __el16.set_attribute("class", "col col-board-c-bc13d758").unwrap();
        let __el17 = document.create_element("h2").unwrap();
        let __t18 = document.create_text_node("To Do (");
        __el17.append_child(&__t18).unwrap();
        let __interp19 = format!("{}", ((cards_in((*self.cards.borrow()).clone(), "todo".to_string())).len() as i64));
        let __t20 = document.create_text_node(&__interp19);
        __el17.append_child(&__t20).unwrap();
        let __t21 = document.create_text_node(")");
        __el17.append_child(&__t21).unwrap();
        __el16.append_child(&__el17).unwrap();
        let __el22 = document.create_element("ul").unwrap();
        let __for23 = cards_in((*self.cards.borrow()).clone(), "todo".to_string());
        for c in __for23.into_iter() {
        let __el24 = document.create_element("li").unwrap();
        let __interp25 = format!("{}", c.title.clone());
        let __t26 = document.create_text_node(&__interp25);
        __el24.append_child(&__t26).unwrap();
        let __interp27 = format!("{}", c.id.clone());
        let __t28 = document.create_text_node(&__interp27);
        __el24.append_child(&__t28).unwrap();
        __el22.append_child(&__el24).unwrap();
        }
        __el16.append_child(&__el22).unwrap();
        __el15.append_child(&__el16).unwrap();
        let __el29 = document.create_element("section").unwrap();
        __el29.set_attribute("class", "col col-board-c-bc13d758").unwrap();
        let __el30 = document.create_element("h2").unwrap();
        let __t31 = document.create_text_node("In Progress (");
        __el30.append_child(&__t31).unwrap();
        let __interp32 = format!("{}", ((cards_in((*self.cards.borrow()).clone(), "in_progress".to_string())).len() as i64));
        let __t33 = document.create_text_node(&__interp32);
        __el30.append_child(&__t33).unwrap();
        let __t34 = document.create_text_node(")");
        __el30.append_child(&__t34).unwrap();
        __el29.append_child(&__el30).unwrap();
        let __el35 = document.create_element("ul").unwrap();
        let __for36 = cards_in((*self.cards.borrow()).clone(), "in_progress".to_string());
        for c in __for36.into_iter() {
        let __el37 = document.create_element("li").unwrap();
        let __interp38 = format!("{}", c.title.clone());
        let __t39 = document.create_text_node(&__interp38);
        __el37.append_child(&__t39).unwrap();
        let __interp40 = format!("{}", c.id.clone());
        let __t41 = document.create_text_node(&__interp40);
        __el37.append_child(&__t41).unwrap();
        __el35.append_child(&__el37).unwrap();
        }
        __el29.append_child(&__el35).unwrap();
        __el15.append_child(&__el29).unwrap();
        let __el42 = document.create_element("section").unwrap();
        __el42.set_attribute("class", "col col-board-c-bc13d758").unwrap();
        let __el43 = document.create_element("h2").unwrap();
        let __t44 = document.create_text_node("Done (");
        __el43.append_child(&__t44).unwrap();
        let __interp45 = format!("{}", ((cards_in((*self.cards.borrow()).clone(), "done".to_string())).len() as i64));
        let __t46 = document.create_text_node(&__interp45);
        __el43.append_child(&__t46).unwrap();
        let __t47 = document.create_text_node(")");
        __el43.append_child(&__t47).unwrap();
        __el42.append_child(&__el43).unwrap();
        let __el48 = document.create_element("ul").unwrap();
        let __for49 = cards_in((*self.cards.borrow()).clone(), "done".to_string());
        for c in __for49.into_iter() {
        let __el50 = document.create_element("li").unwrap();
        let __interp51 = format!("{}", c.title.clone());
        let __t52 = document.create_text_node(&__interp51);
        __el50.append_child(&__t52).unwrap();
        let __interp53 = format!("{}", c.id.clone());
        let __t54 = document.create_text_node(&__interp53);
        __el50.append_child(&__t54).unwrap();
        __el48.append_child(&__el50).unwrap();
        }
        __el42.append_child(&__el48).unwrap();
        __el15.append_child(&__el42).unwrap();
        __el0.append_child(&__el15).unwrap();
        root.append_child(&__el0).unwrap();
    }
}

fn __inject_style_Board_board_c_bc13d758() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .board-board-c-bc13d758 { font-family: system-ui, sans-serif; max-width: 720px; }\n    .hint-board-c-bc13d758 { color: #666; font-size: 0.9em; }\n    .controls-board-c-bc13d758 { display: flex; gap: 8px; flex-wrap: wrap; margin-bottom: 16px; }\n    .controls-board-c-bc13d758 button { padding: 8px 14px; cursor: pointer; border: 1px solid #999; border-radius: 6px; background: white; }\n    .cols-board-c-bc13d758 { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; }\n    .col-board-c-bc13d758 { background: #f4f4f4; border-radius: 8px; padding: 12px; min-height: 120px; }\n    .col-board-c-bc13d758 h2 { margin: 0 0 8px 0; font-size: 0.95em; text-transform: uppercase; letter-spacing: 0.04em; color: #333; }\n    .col-board-c-bc13d758 ul { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 6px; }\n    .col-board-c-bc13d758 li { background: white; border-radius: 6px; padding: 8px 10px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); font-variant-numeric: tabular-nums; }\n  "));
    let _ = head.append_child(&style_el);
}



// Composed entry point — NOT part of emit_module output.
// `fitz build --target wasm-client` (Phase 11.5.c) appends this
// wrapper so the bundle mounts the root component when the
// browser calls the `start` export.
#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    console_error_panic_hook::set_once();
    let root = Board::new();
    root.mount("#app")?;
    Ok(())
}
