// AUTO-GENERATED by `fitz build --target wasm-client`.
// Do NOT edit by hand — regenerate from the source `.fitzv`.
//
// Source: App.fitzv
//
// Composed by `src/view/wasm_build.rs::compose_lib_rs` (Phase 11.5.c).
// The tail below is the `#[wasm_bindgen(start)]` wrapper the CLI
// appends to the emitter output; the emitter itself does NOT emit
// the entry point so future targets (SSR, hybrid) can compose
// their own.

// Generated by fitz view WASM emitter (Fase 11.4.b).
// Do NOT edit — regenerate from the source `.fitzv`.

// Phase 11.5.e (§9.o Debt residual) — crate-level allows for
// the two cosmetic warnings that are structural to the
// emitter output, not correctness bugs:
//   - `non_snake_case`: component names are PascalCase by
//     convention (11.5.d), and the synthesised style helper
//     `__inject_style_<Component>_<scope>` reflects that.
//   - `unused_parens`: BinOp lowering wraps sub-expressions
//     in `(...)` to preserve precedence when nested. When
//     the BinOp is the entire RHS of an assignment the outer
//     parens are redundant but harmless.
#![allow(non_snake_case, unused_parens)]

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::atomic::{AtomicBool, Ordering};
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement};

// Phase 11.12 — hydration cursor helpers. Advance a sibling cursor to
// the next element / text node so the adopt walk maps template nodes
// onto the server-painted DOM in DFS order without re-creating them.
fn __flv_next_element(__cursor: &mut Option<web_sys::Node>) -> Option<web_sys::Element> {
    while let Some(__n) = __cursor.clone() {
        *__cursor = __n.next_sibling();
        if let Some(__el) = __n.dyn_ref::<web_sys::Element>() {
            return Some(__el.clone());
        }
    }
    None
}
fn __flv_next_text(__cursor: &mut Option<web_sys::Node>) -> Option<web_sys::Text> {
    while let Some(__n) = __cursor.clone() {
        *__cursor = __n.next_sibling();
        if let Some(__t) = __n.dyn_ref::<web_sys::Text>() {
            return Some(__t.clone());
        }
    }
    None
}
// Phase 11.12 slice 2 — advance the cursor to the next comment node
// whose text matches `__data`, skipping everything else (elements,
// text, and comments with other tags). Used to adopt a `{#if}`/`{#for}`
// region's server-painted anchors (`<!--fr-->` / `<!--/fr-->`) while
// stepping over the region content and any interpolation markers it
// contains. `text_content()` reads the comment data without needing the
// `web_sys::Comment` feature.
fn __flv_next_comment(__cursor: &mut Option<web_sys::Node>, __data: &str) -> Option<web_sys::Node> {
    while let Some(__n) = __cursor.clone() {
        *__cursor = __n.next_sibling();
        if __n.node_type() == web_sys::Node::COMMENT_NODE
            && __n.text_content().as_deref() == Some(__data) {
            return Some(__n);
        }
    }
    None
}

pub struct App {
    name: RefCell<String>,
    items: RefCell<Vec<String>>,
    __ktext_0: RefCell<Option<web_sys::Text>>,
    __kattr_1: RefCell<Option<web_sys::Element>>,
    __astart_0: RefCell<Option<web_sys::Node>>,
    __aend_0: RefCell<Option<web_sys::Node>>,
    __astart_1: RefCell<Option<web_sys::Node>>,
    __aend_1: RefCell<Option<web_sys::Node>>,
    __built: RefCell<bool>,
    root: RefCell<Option<HtmlElement>>,
}

impl App {
    pub fn new() -> Rc<Self> {
        Rc::new(App {
            name: RefCell::new("world".to_string()),
            items: RefCell::new(vec!["alpha".to_string(), "beta".to_string(), "gamma".to_string()]),
            __ktext_0: RefCell::new(None),
            __kattr_1: RefCell::new(None),
            __astart_0: RefCell::new(None),
            __aend_0: RefCell::new(None),
            __astart_1: RefCell::new(None),
            __aend_1: RefCell::new(None),
            __built: RefCell::new(false),
            root: RefCell::new(None),
        })
    }

    fn on_name(self: &Rc<Self>, payload: &std::collections::HashMap<String, String>) {
        let __rhs = payload.get(&("value".to_string())).cloned().unwrap_or_default();
        *self.name.borrow_mut() = __rhs;
        self.render();
    }

    fn reset(self: &Rc<Self>) {
        let __rhs = "world".to_string();
        *self.name.borrow_mut() = __rhs;
        self.render();
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        *self.__built.borrow_mut() = false;
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        if *self.__built.borrow() {
            self.__patch();
        } else {
            self.__build();
            *self.__built.borrow_mut() = true;
        }
    }

    fn __build(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("div").unwrap();
        __el0.set_attribute("class", "demo").unwrap();
        let __el1 = document.create_element("h1").unwrap();
        let __t2 = document.create_text_node("SSR → hydration: regions + mixed text");
        __el1.append_child(&__t2).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el3 = document.create_element("p").unwrap();
        __el3.set_attribute("class", "greeting").unwrap();
        let __t4 = document.create_text_node("Hello, ");
        __el3.append_child(&__t4).unwrap();
        let __interp5 = format!("{}", (*self.name.borrow()));
        let __t6 = document.create_text_node(&__interp5);
        __el3.append_child(&__t6).unwrap();
        *self.__ktext_0.borrow_mut() = Some(__t6.clone());
        let __t7 = document.create_text_node("!");
        __el3.append_child(&__t7).unwrap();
        __el0.append_child(&__el3).unwrap();
        let __el8 = document.create_element("label").unwrap();
        __el8.set_attribute("class", "row").unwrap();
        let __el9 = document.create_element("span").unwrap();
        let __t10 = document.create_text_node("Type a name to hide the matching item");
        __el9.append_child(&__t10).unwrap();
        __el8.append_child(&__el9).unwrap();
        let __el11 = document.create_element("input").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |__evt: Event| {
                let mut __payload = std::collections::HashMap::<String, String>::new();
                if let Some(__t) = __evt.target() {
                    if let Some(__el) = __t.dyn_ref::<web_sys::HtmlInputElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlSelectElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlTextAreaElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    }
                }
                App::on_name(&__self_clone, &__payload);
            }) as Box<dyn FnMut(Event)>);
            __el11.add_event_listener_with_callback("input", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        __el11.set_attribute("value", &format!("{}", (*self.name.borrow()))).unwrap();
        *self.__kattr_1.borrow_mut() = Some(__el11.clone());
        __el11.set_attribute("placeholder", "type here").unwrap();
        __el11.set_attribute("autocomplete", "off").unwrap();
        __el8.append_child(&__el11).unwrap();
        __el0.append_child(&__el8).unwrap();
        let __rs12: web_sys::Node = document.create_comment("").into();
        __el0.append_child(&__rs12).unwrap();
        *self.__astart_0.borrow_mut() = Some(__rs12.clone());
        let __re13: web_sys::Node = document.create_comment("").into();
        __el0.append_child(&__re13).unwrap();
        *self.__aend_0.borrow_mut() = Some(__re13.clone());
        self.__mount_region_0();
        let __el14 = document.create_element("ul").unwrap();
        __el14.set_attribute("class", "items").unwrap();
        let __rs15: web_sys::Node = document.create_comment("").into();
        __el14.append_child(&__rs15).unwrap();
        *self.__astart_1.borrow_mut() = Some(__rs15.clone());
        let __re16: web_sys::Node = document.create_comment("").into();
        __el14.append_child(&__re16).unwrap();
        *self.__aend_1.borrow_mut() = Some(__re16.clone());
        self.__mount_region_1();
        __el0.append_child(&__el14).unwrap();
        let __el17 = document.create_element("button").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                App::reset(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __el17.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t18 = document.create_text_node("reset");
        __el17.append_child(&__t18).unwrap();
        __el0.append_child(&__el17).unwrap();
        root.append_child(&__el0).unwrap();
    }

    fn __patch(self: &Rc<Self>) {
        if let Some(__n) = self.__ktext_0.borrow().as_ref() { __n.set_data(&format!("{}", (*self.name.borrow()))); }
        if let Some(__el) = self.__kattr_1.borrow().as_ref() { let _ = __el.set_attribute("value", &format!("{}", (*self.name.borrow()))); }
        self.__patch_region_0();
        self.__patch_region_1();
    }

    fn __apply_state_json(self: &Rc<Self>, __json: &str) {
        let __v: serde_json::Value = match serde_json::from_str(__json) { Ok(__j) => __j, Err(_) => return, };
        let _ = (&__v, self);
        if let Some(__x) = __v.get("name").and_then(|__j| __j.as_str()) { *self.name.borrow_mut() = __x.to_string(); }
    }

    pub fn hydrate(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        if let Some(__sel) = web_sys::window().unwrap().document().unwrap().get_element_by_id("__flv_state_App") {
            if let Some(__txt) = __sel.text_content() { self.__apply_state_json(&__txt); }
        }
        let mut __cur_root = root.first_child();
        *self.root.borrow_mut() = Some(root);
        if let Some(__hel0) = __flv_next_element(&mut __cur_root) {
        let mut __hcur1 = __hel0.first_child();
        if let Some(__hel2) = __flv_next_element(&mut __hcur1) {
        let mut __hcur3 = __hel2.first_child();
        let _ = __flv_next_text(&mut __hcur3);
        }
        if let Some(__hel4) = __flv_next_element(&mut __hcur1) {
        let mut __hcur5 = __hel4.first_child();
        let _ = __flv_next_text(&mut __hcur5);
        if let Some(__hn) = __flv_next_text(&mut __hcur5) { *self.__ktext_0.borrow_mut() = Some(__hn); }
        let _ = __flv_next_text(&mut __hcur5);
        }
        if let Some(__hel6) = __flv_next_element(&mut __hcur1) {
        let mut __hcur7 = __hel6.first_child();
        if let Some(__hel8) = __flv_next_element(&mut __hcur7) {
        let mut __hcur9 = __hel8.first_child();
        let _ = __flv_next_text(&mut __hcur9);
        }
        if let Some(__hel10) = __flv_next_element(&mut __hcur7) {
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |__evt: Event| {
                let mut __payload = std::collections::HashMap::<String, String>::new();
                if let Some(__t) = __evt.target() {
                    if let Some(__el) = __t.dyn_ref::<web_sys::HtmlInputElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlSelectElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlTextAreaElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    }
                }
                App::on_name(&__self_clone, &__payload);
            }) as Box<dyn FnMut(Event)>);
            __hel10.add_event_listener_with_callback("input", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        *self.__kattr_1.borrow_mut() = Some(__hel10.clone());
        }
        }
        if let Some(__rs) = __flv_next_comment(&mut __hcur1, "fr") { *self.__astart_0.borrow_mut() = Some(__rs); }
        if let Some(__re) = __flv_next_comment(&mut __hcur1, "/fr") { *self.__aend_0.borrow_mut() = Some(__re); }
        if let Some(__hel12) = __flv_next_element(&mut __hcur1) {
        let mut __hcur13 = __hel12.first_child();
        if let Some(__rs) = __flv_next_comment(&mut __hcur13, "fr") { *self.__astart_1.borrow_mut() = Some(__rs); }
        if let Some(__re) = __flv_next_comment(&mut __hcur13, "/fr") { *self.__aend_1.borrow_mut() = Some(__re); }
        }
        if let Some(__hel14) = __flv_next_element(&mut __hcur1) {
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                App::reset(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __hel14.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let mut __hcur15 = __hel14.first_child();
        let _ = __flv_next_text(&mut __hcur15);
        }
        }
        *self.__built.borrow_mut() = true;
        Ok(())
    }


    fn __mount_region_0(self: &Rc<Self>) {
        let document = web_sys::window().unwrap().document().unwrap();
        let __frag = document.create_document_fragment();
        if ((*self.name.borrow()) != "".to_string()) {
        let __el0 = document.create_element("p").unwrap();
        __el0.set_attribute("class", "hint").unwrap();
        let __t1 = document.create_text_node("Hiding items equal to: ");
        __el0.append_child(&__t1).unwrap();
        let __interp2 = format!("{}", (*self.name.borrow()));
        let __t3 = document.create_text_node(&__interp2);
        __el0.append_child(&__t3).unwrap();
        __frag.append_child(&__el0).unwrap();
        }
        if let Some(__e) = self.__aend_0.borrow().as_ref() {
            if let Some(__p) = __e.parent_node() {
                let _ = __p.insert_before(&__frag, Some(__e));
            }
        }
    }

    fn __patch_region_0(self: &Rc<Self>) {
        if let (Some(__s), Some(__e)) = (self.__astart_0.borrow().clone(), self.__aend_0.borrow().clone()) {
            while let Some(__n) = __s.next_sibling() {
                if __n.is_same_node(Some(&__e)) { break; }
                if let Some(__p) = __n.parent_node() { let _ = __p.remove_child(&__n); }
            }
        }
        self.__mount_region_0();
    }


    fn __mount_region_1(self: &Rc<Self>) {
        let document = web_sys::window().unwrap().document().unwrap();
        let __frag = document.create_document_fragment();
        let __for0 = (*self.items.borrow()).clone();
        for it in __for0.iter().cloned() {
        if (it != (*self.name.borrow())) {
        let __el1 = document.create_element("li").unwrap();
        let __interp2 = format!("{}", it);
        let __t3 = document.create_text_node(&__interp2);
        __el1.append_child(&__t3).unwrap();
        __frag.append_child(&__el1).unwrap();
        }
        }
        if let Some(__e) = self.__aend_1.borrow().as_ref() {
            if let Some(__p) = __e.parent_node() {
                let _ = __p.insert_before(&__frag, Some(__e));
            }
        }
    }

    fn __patch_region_1(self: &Rc<Self>) {
        if let (Some(__s), Some(__e)) = (self.__astart_1.borrow().clone(), self.__aend_1.borrow().clone()) {
            while let Some(__n) = __s.next_sibling() {
                if __n.is_same_node(Some(&__e)) { break; }
                if let Some(__p) = __n.parent_node() { let _ = __p.remove_child(&__n); }
            }
        }
        self.__mount_region_1();
    }

}



// Composed entry point — NOT part of emit_module output.
// `fitz build --target wasm-client` appends this wrapper. Phase
// 11.12: hydrate the server-painted DOM when the mount root
// already has content, else fresh-mount into an empty root.
#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    console_error_panic_hook::set_once();
    let root = App::new();
    let __document = web_sys::window().unwrap().document().unwrap();
    if let Some(__mount) = __document.query_selector("#app")? {
        if __mount.first_element_child().is_some() {
            let __el = __mount.dyn_into::<web_sys::HtmlElement>()?;
            return root.hydrate(__el);
        }
    }
    root.mount("#app")?;
    Ok(())
}
