// AUTO-GENERATED by `fitz build --target wasm-client`.
// Do NOT edit by hand — regenerate from the source `.fitzv`.
//
// Source: Dashboard.fitzv
//
// Composed by `src/view/wasm_build.rs::compose_lib_rs` (Phase 11.5.c).
// The tail below is the `#[wasm_bindgen(start)]` wrapper the CLI
// appends to the emitter output; the emitter itself does NOT emit
// the entry point so future targets (SSR, hybrid) can compose
// their own.

// Generated by fitz view WASM emitter (Fase 11.4.b).
// Do NOT edit — regenerate from the source `.fitzv`.

// Phase 11.5.e (§9.o Debt residual) — crate-level allows for
// the two cosmetic warnings that are structural to the
// emitter output, not correctness bugs:
//   - `non_snake_case`: component names are PascalCase by
//     convention (11.5.d), and the synthesised style helper
//     `__inject_style_<Component>_<scope>` reflects that.
//   - `unused_parens`: BinOp lowering wraps sub-expressions
//     in `(...)` to preserve precedence when nested. When
//     the BinOp is the entire RHS of an assignment the outer
//     parens are redundant but harmless.
#![allow(non_snake_case, unused_parens)]

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::atomic::{AtomicBool, Ordering};
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement};

pub struct Board {
    root: RefCell<Option<HtmlElement>>,
}

impl Board {
    pub fn new() -> Rc<Self> {
        Rc::new(Board {
            root: RefCell::new(None),
        })
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_Board_board_c_44d94692();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("div").unwrap();
        __el0.set_attribute("class", "board board-board-c-44d94692").unwrap();
        let __el1 = document.create_element("h2").unwrap();
        let __t2 = document.create_text_node("Metrics");
        __el1.append_child(&__t2).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el3 = document.create_element("div").unwrap();
        __el3.set_attribute("class", "grid grid-board-c-44d94692").unwrap();
        let __el4 = document.create_element("div").unwrap();
        __el4.set_attribute("class", "__fitz-child-MetricCard").unwrap();
        __el3.append_child(&__el4).unwrap();
        let __child5 = MetricCard::new();
        *__child5.title.borrow_mut() = "Requests".to_string();
        *__child5.value.borrow_mut() = 1240i64;
        *__child5.trend.borrow_mut() = "up".to_string();
        let __el4_html = __el4.clone().dyn_into::<HtmlElement>().unwrap();
        __child5.mount_into(__el4_html).unwrap();
        let __el6 = document.create_element("div").unwrap();
        __el6.set_attribute("class", "__fitz-child-MetricCard").unwrap();
        __el3.append_child(&__el6).unwrap();
        let __child7 = MetricCard::new();
        *__child7.title.borrow_mut() = "Errors".to_string();
        *__child7.value.borrow_mut() = 7i64;
        *__child7.trend.borrow_mut() = "down".to_string();
        let __el6_html = __el6.clone().dyn_into::<HtmlElement>().unwrap();
        __child7.mount_into(__el6_html).unwrap();
        let __el8 = document.create_element("div").unwrap();
        __el8.set_attribute("class", "__fitz-child-MetricCard").unwrap();
        __el3.append_child(&__el8).unwrap();
        let __child9 = MetricCard::new();
        *__child9.title.borrow_mut() = "Latency".to_string();
        *__child9.value.borrow_mut() = 42i64;
        *__child9.trend.borrow_mut() = "flat".to_string();
        let __el8_html = __el8.clone().dyn_into::<HtmlElement>().unwrap();
        __child9.mount_into(__el8_html).unwrap();
        __el0.append_child(&__el3).unwrap();
        root.append_child(&__el0).unwrap();
    }
}

fn __inject_style_Board_board_c_44d94692() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .board-board-c-44d94692 { font-family: sans-serif; padding: 24px; }\n    h2 { margin: 0 0 16px; font-size: 1.1em; color: #333; }\n    .grid-board-c-44d94692 { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; }\n  "));
    let _ = head.append_child(&style_el);
}

pub struct MetricCard {
    title: RefCell<String>,
    value: RefCell<i64>,
    trend: RefCell<String>,
    clicks: RefCell<i64>,
    root: RefCell<Option<HtmlElement>>,
}

impl MetricCard {
    pub fn new() -> Rc<Self> {
        Rc::new(MetricCard {
            title: RefCell::new("Untitled".to_string()),
            value: RefCell::new(0i64),
            trend: RefCell::new("flat".to_string()),
            clicks: RefCell::new(0i64),
            root: RefCell::new(None),
        })
    }

    fn tap(self: &Rc<Self>) {
        let __rhs = ((*self.clicks.borrow()) + 1i64);
        *self.clicks.borrow_mut() = __rhs;
        self.render();
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_MetricCard_metric_card_c_dacff6a1();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("div").unwrap();
        __el0.set_attribute("class", "card card-metric-card-c-dacff6a1").unwrap();
        let __el1 = document.create_element("div").unwrap();
        __el1.set_attribute("class", "title title-metric-card-c-dacff6a1").unwrap();
        let __interp2 = format!("{}", (*self.title.borrow()));
        let __t3 = document.create_text_node(&__interp2);
        __el1.append_child(&__t3).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el4 = document.create_element("div").unwrap();
        __el4.set_attribute("class", "value value-metric-card-c-dacff6a1").unwrap();
        let __interp5 = format!("{}", (*self.value.borrow()));
        let __t6 = document.create_text_node(&__interp5);
        __el4.append_child(&__t6).unwrap();
        __el0.append_child(&__el4).unwrap();
        let __el7 = document.create_element("div").unwrap();
        __el7.set_attribute("class", "trend trend-metric-card-c-dacff6a1").unwrap();
        let __t8 = document.create_text_node("trend: ");
        __el7.append_child(&__t8).unwrap();
        let __interp9 = format!("{}", (*self.trend.borrow()));
        let __t10 = document.create_text_node(&__interp9);
        __el7.append_child(&__t10).unwrap();
        __el0.append_child(&__el7).unwrap();
        let __el11 = document.create_element("button").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                MetricCard::tap(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __el11.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t12 = document.create_text_node("tapped ");
        __el11.append_child(&__t12).unwrap();
        let __interp13 = format!("{}", (*self.clicks.borrow()));
        let __t14 = document.create_text_node(&__interp13);
        __el11.append_child(&__t14).unwrap();
        let __t15 = document.create_text_node(" times");
        __el11.append_child(&__t15).unwrap();
        __el0.append_child(&__el11).unwrap();
        root.append_child(&__el0).unwrap();
    }
}

fn __inject_style_MetricCard_metric_card_c_dacff6a1() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .card-metric-card-c-dacff6a1 { border: 1px solid #ddd; border-radius: 8px; padding: 16px; background: #fafafa; }\n    .title-metric-card-c-dacff6a1 { font-size: 0.85em; text-transform: uppercase; color: #666; }\n    .value-metric-card-c-dacff6a1 { font-size: 2em; font-weight: bold; margin: 8px 0; }\n    .trend-metric-card-c-dacff6a1 { font-size: 0.85em; color: #888; margin-bottom: 12px; }\n    button { padding: 6px 12px; border: 1px solid #999; border-radius: 4px; background: white; cursor: pointer; }\n  "));
    let _ = head.append_child(&style_el);
}



// Composed entry point — NOT part of emit_module output.
// `fitz build --target wasm-client` (Phase 11.5.c) appends this
// wrapper so the bundle mounts the root component when the
// browser calls the `start` export.
#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    console_error_panic_hook::set_once();
    let root = Board::new();
    root.mount("#app")?;
    Ok(())
}
