// AUTO-GENERATED by `fitz build --target wasm-client`.
// Do NOT edit by hand — regenerate from the source `.fitzv`.
//
// Source: App.fitzv
//
// Composed by `src/view/wasm_build.rs::compose_lib_rs` (Phase 11.5.c).
// The tail below is the `#[wasm_bindgen(start)]` wrapper the CLI
// appends to the emitter output; the emitter itself does NOT emit
// the entry point so future targets (SSR, hybrid) can compose
// their own.

// Generated by fitz view WASM emitter (Fase 11.4.b).
// Do NOT edit — regenerate from the source `.fitzv`.

// Phase 11.5.e (§9.o Debt residual) — crate-level allows for
// the two cosmetic warnings that are structural to the
// emitter output, not correctness bugs:
//   - `non_snake_case`: component names are PascalCase by
//     convention (11.5.d), and the synthesised style helper
//     `__inject_style_<Component>_<scope>` reflects that.
//   - `unused_parens`: BinOp lowering wraps sub-expressions
//     in `(...)` to preserve precedence when nested. When
//     the BinOp is the entire RHS of an assignment the outer
//     parens are redundant but harmless.
#![allow(non_snake_case, unused_parens)]

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::atomic::{AtomicBool, Ordering};
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement};

pub struct App {
    nums: RefCell<Vec<i64>>,
    next: RefCell<i64>,
    root: RefCell<Option<HtmlElement>>,
}

impl App {
    pub fn new() -> Rc<Self> {
        Rc::new(App {
            nums: RefCell::new(vec![1i64, 2i64, 3i64, 4i64, 5i64]),
            next: RefCell::new(6i64),
            root: RefCell::new(None),
        })
    }

    fn double_all(self: &Rc<Self>) {
        let __rhs = ((*self.nums.borrow())).clone().into_iter().map(|n| (n * 2i64)).collect::<Vec<_>>();
        *self.nums.borrow_mut() = __rhs;
        self.render();
    }

    fn keep_big(self: &Rc<Self>) {
        let __rhs = ((*self.nums.borrow())).clone().into_iter().filter(|__it| { let n = __it.clone(); (n > 5i64) }).collect::<Vec<_>>();
        *self.nums.borrow_mut() = __rhs;
        self.render();
    }

    fn add_next(self: &Rc<Self>) {
        self.nums.borrow_mut().push((*self.next.borrow()));
        let __rhs = ((*self.next.borrow()) + 1i64);
        *self.next.borrow_mut() = __rhs;
        self.render();
    }

    fn reset(self: &Rc<Self>) {
        let __rhs = vec![1i64, 2i64, 3i64, 4i64, 5i64];
        *self.nums.borrow_mut() = __rhs;
        let __rhs = 6i64;
        *self.next.borrow_mut() = __rhs;
        self.render();
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_App_app_c_1c19e0d8();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("div").unwrap();
        __el0.set_attribute("class", "playground playground-app-c-1c19e0d8").unwrap();
        let __el1 = document.create_element("h1").unwrap();
        let __t2 = document.create_text_node("List transform on WASM");
        __el1.append_child(&__t2).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el3 = document.create_element("p").unwrap();
        __el3.set_attribute("class", "hint hint-app-c-1c19e0d8").unwrap();
        let __t4 = document.create_text_node("Map, filter and reassign a list of Ints entirely client-side — no server round-trip. The \"big ones\" list is recomputed in the template with a filter inside the loop.");
        __el3.append_child(&__t4).unwrap();
        __el0.append_child(&__el3).unwrap();
        let __el5 = document.create_element("div").unwrap();
        __el5.set_attribute("class", "controls controls-app-c-1c19e0d8").unwrap();
        let __el6 = document.create_element("button").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                App::double_all(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __el6.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t7 = document.create_text_node("double all");
        __el6.append_child(&__t7).unwrap();
        __el5.append_child(&__el6).unwrap();
        let __el8 = document.create_element("button").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                App::keep_big(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __el8.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t9 = document.create_text_node("keep over 5");
        __el8.append_child(&__t9).unwrap();
        __el5.append_child(&__el8).unwrap();
        let __el10 = document.create_element("button").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                App::add_next(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __el10.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t11 = document.create_text_node("add ");
        __el10.append_child(&__t11).unwrap();
        let __interp12 = format!("{}", (*self.next.borrow()));
        let __t13 = document.create_text_node(&__interp12);
        __el10.append_child(&__t13).unwrap();
        __el5.append_child(&__el10).unwrap();
        let __el14 = document.create_element("button").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                App::reset(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __el14.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t15 = document.create_text_node("reset");
        __el14.append_child(&__t15).unwrap();
        __el5.append_child(&__el14).unwrap();
        __el0.append_child(&__el5).unwrap();
        let __el16 = document.create_element("p").unwrap();
        __el16.set_attribute("class", "count count-app-c-1c19e0d8").unwrap();
        let __t17 = document.create_text_node("count: ");
        __el16.append_child(&__t17).unwrap();
        let __interp18 = format!("{}", (((*self.nums.borrow())).len() as i64));
        let __t19 = document.create_text_node(&__interp18);
        __el16.append_child(&__t19).unwrap();
        __el0.append_child(&__el16).unwrap();
        let __el20 = document.create_element("ul").unwrap();
        __el20.set_attribute("class", "nums nums-app-c-1c19e0d8").unwrap();
        let __for21 = (*self.nums.borrow()).clone();
        for n in __for21.iter().cloned() {
        let __el22 = document.create_element("li").unwrap();
        let __interp23 = format!("{}", n);
        let __t24 = document.create_text_node(&__interp23);
        __el22.append_child(&__t24).unwrap();
        __el20.append_child(&__el22).unwrap();
        }
        __el0.append_child(&__el20).unwrap();
        let __el25 = document.create_element("h2").unwrap();
        let __t26 = document.create_text_node("big ones (over 4)");
        __el25.append_child(&__t26).unwrap();
        __el0.append_child(&__el25).unwrap();
        let __el27 = document.create_element("ul").unwrap();
        __el27.set_attribute("class", "big big-app-c-1c19e0d8").unwrap();
        let __for28 = ((*self.nums.borrow())).clone().into_iter().filter(|__it| { let n = __it.clone(); (n > 4i64) }).collect::<Vec<_>>();
        for m in __for28.into_iter() {
        let __el29 = document.create_element("li").unwrap();
        let __interp30 = format!("{}", m);
        let __t31 = document.create_text_node(&__interp30);
        __el29.append_child(&__t31).unwrap();
        __el27.append_child(&__el29).unwrap();
        }
        __el0.append_child(&__el27).unwrap();
        root.append_child(&__el0).unwrap();
    }
}

fn __inject_style_App_app_c_1c19e0d8() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .playground-app-c-1c19e0d8 { font-family: system-ui, sans-serif; max-width: 480px; }\n    .hint-app-c-1c19e0d8 { color: #666; font-size: 0.9em; }\n    .controls-app-c-1c19e0d8 { display: flex; gap: 8px; flex-wrap: wrap; margin-bottom: 16px; }\n    .controls-app-c-1c19e0d8 button { padding: 8px 14px; cursor: pointer; border: 1px solid #999; border-radius: 6px; background: white; }\n    .count-app-c-1c19e0d8 { font-variant-numeric: tabular-nums; }\n    ul { list-style: none; padding: 0; display: flex; gap: 8px; flex-wrap: wrap; }\n    li { padding: 6px 12px; border: 1px solid #ddd; border-radius: 6px; background: #fafafa; font-variant-numeric: tabular-nums; }\n  "));
    let _ = head.append_child(&style_el);
}



// Composed entry point — NOT part of emit_module output.
// `fitz build --target wasm-client` (Phase 11.5.c) appends this
// wrapper so the bundle mounts the root component when the
// browser calls the `start` export.
#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    console_error_panic_hook::set_once();
    let root = App::new();
    root.mount("#app")?;
    Ok(())
}
