// AUTO-GENERATED by `fitz build --target wasm-client`.
// Do NOT edit by hand — regenerate from the source `.fitzv`.
//
// Source: App.fitzv
//
// Composed by `src/view/wasm_build.rs::compose_lib_rs` (Phase 11.5.c).
// The tail below is the `#[wasm_bindgen(start)]` wrapper the CLI
// appends to the emitter output; the emitter itself does NOT emit
// the entry point so future targets (SSR, hybrid) can compose
// their own.

// Generated by fitz view WASM emitter (Fase 11.4.b).
// Do NOT edit — regenerate from the source `.fitzv`.

// Phase 11.5.e (§9.o Debt residual) — crate-level allows for
// the two cosmetic warnings that are structural to the
// emitter output, not correctness bugs:
//   - `non_snake_case`: component names are PascalCase by
//     convention (11.5.d), and the synthesised style helper
//     `__inject_style_<Component>_<scope>` reflects that.
//   - `unused_parens`: BinOp lowering wraps sub-expressions
//     in `(...)` to preserve precedence when nested. When
//     the BinOp is the entire RHS of an assignment the outer
//     parens are redundant but harmless.
#![allow(non_snake_case, unused_parens)]

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::atomic::{AtomicBool, Ordering};
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement};

pub struct App {
    count: RefCell<i64>,
    labels: RefCell<Vec<String>>,
    root: RefCell<Option<HtmlElement>>,
}

impl App {
    pub fn new() -> Rc<Self> {
        Rc::new(App {
            count: RefCell::new(0i64),
            labels: RefCell::new(vec!["design".to_string(), "build".to_string(), "ship".to_string()]),
            root: RefCell::new(None),
        })
    }

    fn bump(self: &Rc<Self>) {
        let __rhs = ((*self.count.borrow()) + 1i64);
        *self.count.borrow_mut() = __rhs;
        self.render();
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_App_app_c_42df218b();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("div").unwrap();
        __el0.set_attribute("class", "demo demo-app-c-42df218b").unwrap();
        let __el1 = document.create_element("h1").unwrap();
        let __t2 = document.create_text_node("Control flow on WASM");
        __el1.append_child(&__t2).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el3 = document.create_element("button").unwrap();
        __el3.set_attribute("class", "bump bump-app-c-42df218b").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                App::bump(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __el3.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t4 = document.create_text_node("clicked ");
        __el3.append_child(&__t4).unwrap();
        let __interp5 = format!("{}", (*self.count.borrow()));
        let __t6 = document.create_text_node(&__interp5);
        __el3.append_child(&__t6).unwrap();
        let __t7 = document.create_text_node(" times");
        __el3.append_child(&__t7).unwrap();
        __el0.append_child(&__el3).unwrap();
        if ((*self.count.borrow()) > 2i64) {
        let __el8 = document.create_element("p").unwrap();
        __el8.set_attribute("class", "active active-app-c-42df218b").unwrap();
        let __t9 = document.create_text_node("On a roll — clicked more than twice!");
        __el8.append_child(&__t9).unwrap();
        __el0.append_child(&__el8).unwrap();
        } else {
        if ((*self.count.borrow()) > 0i64) {
        let __el10 = document.create_element("p").unwrap();
        __el10.set_attribute("class", "active active-app-c-42df218b").unwrap();
        let __t11 = document.create_text_node("You have clicked at least once.");
        __el10.append_child(&__t11).unwrap();
        __el0.append_child(&__el10).unwrap();
        } else {
        let __el12 = document.create_element("p").unwrap();
        __el12.set_attribute("class", "idle idle-app-c-42df218b").unwrap();
        let __t13 = document.create_text_node("Click the button to begin.");
        __el12.append_child(&__t13).unwrap();
        __el0.append_child(&__el12).unwrap();
        }
        }
        let __el14 = document.create_element("h2").unwrap();
        let __t15 = document.create_text_node("Steps");
        __el14.append_child(&__t15).unwrap();
        __el0.append_child(&__el14).unwrap();
        let __el16 = document.create_element("ul").unwrap();
        __el16.set_attribute("class", "labels labels-app-c-42df218b").unwrap();
        let __for17 = (*self.labels.borrow()).clone();
        for label in __for17.iter().cloned() {
        let __el18 = document.create_element("li").unwrap();
        let __interp19 = format!("{}", label);
        let __t20 = document.create_text_node(&__interp19);
        __el18.append_child(&__t20).unwrap();
        __el16.append_child(&__el18).unwrap();
        }
        __el0.append_child(&__el16).unwrap();
        root.append_child(&__el0).unwrap();
    }
}

fn __inject_style_App_app_c_42df218b() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .demo-app-c-42df218b { font-family: system-ui, sans-serif; }\n    .bump-app-c-42df218b { padding: 8px 16px; cursor: pointer; border: 1px solid #999; border-radius: 6px; background: white; }\n    .active-app-c-42df218b { color: #178a4c; font-weight: bold; }\n    .idle-app-c-42df218b { color: #888; }\n    .labels-app-c-42df218b { padding-left: 20px; }\n    .labels-app-c-42df218b li { margin: 4px 0; }\n  "));
    let _ = head.append_child(&style_el);
}



// Composed entry point — NOT part of emit_module output.
// `fitz build --target wasm-client` (Phase 11.5.c) appends this
// wrapper so the bundle mounts the root component when the
// browser calls the `start` export.
#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    console_error_panic_hook::set_once();
    let root = App::new();
    root.mount("#app")?;
    Ok(())
}
