// AUTO-GENERATED by `fitz build --target wasm-client`.
// Do NOT edit by hand — regenerate from the source `.fitzv`.
//
// Source: App.fitzv
//
// Composed by `src/view/wasm_build.rs::compose_lib_rs` (Phase 11.5.c).
// The tail below is the `#[wasm_bindgen(start)]` wrapper the CLI
// appends to the emitter output; the emitter itself does NOT emit
// the entry point so future targets (SSR, hybrid) can compose
// their own.

// Generated by fitz view WASM emitter (Fase 11.4.b).
// Do NOT edit — regenerate from the source `.fitzv`.

// Phase 11.5.e (§9.o Debt residual) — crate-level allows for
// the two cosmetic warnings that are structural to the
// emitter output, not correctness bugs:
//   - `non_snake_case`: component names are PascalCase by
//     convention (11.5.d), and the synthesised style helper
//     `__inject_style_<Component>_<scope>` reflects that.
//   - `unused_parens`: BinOp lowering wraps sub-expressions
//     in `(...)` to preserve precedence when nested. When
//     the BinOp is the entire RHS of an assignment the outer
//     parens are redundant but harmless.
#![allow(non_snake_case, unused_parens)]

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::atomic::{AtomicBool, Ordering};
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement};

pub struct TodoForm {
    items: RefCell<Vec<String>>,
    root: RefCell<Option<HtmlElement>>,
}

impl TodoForm {
    pub fn new() -> Rc<Self> {
        Rc::new(TodoForm {
            items: RefCell::new(Vec::new()),
            root: RefCell::new(None),
        })
    }

    fn add(self: &Rc<Self>, payload: &std::collections::HashMap<String, String>) {
        if payload.contains_key(&("text".to_string())) {
            self.items.borrow_mut().push(payload.get(&("text".to_string())).cloned().unwrap_or_default());
        }
        self.render();
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_TodoForm_todo_form_c_c3f61302();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("div").unwrap();
        __el0.set_attribute("class", "todo todo-todo-form-c-c3f61302").unwrap();
        let __el1 = document.create_element("h1").unwrap();
        let __t2 = document.create_text_node("Form payload on WASM");
        __el1.append_child(&__t2).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el3 = document.create_element("p").unwrap();
        __el3.set_attribute("class", "hint hint-todo-form-c-c3f61302").unwrap();
        let __t4 = document.create_text_node("Type an item and press Add — the submit handler reads the form field from the payload, appends it, and the input clears.");
        __el3.append_child(&__t4).unwrap();
        __el0.append_child(&__el3).unwrap();
        let __el5 = document.create_element("form").unwrap();
        {
            let __self_clone = self.clone();
            let __form_el = __el5.clone();
            let __closure = Closure::wrap(Box::new(move |__evt: Event| {
                __evt.prevent_default();
                let mut __payload = std::collections::HashMap::<String, String>::new();
                if let Some(__f) = __form_el.query_selector("[name=\"text\"]").ok().flatten() {
                    if let Ok(__inp) = __f.dyn_into::<web_sys::HtmlInputElement>() {
                        __payload.insert("text".to_string(), __inp.value());
                    }
                }
                TodoForm::add(&__self_clone, &__payload);
                if let Some(__f) = __form_el.query_selector("[name=\"text\"]").ok().flatten() {
                    if let Ok(__inp) = __f.dyn_into::<web_sys::HtmlInputElement>() { __inp.set_value(""); }
                }
            }) as Box<dyn FnMut(Event)>);
            __el5.add_event_listener_with_callback("submit", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __el6 = document.create_element("input").unwrap();
        __el6.set_attribute("name", "text").unwrap();
        __el6.set_attribute("placeholder", "New item").unwrap();
        __el6.set_attribute("autocomplete", "off").unwrap();
        __el6.set_attribute("data-flv-clear", "").unwrap();
        __el5.append_child(&__el6).unwrap();
        let __el7 = document.create_element("button").unwrap();
        __el7.set_attribute("type", "submit").unwrap();
        let __t8 = document.create_text_node("Add");
        __el7.append_child(&__t8).unwrap();
        __el5.append_child(&__el7).unwrap();
        __el0.append_child(&__el5).unwrap();
        let __el9 = document.create_element("ul").unwrap();
        let __for10 = (*self.items.borrow()).clone();
        for it in __for10.iter().cloned() {
        let __el11 = document.create_element("li").unwrap();
        let __interp12 = format!("{}", it);
        let __t13 = document.create_text_node(&__interp12);
        __el11.append_child(&__t13).unwrap();
        __el9.append_child(&__el11).unwrap();
        }
        __el0.append_child(&__el9).unwrap();
        root.append_child(&__el0).unwrap();
    }
}

fn __inject_style_TodoForm_todo_form_c_c3f61302() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .todo-todo-form-c-c3f61302 { font-family: system-ui, sans-serif; max-width: 420px; }\n    .hint-todo-form-c-c3f61302 { color: #666; font-size: 0.9em; }\n    form { display: flex; gap: 8px; margin-bottom: 16px; }\n    input { flex: 1; padding: 8px 10px; border: 1px solid #ccc; border-radius: 6px; font-size: 1rem; }\n    button { padding: 8px 16px; cursor: pointer; border: none; border-radius: 6px; background: #CE412B; color: white; font-weight: 600; }\n    ul { list-style: none; padding: 0; display: flex; flex-direction: column; gap: 6px; }\n    li { padding: 8px 10px; border: 1px solid #ddd; border-radius: 6px; background: #fafafa; }\n  "));
    let _ = head.append_child(&style_el);
}



// Composed entry point — NOT part of emit_module output.
// `fitz build --target wasm-client` (Phase 11.5.c) appends this
// wrapper so the bundle mounts the root component when the
// browser calls the `start` export.
#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    console_error_panic_hook::set_once();
    let root = TodoForm::new();
    root.mount("#app")?;
    Ok(())
}
