// AUTO-GENERATED by `fitz build --target wasm-client`.
// Do NOT edit by hand — regenerate from the source `.fitzv`.
//
// Source: App.fitzv
//
// Composed by `src/view/wasm_build.rs::compose_lib_rs` (Phase 11.5.c).
// The tail below is the `#[wasm_bindgen(start)]` wrapper the CLI
// appends to the emitter output; the emitter itself does NOT emit
// the entry point so future targets (SSR, hybrid) can compose
// their own.

// Generated by fitz view WASM emitter (Fase 11.4.b).
// Do NOT edit — regenerate from the source `.fitzv`.

// Phase 11.5.e (§9.o Debt residual) — crate-level allows for
// the two cosmetic warnings that are structural to the
// emitter output, not correctness bugs:
//   - `non_snake_case`: component names are PascalCase by
//     convention (11.5.d), and the synthesised style helper
//     `__inject_style_<Component>_<scope>` reflects that.
//   - `unused_parens`: BinOp lowering wraps sub-expressions
//     in `(...)` to preserve precedence when nested. When
//     the BinOp is the entire RHS of an assignment the outer
//     parens are redundant but harmless.
#![allow(non_snake_case, unused_parens)]

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::atomic::{AtomicBool, Ordering};
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement};

pub struct Card {
    title: RefCell<String>,
    likes: RefCell<i64>,
    __on_like: RefCell<Option<Box<dyn Fn(&std::collections::HashMap<String, String>)>>>,
    __slot: RefCell<Option<Rc<dyn Fn(&web_sys::Node)>>>,
    __slot_badge: RefCell<Option<Rc<dyn Fn(&web_sys::Node)>>>,
    root: RefCell<Option<HtmlElement>>,
}

impl Card {
    pub fn new() -> Rc<Self> {
        Rc::new(Card {
            title: RefCell::new("Untitled".to_string()),
            likes: RefCell::new(0i64),
            __on_like: RefCell::new(None),
            __slot: RefCell::new(None),
            __slot_badge: RefCell::new(None),
            root: RefCell::new(None),
        })
    }

    fn like(self: &Rc<Self>, payload: &std::collections::HashMap<String, String>) {
        let __rhs = ((*self.likes.borrow()) + 1i64);
        *self.likes.borrow_mut() = __rhs;
        self.render();
        if let Some(__cb) = self.__on_like.borrow().as_ref() { __cb(payload); }
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_Card_card_c_0fb22f41();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("article").unwrap();
        __el0.set_attribute("class", "card card-card-c-0fb22f41").unwrap();
        let __el1 = document.create_element("header").unwrap();
        __el1.set_attribute("class", "head head-card-c-0fb22f41").unwrap();
        if let Some(__cb) = self.__slot_badge.borrow().as_ref() {
            let __slot_target: &web_sys::Node = __el1.as_ref();
            __cb(__slot_target);
        } else {
        let __t2 = document.create_text_node("·");
        __el1.append_child(&__t2).unwrap();
        }
        let __el3 = document.create_element("h2").unwrap();
        __el3.set_attribute("class", "title title-card-c-0fb22f41").unwrap();
        let __interp4 = format!("{}", (*self.title.borrow()));
        let __t5 = document.create_text_node(&__interp4);
        __el3.append_child(&__t5).unwrap();
        __el1.append_child(&__el3).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el6 = document.create_element("div").unwrap();
        __el6.set_attribute("class", "body body-card-c-0fb22f41").unwrap();
        if let Some(__cb) = self.__slot.borrow().as_ref() {
            let __slot_target: &web_sys::Node = __el6.as_ref();
            __cb(__slot_target);
        } else {
        let __t7 = document.create_text_node("(no body)");
        __el6.append_child(&__t7).unwrap();
        }
        __el0.append_child(&__el6).unwrap();
        let __el8 = document.create_element("button").unwrap();
        __el8.set_attribute("class", "like like-card-c-0fb22f41").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                let __payload = std::collections::HashMap::<String, String>::new();
                Card::like(&__self_clone, &__payload);
            }) as Box<dyn FnMut(Event)>);
            __el8.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t9 = document.create_text_node("♥ ");
        __el8.append_child(&__t9).unwrap();
        let __interp10 = format!("{}", (*self.likes.borrow()));
        let __t11 = document.create_text_node(&__interp10);
        __el8.append_child(&__t11).unwrap();
        __el0.append_child(&__el8).unwrap();
        root.append_child(&__el0).unwrap();
    }
}

fn __inject_style_Card_card_c_0fb22f41() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .card-card-c-0fb22f41 { border: 1px solid #ddd; border-radius: 10px; padding: 14px 16px; background: #fff; display: flex; flex-direction: column; gap: 10px; }\n    .head-card-c-0fb22f41 { display: flex; align-items: center; gap: 8px; }\n    .title-card-c-0fb22f41 { margin: 0; font-size: 1.1em; }\n    .body-card-c-0fb22f41 { color: #444; }\n    .like-card-c-0fb22f41 { align-self: flex-start; padding: 6px 12px; cursor: pointer; border: 1px solid #c33; border-radius: 6px; background: #fff; color: #c33; }\n  "));
    let _ = head.append_child(&style_el);
}

pub struct App {
    heading: RefCell<String>,
    total: RefCell<i64>,
    __child_slot_0: RefCell<Option<Rc<Card>>>,
    __child_slot_1: RefCell<Option<Rc<Card>>>,
    root: RefCell<Option<HtmlElement>>,
}

impl App {
    pub fn new() -> Rc<Self> {
        Rc::new(App {
            heading: RefCell::new("Cross-file cards".to_string()),
            total: RefCell::new(0i64),
            __child_slot_0: RefCell::new(None),
            __child_slot_1: RefCell::new(None),
            root: RefCell::new(None),
        })
    }

    fn bump(self: &Rc<Self>) {
        let __rhs = ((*self.total.borrow()) + 1i64);
        *self.total.borrow_mut() = __rhs;
        self.render();
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_App_app_c_1277fdb3();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("main").unwrap();
        __el0.set_attribute("class", "app app-app-c-1277fdb3").unwrap();
        let __el1 = document.create_element("h1").unwrap();
        let __interp2 = format!("{}", (*self.heading.borrow()));
        let __t3 = document.create_text_node(&__interp2);
        __el1.append_child(&__t3).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el4 = document.create_element("p").unwrap();
        __el4.set_attribute("class", "total total-app-c-1277fdb3").unwrap();
        let __t5 = document.create_text_node("Total likes across cards: ");
        __el4.append_child(&__t5).unwrap();
        let __interp6 = format!("{}", (*self.total.borrow()));
        let __t7 = document.create_text_node(&__interp6);
        __el4.append_child(&__t7).unwrap();
        __el0.append_child(&__el4).unwrap();
        let __el8 = document.create_element("div").unwrap();
        __el8.set_attribute("class", "__fitz-child-Card").unwrap();
        __el0.append_child(&__el8).unwrap();
        let __child9 = {
            let mut __slot = self.__child_slot_0.borrow_mut();
            if __slot.is_none() { *__slot = Some(Card::new()); }
            __slot.as_ref().unwrap().clone()
        };
        *__child9.title.borrow_mut() = "Patagonia".to_string();
        {
            let __parent = self.clone();
            *__child9.__on_like.borrow_mut() = Some(Box::new(move |_: &std::collections::HashMap<String, String>| {
                App::bump(&__parent);
            }));
        }
        {
            let __parent = self.clone();
            *__child9.__slot.borrow_mut() = Some(Rc::new(move |__t: &web_sys::Node| __parent.__render_slot_0(__t)));
        }
        {
            let __parent = self.clone();
            *__child9.__slot_badge.borrow_mut() = Some(Rc::new(move |__t: &web_sys::Node| __parent.__render_slot_1(__t)));
        }
        let __el8_html = __el8.clone().dyn_into::<HtmlElement>().unwrap();
        __child9.mount_into(__el8_html).unwrap();
        let __el10 = document.create_element("div").unwrap();
        __el10.set_attribute("class", "__fitz-child-Card").unwrap();
        __el0.append_child(&__el10).unwrap();
        let __child11 = {
            let mut __slot = self.__child_slot_1.borrow_mut();
            if __slot.is_none() { *__slot = Some(Card::new()); }
            __slot.as_ref().unwrap().clone()
        };
        *__child11.title.borrow_mut() = "El Chaltén".to_string();
        {
            let __parent = self.clone();
            *__child11.__on_like.borrow_mut() = Some(Box::new(move |_: &std::collections::HashMap<String, String>| {
                App::bump(&__parent);
            }));
        }
        {
            let __parent = self.clone();
            *__child11.__slot.borrow_mut() = Some(Rc::new(move |__t: &web_sys::Node| __parent.__render_slot_2(__t)));
        }
        let __el10_html = __el10.clone().dyn_into::<HtmlElement>().unwrap();
        __child11.mount_into(__el10_html).unwrap();
        root.append_child(&__el0).unwrap();
    }
    fn __render_slot_0(self: &Rc<Self>, __target: &web_sys::Node) {
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("p").unwrap();
        let __t1 = document.create_text_node("The body of a card is written by the PARENT and rendered in the parent's scope.");
        __el0.append_child(&__t1).unwrap();
        __target.append_child(&__el0).unwrap();
    }

    fn __render_slot_1(self: &Rc<Self>, __target: &web_sys::Node) {
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("span").unwrap();
        __el0.set_attribute("class", "badge").unwrap();
        let __t1 = document.create_text_node("NEW");
        __el0.append_child(&__t1).unwrap();
        __target.append_child(&__el0).unwrap();
    }

    fn __render_slot_2(self: &Rc<Self>, __target: &web_sys::Node) {
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("p").unwrap();
        let __t1 = document.create_text_node("This card fills only the default slot, so the badge above falls back to its own content.");
        __el0.append_child(&__t1).unwrap();
        __target.append_child(&__el0).unwrap();
    }

}

fn __inject_style_App_app_c_1277fdb3() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .app-app-c-1277fdb3 { font-family: system-ui, sans-serif; max-width: 520px; display: flex; flex-direction: column; gap: 14px; }\n    .total-app-c-1277fdb3 { color: #555; font-weight: 600; }\n    .badge-app-c-1277fdb3 { background: #c33; color: #fff; font-size: 0.7em; font-weight: 700; padding: 2px 6px; border-radius: 4px; }\n  "));
    let _ = head.append_child(&style_el);
}



// Composed entry point — NOT part of emit_module output.
// `fitz build --target wasm-client` (Phase 11.5.c) appends this
// wrapper so the bundle mounts the root component when the
// browser calls the `start` export.
#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    console_error_panic_hook::set_once();
    let root = App::new();
    root.mount("#app")?;
    Ok(())
}
