// AUTO-GENERATED by `fitz build --target wasm-client`.
// Do NOT edit by hand — regenerate from the source `.fitzv`.
//
// Source: App.fitzv
//
// Composed by `src/view/wasm_build.rs::compose_lib_rs` (Phase 11.5.c).
// The tail below is the `#[wasm_bindgen(start)]` wrapper the CLI
// appends to the emitter output; the emitter itself does NOT emit
// the entry point so future targets (SSR, hybrid) can compose
// their own.

// Generated by fitz view WASM emitter (Fase 11.4.b).
// Do NOT edit — regenerate from the source `.fitzv`.

// Phase 11.5.e (§9.o Debt residual) — crate-level allows for
// the two cosmetic warnings that are structural to the
// emitter output, not correctness bugs:
//   - `non_snake_case`: component names are PascalCase by
//     convention (11.5.d), and the synthesised style helper
//     `__inject_style_<Component>_<scope>` reflects that.
//   - `unused_parens`: BinOp lowering wraps sub-expressions
//     in `(...)` to preserve precedence when nested. When
//     the BinOp is the entire RHS of an assignment the outer
//     parens are redundant but harmless.
#![allow(non_snake_case, unused_parens)]

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::atomic::{AtomicBool, Ordering};
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement};

pub struct App {
    name: RefCell<String>,
    __child_slot_0: RefCell<Option<Rc<Panel>>>,
    __child_slot_1: RefCell<Option<Rc<Panel>>>,
    root: RefCell<Option<HtmlElement>>,
}

impl App {
    pub fn new() -> Rc<Self> {
        Rc::new(App {
            name: RefCell::new("world".to_string()),
            __child_slot_0: RefCell::new(None),
            __child_slot_1: RefCell::new(None),
            root: RefCell::new(None),
        })
    }

    fn greet(self: &Rc<Self>) {
        let __rhs = "Fitz".to_string();
        *self.name.borrow_mut() = __rhs;
        self.render();
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_App_app_c_df2297e5();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("div").unwrap();
        __el0.set_attribute("class", "app app-app-c-df2297e5").unwrap();
        let __el1 = document.create_element("h1").unwrap();
        let __t2 = document.create_text_node("Slots on WASM");
        __el1.append_child(&__t2).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el3 = document.create_element("div").unwrap();
        __el3.set_attribute("class", "__fitz-child-Panel").unwrap();
        __el0.append_child(&__el3).unwrap();
        let __child4 = {
            let mut __slot = self.__child_slot_0.borrow_mut();
            if __slot.is_none() { *__slot = Some(Panel::new()); }
            __slot.as_ref().unwrap().clone()
        };
        {
            let __parent = self.clone();
            *__child4.__slot.borrow_mut() = Some(Rc::new(move |__t: &web_sys::Node| __parent.__render_slot_0(__t)));
        }
        let __el3_html = __el3.clone().dyn_into::<HtmlElement>().unwrap();
        __child4.mount_into(__el3_html).unwrap();
        let __el5 = document.create_element("div").unwrap();
        __el5.set_attribute("class", "__fitz-child-Panel").unwrap();
        __el0.append_child(&__el5).unwrap();
        let __child6 = {
            let mut __slot = self.__child_slot_1.borrow_mut();
            if __slot.is_none() { *__slot = Some(Panel::new()); }
            __slot.as_ref().unwrap().clone()
        };
        let __el5_html = __el5.clone().dyn_into::<HtmlElement>().unwrap();
        __child6.mount_into(__el5_html).unwrap();
        root.append_child(&__el0).unwrap();
    }
    fn __render_slot_0(self: &Rc<Self>, __target: &web_sys::Node) {
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("p").unwrap();
        __el0.set_attribute("class", "filled").unwrap();
        let __t1 = document.create_text_node("Hello, ");
        __el0.append_child(&__t1).unwrap();
        let __interp2 = format!("{}", (*self.name.borrow()));
        let __t3 = document.create_text_node(&__interp2);
        __el0.append_child(&__t3).unwrap();
        let __t4 = document.create_text_node("! (parent-provided slot content)");
        __el0.append_child(&__t4).unwrap();
        __target.append_child(&__el0).unwrap();
        let __el5 = document.create_element("button").unwrap();
        __el5.set_attribute("class", "btn").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                App::greet(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __el5.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t6 = document.create_text_node("set name to Fitz");
        __el5.append_child(&__t6).unwrap();
        __target.append_child(&__el5).unwrap();
    }

}

fn __inject_style_App_app_c_df2297e5() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .app-app-c-df2297e5 { font-family: system-ui, sans-serif; max-width: 520px; }\n    .filled-app-c-df2297e5 { margin: 0 0 8px 0; }\n    .btn-app-c-df2297e5 { padding: 6px 12px; cursor: pointer; border: 1px solid #999; border-radius: 6px; background: white; }\n  "));
    let _ = head.append_child(&style_el);
}

pub struct Panel {
    __slot: RefCell<Option<Rc<dyn Fn(&web_sys::Node)>>>,
    root: RefCell<Option<HtmlElement>>,
}

impl Panel {
    pub fn new() -> Rc<Self> {
        Rc::new(Panel {
            __slot: RefCell::new(None),
            root: RefCell::new(None),
        })
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_Panel_panel_c_4a3e1fec();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("section").unwrap();
        __el0.set_attribute("class", "panel panel-panel-c-4a3e1fec").unwrap();
        let __el1 = document.create_element("header").unwrap();
        __el1.set_attribute("class", "panel-head panel-head-panel-c-4a3e1fec").unwrap();
        let __t2 = document.create_text_node("Panel header (from the child)");
        __el1.append_child(&__t2).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el3 = document.create_element("div").unwrap();
        __el3.set_attribute("class", "panel-body panel-body-panel-c-4a3e1fec").unwrap();
        if let Some(__cb) = self.__slot.borrow().as_ref() {
            let __slot_target: &web_sys::Node = __el3.as_ref();
            __cb(__slot_target);
        } else {
        let __el4 = document.create_element("em").unwrap();
        let __t5 = document.create_text_node("default fallback content — this panel wasn't filled");
        __el4.append_child(&__t5).unwrap();
        __el3.append_child(&__el4).unwrap();
        }
        __el0.append_child(&__el3).unwrap();
        root.append_child(&__el0).unwrap();
    }
}

fn __inject_style_Panel_panel_c_4a3e1fec() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .panel-panel-c-4a3e1fec { border: 1px solid #ddd; border-radius: 8px; margin: 12px 0; overflow: hidden; }\n    .panel-head-panel-c-4a3e1fec { background: #f4f4f4; padding: 8px 12px; font-weight: 600; font-size: 0.9rem; }\n    .panel-body-panel-c-4a3e1fec { padding: 12px; }\n  "));
    let _ = head.append_child(&style_el);
}



// Composed entry point — NOT part of emit_module output.
// `fitz build --target wasm-client` (Phase 11.5.c) appends this
// wrapper so the bundle mounts the root component when the
// browser calls the `start` export.
#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    console_error_panic_hook::set_once();
    let root = App::new();
    root.mount("#app")?;
    Ok(())
}
