// AUTO-GENERATED by `fitz build --target wasm-client`.
// Do NOT edit by hand — regenerate from the source `.fitzv`.
//
// Source: App.fitzv
//
// Composed by `src/view/wasm_build.rs::compose_lib_rs` (Phase 11.5.c).
// The tail below is the `#[wasm_bindgen(start)]` wrapper the CLI
// appends to the emitter output; the emitter itself does NOT emit
// the entry point so future targets (SSR, hybrid) can compose
// their own.

// Generated by fitz view WASM emitter (Fase 11.4.b).
// Do NOT edit — regenerate from the source `.fitzv`.

// Phase 11.5.e (§9.o Debt residual) — crate-level allows for
// the two cosmetic warnings that are structural to the
// emitter output, not correctness bugs:
//   - `non_snake_case`: component names are PascalCase by
//     convention (11.5.d), and the synthesised style helper
//     `__inject_style_<Component>_<scope>` reflects that.
//   - `unused_parens`: BinOp lowering wraps sub-expressions
//     in `(...)` to preserve precedence when nested. When
//     the BinOp is the entire RHS of an assignment the outer
//     parens are redundant but harmless.
#![allow(non_snake_case, unused_parens)]

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::atomic::{AtomicBool, Ordering};
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement};

// Phase 11.12 — hydration cursor helpers. Advance a sibling cursor to
// the next element / text node so the adopt walk maps template nodes
// onto the server-painted DOM in DFS order without re-creating them.
fn __flv_next_element(__cursor: &mut Option<web_sys::Node>) -> Option<web_sys::Element> {
    while let Some(__n) = __cursor.clone() {
        *__cursor = __n.next_sibling();
        if let Some(__el) = __n.dyn_ref::<web_sys::Element>() {
            return Some(__el.clone());
        }
    }
    None
}
fn __flv_next_text(__cursor: &mut Option<web_sys::Node>) -> Option<web_sys::Text> {
    while let Some(__n) = __cursor.clone() {
        *__cursor = __n.next_sibling();
        if let Some(__t) = __n.dyn_ref::<web_sys::Text>() {
            return Some(__t.clone());
        }
    }
    None
}

pub struct LiveInput {
    name: RefCell<String>,
    color: RefCell<String>,
    __kattr_0: RefCell<Option<web_sys::Element>>,
    __ktext_1: RefCell<Option<web_sys::Text>>,
    __kattr_2: RefCell<Option<web_sys::Element>>,
    __ktext_3: RefCell<Option<web_sys::Text>>,
    __built: RefCell<bool>,
    root: RefCell<Option<HtmlElement>>,
}

impl LiveInput {
    pub fn new() -> Rc<Self> {
        Rc::new(LiveInput {
            name: RefCell::new("".to_string()),
            color: RefCell::new("red".to_string()),
            __kattr_0: RefCell::new(None),
            __ktext_1: RefCell::new(None),
            __kattr_2: RefCell::new(None),
            __ktext_3: RefCell::new(None),
            __built: RefCell::new(false),
            root: RefCell::new(None),
        })
    }

    fn on_name(self: &Rc<Self>, payload: &std::collections::HashMap<String, String>) {
        let __rhs = payload.get(&("value".to_string())).cloned().unwrap_or_default();
        *self.name.borrow_mut() = __rhs;
        self.render();
    }

    fn on_color(self: &Rc<Self>, payload: &std::collections::HashMap<String, String>) {
        let __rhs = payload.get(&("value".to_string())).cloned().unwrap_or_default();
        *self.color.borrow_mut() = __rhs;
        self.render();
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        *self.__built.borrow_mut() = false;
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        if *self.__built.borrow() {
            self.__patch();
        } else {
            self.__build();
            *self.__built.borrow_mut() = true;
        }
    }

    fn __build(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("div").unwrap();
        __el0.set_attribute("class", "live").unwrap();
        let __el1 = document.create_element("h1").unwrap();
        let __t2 = document.create_text_node("Live input on WASM");
        __el1.append_child(&__t2).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el3 = document.create_element("label").unwrap();
        __el3.set_attribute("class", "row").unwrap();
        let __el4 = document.create_element("span").unwrap();
        let __t5 = document.create_text_node("Favourite colour");
        __el4.append_child(&__t5).unwrap();
        __el3.append_child(&__el4).unwrap();
        let __el6 = document.create_element("select").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |__evt: Event| {
                let mut __payload = std::collections::HashMap::<String, String>::new();
                if let Some(__t) = __evt.target() {
                    if let Some(__el) = __t.dyn_ref::<web_sys::HtmlInputElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlSelectElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlTextAreaElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    }
                }
                LiveInput::on_color(&__self_clone, &__payload);
            }) as Box<dyn FnMut(Event)>);
            __el6.add_event_listener_with_callback("change", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __el7 = document.create_element("option").unwrap();
        __el7.set_attribute("value", "red").unwrap();
        let __t8 = document.create_text_node("Red");
        __el7.append_child(&__t8).unwrap();
        __el6.append_child(&__el7).unwrap();
        let __el9 = document.create_element("option").unwrap();
        __el9.set_attribute("value", "green").unwrap();
        let __t10 = document.create_text_node("Green");
        __el9.append_child(&__t10).unwrap();
        __el6.append_child(&__el9).unwrap();
        let __el11 = document.create_element("option").unwrap();
        __el11.set_attribute("value", "blue").unwrap();
        let __t12 = document.create_text_node("Blue");
        __el11.append_child(&__t12).unwrap();
        __el6.append_child(&__el11).unwrap();
        __el3.append_child(&__el6).unwrap();
        __el0.append_child(&__el3).unwrap();
        let __el13 = document.create_element("p").unwrap();
        __el13.set_attribute("class", "swatch").unwrap();
        __el13.set_attribute("style", &format!("background: {}", (*self.color.borrow()))).unwrap();
        *self.__kattr_0.borrow_mut() = Some(__el13.clone());
        let __t14 = document.create_text_node("Picked: ");
        __el13.append_child(&__t14).unwrap();
        let __interp15 = format!("{}", (*self.color.borrow()));
        let __t16 = document.create_text_node(&__interp15);
        __el13.append_child(&__t16).unwrap();
        *self.__ktext_1.borrow_mut() = Some(__t16.clone());
        __el0.append_child(&__el13).unwrap();
        let __el17 = document.create_element("label").unwrap();
        __el17.set_attribute("class", "row").unwrap();
        let __el18 = document.create_element("span").unwrap();
        let __t19 = document.create_text_node("Your name");
        __el18.append_child(&__t19).unwrap();
        __el17.append_child(&__el18).unwrap();
        let __el20 = document.create_element("input").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |__evt: Event| {
                let mut __payload = std::collections::HashMap::<String, String>::new();
                if let Some(__t) = __evt.target() {
                    if let Some(__el) = __t.dyn_ref::<web_sys::HtmlInputElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlSelectElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlTextAreaElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    }
                }
                LiveInput::on_name(&__self_clone, &__payload);
            }) as Box<dyn FnMut(Event)>);
            __el20.add_event_listener_with_callback("input", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        __el20.set_attribute("value", &format!("{}", (*self.name.borrow()))).unwrap();
        *self.__kattr_2.borrow_mut() = Some(__el20.clone());
        __el20.set_attribute("placeholder", "Type here").unwrap();
        __el20.set_attribute("autocomplete", "off").unwrap();
        __el17.append_child(&__el20).unwrap();
        __el0.append_child(&__el17).unwrap();
        let __el21 = document.create_element("p").unwrap();
        __el21.set_attribute("class", "echo").unwrap();
        let __t22 = document.create_text_node("Hello, ");
        __el21.append_child(&__t22).unwrap();
        let __interp23 = format!("{}", (*self.name.borrow()));
        let __t24 = document.create_text_node(&__interp23);
        __el21.append_child(&__t24).unwrap();
        *self.__ktext_3.borrow_mut() = Some(__t24.clone());
        let __t25 = document.create_text_node("!");
        __el21.append_child(&__t25).unwrap();
        __el0.append_child(&__el21).unwrap();
        root.append_child(&__el0).unwrap();
    }

    fn __patch(self: &Rc<Self>) {
        if let Some(__el) = self.__kattr_0.borrow().as_ref() { let _ = __el.set_attribute("style", &format!("background: {}", (*self.color.borrow()))); }
        if let Some(__n) = self.__ktext_1.borrow().as_ref() { __n.set_data(&format!("{}", (*self.color.borrow()))); }
        if let Some(__el) = self.__kattr_2.borrow().as_ref() { let _ = __el.set_attribute("value", &format!("{}", (*self.name.borrow()))); }
        if let Some(__n) = self.__ktext_3.borrow().as_ref() { __n.set_data(&format!("{}", (*self.name.borrow()))); }
    }

    fn __apply_state_json(self: &Rc<Self>, __json: &str) {
        let __v: serde_json::Value = match serde_json::from_str(__json) { Ok(__j) => __j, Err(_) => return, };
        let _ = (&__v, self);
        if let Some(__x) = __v.get("name").and_then(|__j| __j.as_str()) { *self.name.borrow_mut() = __x.to_string(); }
        if let Some(__x) = __v.get("color").and_then(|__j| __j.as_str()) { *self.color.borrow_mut() = __x.to_string(); }
    }

    pub fn hydrate(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        if let Some(__sel) = web_sys::window().unwrap().document().unwrap().get_element_by_id("__flv_state_LiveInput") {
            if let Some(__txt) = __sel.text_content() { self.__apply_state_json(&__txt); }
        }
        let mut __cur_root = root.first_child();
        *self.root.borrow_mut() = Some(root);
        if let Some(__hel0) = __flv_next_element(&mut __cur_root) {
        let mut __hcur1 = __hel0.first_child();
        if let Some(__hel2) = __flv_next_element(&mut __hcur1) {
        let mut __hcur3 = __hel2.first_child();
        let _ = __flv_next_text(&mut __hcur3);
        }
        if let Some(__hel4) = __flv_next_element(&mut __hcur1) {
        let mut __hcur5 = __hel4.first_child();
        if let Some(__hel6) = __flv_next_element(&mut __hcur5) {
        let mut __hcur7 = __hel6.first_child();
        let _ = __flv_next_text(&mut __hcur7);
        }
        if let Some(__hel8) = __flv_next_element(&mut __hcur5) {
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |__evt: Event| {
                let mut __payload = std::collections::HashMap::<String, String>::new();
                if let Some(__t) = __evt.target() {
                    if let Some(__el) = __t.dyn_ref::<web_sys::HtmlInputElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlSelectElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlTextAreaElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    }
                }
                LiveInput::on_color(&__self_clone, &__payload);
            }) as Box<dyn FnMut(Event)>);
            __hel8.add_event_listener_with_callback("change", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let mut __hcur9 = __hel8.first_child();
        if let Some(__hel10) = __flv_next_element(&mut __hcur9) {
        let mut __hcur11 = __hel10.first_child();
        let _ = __flv_next_text(&mut __hcur11);
        }
        if let Some(__hel12) = __flv_next_element(&mut __hcur9) {
        let mut __hcur13 = __hel12.first_child();
        let _ = __flv_next_text(&mut __hcur13);
        }
        if let Some(__hel14) = __flv_next_element(&mut __hcur9) {
        let mut __hcur15 = __hel14.first_child();
        let _ = __flv_next_text(&mut __hcur15);
        }
        }
        }
        if let Some(__hel16) = __flv_next_element(&mut __hcur1) {
        *self.__kattr_0.borrow_mut() = Some(__hel16.clone());
        let mut __hcur17 = __hel16.first_child();
        let _ = __flv_next_text(&mut __hcur17);
        if let Some(__hn) = __flv_next_text(&mut __hcur17) { *self.__ktext_1.borrow_mut() = Some(__hn); }
        }
        if let Some(__hel18) = __flv_next_element(&mut __hcur1) {
        let mut __hcur19 = __hel18.first_child();
        if let Some(__hel20) = __flv_next_element(&mut __hcur19) {
        let mut __hcur21 = __hel20.first_child();
        let _ = __flv_next_text(&mut __hcur21);
        }
        if let Some(__hel22) = __flv_next_element(&mut __hcur19) {
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |__evt: Event| {
                let mut __payload = std::collections::HashMap::<String, String>::new();
                if let Some(__t) = __evt.target() {
                    if let Some(__el) = __t.dyn_ref::<web_sys::HtmlInputElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlSelectElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlTextAreaElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    }
                }
                LiveInput::on_name(&__self_clone, &__payload);
            }) as Box<dyn FnMut(Event)>);
            __hel22.add_event_listener_with_callback("input", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        *self.__kattr_2.borrow_mut() = Some(__hel22.clone());
        }
        }
        if let Some(__hel24) = __flv_next_element(&mut __hcur1) {
        let mut __hcur25 = __hel24.first_child();
        let _ = __flv_next_text(&mut __hcur25);
        if let Some(__hn) = __flv_next_text(&mut __hcur25) { *self.__ktext_3.borrow_mut() = Some(__hn); }
        let _ = __flv_next_text(&mut __hcur25);
        }
        }
        *self.__built.borrow_mut() = true;
        Ok(())
    }

}



// Composed entry point — NOT part of emit_module output.
// `fitz build --target wasm-client` appends this wrapper. Phase
// 11.12: hydrate the server-painted DOM when the mount root
// already has content, else fresh-mount into an empty root.
#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    console_error_panic_hook::set_once();
    let root = LiveInput::new();
    let __document = web_sys::window().unwrap().document().unwrap();
    if let Some(__mount) = __document.query_selector("#app")? {
        if __mount.first_element_child().is_some() {
            let __el = __mount.dyn_into::<web_sys::HtmlElement>()?;
            return root.hydrate(__el);
        }
    }
    root.mount("#app")?;
    Ok(())
}
