// AUTO-GENERATED by `fitz build --target wasm-client`.
// Do NOT edit by hand — regenerate from the source `.fitzv`.
//
// Source: App.fitzv
//
// Composed by `src/view/wasm_build.rs::compose_lib_rs` (Phase 11.5.c).
// The tail below is the `#[wasm_bindgen(start)]` wrapper the CLI
// appends to the emitter output; the emitter itself does NOT emit
// the entry point so future targets (SSR, hybrid) can compose
// their own.

// Generated by fitz view WASM emitter (Fase 11.4.b).
// Do NOT edit — regenerate from the source `.fitzv`.

// Phase 11.5.e (§9.o Debt residual) — crate-level allows for
// the two cosmetic warnings that are structural to the
// emitter output, not correctness bugs:
//   - `non_snake_case`: component names are PascalCase by
//     convention (11.5.d), and the synthesised style helper
//     `__inject_style_<Component>_<scope>` reflects that.
//   - `unused_parens`: BinOp lowering wraps sub-expressions
//     in `(...)` to preserve precedence when nested. When
//     the BinOp is the entire RHS of an assignment the outer
//     parens are redundant but harmless.
#![allow(non_snake_case, unused_parens)]

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::atomic::{AtomicBool, Ordering};
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement};

pub struct Badge {
    label: RefCell<String>,
    root: RefCell<Option<HtmlElement>>,
}

impl Badge {
    pub fn new() -> Rc<Self> {
        Rc::new(Badge {
            label: RefCell::new("".to_string()),
            root: RefCell::new(None),
        })
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_Badge_badge_c_63b1d3ac();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("span").unwrap();
        __el0.set_attribute("class", "badge badge-badge-c-63b1d3ac").unwrap();
        let __interp1 = format!("{}", (*self.label.borrow()));
        let __t2 = document.create_text_node(&__interp1);
        __el0.append_child(&__t2).unwrap();
        root.append_child(&__el0).unwrap();
    }
}

fn __inject_style_Badge_badge_c_63b1d3ac() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .badge-badge-c-63b1d3ac { background: #eef; color: #33c; font-size: 0.7em; font-weight: 700; padding: 2px 6px; border-radius: 4px; }\n  "));
    let _ = head.append_child(&style_el);
}

pub struct Row {
    title: RefCell<String>,
    likes: RefCell<i64>,
    __child_slot_0: RefCell<Option<Rc<Badge>>>,
    __on_like: RefCell<Option<Box<dyn Fn(&std::collections::HashMap<String, String>)>>>,
    root: RefCell<Option<HtmlElement>>,
}

impl Row {
    pub fn new() -> Rc<Self> {
        Rc::new(Row {
            title: RefCell::new("Untitled".to_string()),
            likes: RefCell::new(0i64),
            __child_slot_0: RefCell::new(None),
            __on_like: RefCell::new(None),
            root: RefCell::new(None),
        })
    }

    fn like(self: &Rc<Self>, payload: &std::collections::HashMap<String, String>) {
        let __rhs = ((*self.likes.borrow()) + 1i64);
        *self.likes.borrow_mut() = __rhs;
        self.render();
        if let Some(__cb) = self.__on_like.borrow().as_ref() { __cb(payload); }
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_Row_card_c_acec70a2();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("article").unwrap();
        __el0.set_attribute("class", "card card-card-c-acec70a2").unwrap();
        let __el1 = document.create_element("header").unwrap();
        __el1.set_attribute("class", "head head-card-c-acec70a2").unwrap();
        let __el2 = document.create_element("div").unwrap();
        __el2.set_attribute("class", "__fitz-child-Badge").unwrap();
        __el1.append_child(&__el2).unwrap();
        let __child3 = {
            let mut __slot = self.__child_slot_0.borrow_mut();
            if __slot.is_none() { *__slot = Some(Badge::new()); }
            __slot.as_ref().unwrap().clone()
        };
        *__child3.label.borrow_mut() = "peak".to_string();
        let __el2_html = __el2.clone().dyn_into::<HtmlElement>().unwrap();
        __child3.mount_into(__el2_html).unwrap();
        let __el4 = document.create_element("h2").unwrap();
        __el4.set_attribute("class", "title title-card-c-acec70a2").unwrap();
        let __interp5 = format!("{}", (*self.title.borrow()));
        let __t6 = document.create_text_node(&__interp5);
        __el4.append_child(&__t6).unwrap();
        __el1.append_child(&__el4).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el7 = document.create_element("button").unwrap();
        __el7.set_attribute("class", "like like-card-c-acec70a2").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                let __payload = std::collections::HashMap::<String, String>::new();
                Row::like(&__self_clone, &__payload);
            }) as Box<dyn FnMut(Event)>);
            __el7.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t8 = document.create_text_node("♥ ");
        __el7.append_child(&__t8).unwrap();
        let __interp9 = format!("{}", (*self.likes.borrow()));
        let __t10 = document.create_text_node(&__interp9);
        __el7.append_child(&__t10).unwrap();
        __el0.append_child(&__el7).unwrap();
        root.append_child(&__el0).unwrap();
    }
}

fn __inject_style_Row_card_c_acec70a2() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .card-card-c-acec70a2 { border: 1px solid #ddd; border-radius: 10px; padding: 12px 14px; background: #fff; display: flex; flex-direction: column; gap: 8px; }\n    .head-card-c-acec70a2 { display: flex; align-items: center; gap: 8px; }\n    .title-card-c-acec70a2 { margin: 0; font-size: 1.05em; }\n    .like-card-c-acec70a2 { align-self: flex-start; padding: 5px 10px; cursor: pointer; border: 1px solid #c33; border-radius: 6px; background: #fff; color: #c33; }\n  "));
    let _ = head.append_child(&style_el);
}

pub struct App {
    heading: RefCell<String>,
    total: RefCell<i64>,
    __child_slot_0: RefCell<Option<Rc<Row>>>,
    __child_slot_1: RefCell<Option<Rc<Row>>>,
    root: RefCell<Option<HtmlElement>>,
}

impl App {
    pub fn new() -> Rc<Self> {
        Rc::new(App {
            heading: RefCell::new("Transitive + alias demo".to_string()),
            total: RefCell::new(0i64),
            __child_slot_0: RefCell::new(None),
            __child_slot_1: RefCell::new(None),
            root: RefCell::new(None),
        })
    }

    fn bump(self: &Rc<Self>) {
        let __rhs = ((*self.total.borrow()) + 1i64);
        *self.total.borrow_mut() = __rhs;
        self.render();
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_App_app_c_9dd85aea();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("main").unwrap();
        __el0.set_attribute("class", "app app-app-c-9dd85aea").unwrap();
        let __el1 = document.create_element("h1").unwrap();
        let __interp2 = format!("{}", (*self.heading.borrow()));
        let __t3 = document.create_text_node(&__interp2);
        __el1.append_child(&__t3).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el4 = document.create_element("p").unwrap();
        __el4.set_attribute("class", "total total-app-c-9dd85aea").unwrap();
        let __t5 = document.create_text_node("Cards liked: ");
        __el4.append_child(&__t5).unwrap();
        let __interp6 = format!("{}", (*self.total.borrow()));
        let __t7 = document.create_text_node(&__interp6);
        __el4.append_child(&__t7).unwrap();
        __el0.append_child(&__el4).unwrap();
        let __el8 = document.create_element("div").unwrap();
        __el8.set_attribute("class", "__fitz-child-Row").unwrap();
        __el0.append_child(&__el8).unwrap();
        let __child9 = {
            let mut __slot = self.__child_slot_0.borrow_mut();
            if __slot.is_none() { *__slot = Some(Row::new()); }
            __slot.as_ref().unwrap().clone()
        };
        *__child9.title.borrow_mut() = "Fitz Roy".to_string();
        {
            let __parent = self.clone();
            *__child9.__on_like.borrow_mut() = Some(Box::new(move |_: &std::collections::HashMap<String, String>| {
                App::bump(&__parent);
            }));
        }
        let __el8_html = __el8.clone().dyn_into::<HtmlElement>().unwrap();
        __child9.mount_into(__el8_html).unwrap();
        let __el10 = document.create_element("div").unwrap();
        __el10.set_attribute("class", "__fitz-child-Row").unwrap();
        __el0.append_child(&__el10).unwrap();
        let __child11 = {
            let mut __slot = self.__child_slot_1.borrow_mut();
            if __slot.is_none() { *__slot = Some(Row::new()); }
            __slot.as_ref().unwrap().clone()
        };
        *__child11.title.borrow_mut() = "Cerro Torre".to_string();
        {
            let __parent = self.clone();
            *__child11.__on_like.borrow_mut() = Some(Box::new(move |_: &std::collections::HashMap<String, String>| {
                App::bump(&__parent);
            }));
        }
        let __el10_html = __el10.clone().dyn_into::<HtmlElement>().unwrap();
        __child11.mount_into(__el10_html).unwrap();
        root.append_child(&__el0).unwrap();
    }
}

fn __inject_style_App_app_c_9dd85aea() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .app-app-c-9dd85aea { font-family: system-ui, sans-serif; max-width: 480px; display: flex; flex-direction: column; gap: 12px; }\n    .total-app-c-9dd85aea { color: #555; font-weight: 600; }\n  "));
    let _ = head.append_child(&style_el);
}



// Composed entry point — NOT part of emit_module output.
// `fitz build --target wasm-client` (Phase 11.5.c) appends this
// wrapper so the bundle mounts the root component when the
// browser calls the `start` export.
#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    console_error_panic_hook::set_once();
    let root = App::new();
    root.mount("#app")?;
    Ok(())
}
