// AUTO-GENERATED by `fitz build --target wasm-client`.
// Do NOT edit by hand — regenerate from the source `.fitzv`.
//
// Source: App.fitzv
//
// Composed by `src/view/wasm_build.rs::compose_lib_rs` (Phase 11.5.c).
// The tail below is the `#[wasm_bindgen(start)]` wrapper the CLI
// appends to the emitter output; the emitter itself does NOT emit
// the entry point so future targets (SSR, hybrid) can compose
// their own.

// Generated by fitz view WASM emitter (Fase 11.4.b).
// Do NOT edit — regenerate from the source `.fitzv`.

// Phase 11.5.e (§9.o Debt residual) — crate-level allows for
// the two cosmetic warnings that are structural to the
// emitter output, not correctness bugs:
//   - `non_snake_case`: component names are PascalCase by
//     convention (11.5.d), and the synthesised style helper
//     `__inject_style_<Component>_<scope>` reflects that.
//   - `unused_parens`: BinOp lowering wraps sub-expressions
//     in `(...)` to preserve precedence when nested. When
//     the BinOp is the entire RHS of an assignment the outer
//     parens are redundant but harmless.
#![allow(non_snake_case, unused_parens)]

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::atomic::{AtomicBool, Ordering};
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement};

pub struct Filter {
    query: RefCell<String>,
    items: RefCell<Vec<String>>,
    __kattr_0: RefCell<Option<web_sys::Element>>,
    __astart_0: RefCell<Option<web_sys::Node>>,
    __aend_0: RefCell<Option<web_sys::Node>>,
    __astart_1: RefCell<Option<web_sys::Node>>,
    __aend_1: RefCell<Option<web_sys::Node>>,
    __built: RefCell<bool>,
    root: RefCell<Option<HtmlElement>>,
}

impl Filter {
    pub fn new() -> Rc<Self> {
        Rc::new(Filter {
            query: RefCell::new("".to_string()),
            items: RefCell::new(vec!["apple".to_string(), "banana".to_string(), "cherry".to_string(), "grape".to_string(), "lemon".to_string(), "mango".to_string()]),
            __kattr_0: RefCell::new(None),
            __astart_0: RefCell::new(None),
            __aend_0: RefCell::new(None),
            __astart_1: RefCell::new(None),
            __aend_1: RefCell::new(None),
            __built: RefCell::new(false),
            root: RefCell::new(None),
        })
    }

    fn on_query(self: &Rc<Self>, payload: &std::collections::HashMap<String, String>) {
        let __rhs = payload.get(&("value".to_string())).cloned().unwrap_or_default();
        *self.query.borrow_mut() = __rhs;
        self.render();
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_Filter_filter_c_9a264632();
        *self.__built.borrow_mut() = false;
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        if *self.__built.borrow() {
            self.__patch();
        } else {
            self.__build();
            *self.__built.borrow_mut() = true;
        }
    }

    fn __build(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("div").unwrap();
        __el0.set_attribute("class", "filter filter-filter-c-9a264632").unwrap();
        let __el1 = document.create_element("h1").unwrap();
        let __t2 = document.create_text_node("Type a fruit to hide it");
        __el1.append_child(&__t2).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el3 = document.create_element("input").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |__evt: Event| {
                let mut __payload = std::collections::HashMap::<String, String>::new();
                if let Some(__t) = __evt.target() {
                    if let Some(__el) = __t.dyn_ref::<web_sys::HtmlInputElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlSelectElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    } else if let Some(__el) = __t.dyn_ref::<web_sys::HtmlTextAreaElement>() {
                        __payload.insert("value".to_string(), __el.value());
                    }
                }
                Filter::on_query(&__self_clone, &__payload);
            }) as Box<dyn FnMut(Event)>);
            __el3.add_event_listener_with_callback("input", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        __el3.set_attribute("value", &format!("{}", (*self.query.borrow()))).unwrap();
        *self.__kattr_0.borrow_mut() = Some(__el3.clone());
        __el3.set_attribute("placeholder", "type here…").unwrap();
        __el3.set_attribute("autocomplete", "off").unwrap();
        __el0.append_child(&__el3).unwrap();
        let __rs4: web_sys::Node = document.create_comment("").into();
        __el0.append_child(&__rs4).unwrap();
        *self.__astart_0.borrow_mut() = Some(__rs4.clone());
        let __re5: web_sys::Node = document.create_comment("").into();
        __el0.append_child(&__re5).unwrap();
        *self.__aend_0.borrow_mut() = Some(__re5.clone());
        self.__mount_region_0();
        let __el6 = document.create_element("ul").unwrap();
        __el6.set_attribute("class", "items items-filter-c-9a264632").unwrap();
        let __rs7: web_sys::Node = document.create_comment("").into();
        __el6.append_child(&__rs7).unwrap();
        *self.__astart_1.borrow_mut() = Some(__rs7.clone());
        let __re8: web_sys::Node = document.create_comment("").into();
        __el6.append_child(&__re8).unwrap();
        *self.__aend_1.borrow_mut() = Some(__re8.clone());
        self.__mount_region_1();
        __el0.append_child(&__el6).unwrap();
        root.append_child(&__el0).unwrap();
    }

    fn __patch(self: &Rc<Self>) {
        if let Some(__el) = self.__kattr_0.borrow().as_ref() { let _ = __el.set_attribute("value", &format!("{}", (*self.query.borrow()))); }
        self.__patch_region_0();
        self.__patch_region_1();
    }

    fn __mount_region_0(self: &Rc<Self>) {
        let document = web_sys::window().unwrap().document().unwrap();
        let __frag = document.create_document_fragment();
        if ((*self.query.borrow()) != "".to_string()) {
        let __el0 = document.create_element("p").unwrap();
        __el0.set_attribute("class", "hint hint-filter-c-9a264632").unwrap();
        let __t1 = document.create_text_node("Hiding: ");
        __el0.append_child(&__t1).unwrap();
        let __interp2 = format!("{}", (*self.query.borrow()));
        let __t3 = document.create_text_node(&__interp2);
        __el0.append_child(&__t3).unwrap();
        __frag.append_child(&__el0).unwrap();
        }
        if let Some(__e) = self.__aend_0.borrow().as_ref() {
            if let Some(__p) = __e.parent_node() {
                let _ = __p.insert_before(&__frag, Some(__e));
            }
        }
    }

    fn __patch_region_0(self: &Rc<Self>) {
        if let (Some(__s), Some(__e)) = (self.__astart_0.borrow().clone(), self.__aend_0.borrow().clone()) {
            while let Some(__n) = __s.next_sibling() {
                if __n.is_same_node(Some(&__e)) { break; }
                if let Some(__p) = __n.parent_node() { let _ = __p.remove_child(&__n); }
            }
        }
        self.__mount_region_0();
    }


    fn __mount_region_1(self: &Rc<Self>) {
        let document = web_sys::window().unwrap().document().unwrap();
        let __frag = document.create_document_fragment();
        let __for0 = (*self.items.borrow()).clone();
        for it in __for0.iter().cloned() {
        if (it != (*self.query.borrow())) {
        let __el1 = document.create_element("li").unwrap();
        let __interp2 = format!("{}", it);
        let __t3 = document.create_text_node(&__interp2);
        __el1.append_child(&__t3).unwrap();
        __frag.append_child(&__el1).unwrap();
        }
        }
        if let Some(__e) = self.__aend_1.borrow().as_ref() {
            if let Some(__p) = __e.parent_node() {
                let _ = __p.insert_before(&__frag, Some(__e));
            }
        }
    }

    fn __patch_region_1(self: &Rc<Self>) {
        if let (Some(__s), Some(__e)) = (self.__astart_1.borrow().clone(), self.__aend_1.borrow().clone()) {
            while let Some(__n) = __s.next_sibling() {
                if __n.is_same_node(Some(&__e)) { break; }
                if let Some(__p) = __n.parent_node() { let _ = __p.remove_child(&__n); }
            }
        }
        self.__mount_region_1();
    }

}

fn __inject_style_Filter_filter_c_9a264632() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .filter-filter-c-9a264632 { font-family: system-ui, sans-serif; display: grid; gap: 8px; max-width: 360px; }\n    .hint-filter-c-9a264632 { color: #b45309; font-size: 0.9em; }\n    .items-filter-c-9a264632 { margin: 0; padding-left: 1.2em; }\n  "));
    let _ = head.append_child(&style_el);
}



// Composed entry point — NOT part of emit_module output.
// `fitz build --target wasm-client` (Phase 11.5.c) appends this
// wrapper so the bundle mounts the root component when the
// browser calls the `start` export.
#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    console_error_panic_hook::set_once();
    let root = Filter::new();
    root.mount("#app")?;
    Ok(())
}
