// AUTO-GENERATED by `fitz build --target wasm-client`.
// Do NOT edit by hand — regenerate from the source `.fitzv`.
//
// Source: App.fitzv
//
// Composed by `src/view/wasm_build.rs::compose_lib_rs` (Phase 11.5.c).
// The tail below is the `#[wasm_bindgen(start)]` wrapper the CLI
// appends to the emitter output; the emitter itself does NOT emit
// the entry point so future targets (SSR, hybrid) can compose
// their own.

// Generated by fitz view WASM emitter (Fase 11.4.b).
// Do NOT edit — regenerate from the source `.fitzv`.

// Phase 11.5.e (§9.o Debt residual) — crate-level allows for
// the two cosmetic warnings that are structural to the
// emitter output, not correctness bugs:
//   - `non_snake_case`: component names are PascalCase by
//     convention (11.5.d), and the synthesised style helper
//     `__inject_style_<Component>_<scope>` reflects that.
//   - `unused_parens`: BinOp lowering wraps sub-expressions
//     in `(...)` to preserve precedence when nested. When
//     the BinOp is the entire RHS of an assignment the outer
//     parens are redundant but harmless.
#![allow(non_snake_case, unused_parens)]

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::atomic::{AtomicBool, Ordering};
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement};

pub struct App {
    title: RefCell<String>,
    clicks: RefCell<i64>,
    root: RefCell<Option<HtmlElement>>,
}

impl App {
    pub fn new() -> Rc<Self> {
        Rc::new(App {
            title: RefCell::new("Fitz reactive props".to_string()),
            clicks: RefCell::new(0i64),
            root: RefCell::new(None),
        })
    }

    fn bump(self: &Rc<Self>) {
        let __rhs = ((*self.clicks.borrow()) + 1i64);
        *self.clicks.borrow_mut() = __rhs;
        self.render();
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_App_app_c_811ecb28();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("div").unwrap();
        __el0.set_attribute("class", "app app-app-c-811ecb28").unwrap();
        let __el1 = document.create_element("h1").unwrap();
        let __interp2 = format!("{}", (*self.title.borrow()));
        let __t3 = document.create_text_node(&__interp2);
        __el1.append_child(&__t3).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el4 = document.create_element("p").unwrap();
        __el4.set_attribute("class", "hint hint-app-c-811ecb28").unwrap();
        let __t5 = document.create_text_node("Click below — the parent's ");
        __el4.append_child(&__t5).unwrap();
        let __el6 = document.create_element("code").unwrap();
        let __t7 = document.create_text_node("clicks");
        __el6.append_child(&__t7).unwrap();
        __el4.append_child(&__el6).unwrap();
        let __t8 = document.create_text_node(" flows into the child's ");
        __el4.append_child(&__t8).unwrap();
        let __el9 = document.create_element("code").unwrap();
        let __t10 = document.create_text_node("count");
        __el9.append_child(&__t10).unwrap();
        __el4.append_child(&__el9).unwrap();
        let __t11 = document.create_text_node(" prop.");
        __el4.append_child(&__t11).unwrap();
        __el0.append_child(&__el4).unwrap();
        let __el12 = document.create_element("button").unwrap();
        __el12.set_attribute("class", "bump bump-app-c-811ecb28").unwrap();
        {
            let __self_clone = self.clone();
            let __closure = Closure::wrap(Box::new(move |_evt: Event| {
                App::bump(&__self_clone);
            }) as Box<dyn FnMut(Event)>);
            __el12.add_event_listener_with_callback("click", __closure.as_ref().unchecked_ref()).unwrap();
            __closure.forget();
        }
        let __t13 = document.create_text_node("bump the parent");
        __el12.append_child(&__t13).unwrap();
        __el0.append_child(&__el12).unwrap();
        let __el14 = document.create_element("div").unwrap();
        __el14.set_attribute("class", "__fitz-child-Badge").unwrap();
        __el0.append_child(&__el14).unwrap();
        let __child15 = Badge::new();
        *__child15.heading.borrow_mut() = (*self.title.borrow()).clone();
        *__child15.count.borrow_mut() = ((*self.clicks.borrow()) + 1i64);
        let __el14_html = __el14.clone().dyn_into::<HtmlElement>().unwrap();
        __child15.mount_into(__el14_html).unwrap();
        root.append_child(&__el0).unwrap();
    }
}

fn __inject_style_App_app_c_811ecb28() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .app-app-c-811ecb28 { font-family: system-ui, sans-serif; }\n    .hint-app-c-811ecb28 { color: #666; font-size: 0.9em; }\n    .bump-app-c-811ecb28 { padding: 8px 16px; cursor: pointer; border: 1px solid #999; border-radius: 6px; background: white; }\n  "));
    let _ = head.append_child(&style_el);
}

pub struct Badge {
    heading: RefCell<String>,
    count: RefCell<i64>,
    root: RefCell<Option<HtmlElement>>,
}

impl Badge {
    pub fn new() -> Rc<Self> {
        Rc::new(Badge {
            heading: RefCell::new("".to_string()),
            count: RefCell::new(0i64),
            root: RefCell::new(None),
        })
    }

    pub fn mount(self: &Rc<Self>, selector: &str) -> Result<(), JsValue> {
        let document = web_sys::window().unwrap().document().unwrap();
        let root = document
            .query_selector(selector)?
            .ok_or_else(|| JsValue::from_str("mount: selector matched no element"))?
            .dyn_into::<HtmlElement>()?;
        self.mount_into(root)
    }

    pub fn mount_into(self: &Rc<Self>, root: HtmlElement) -> Result<(), JsValue> {
        __inject_style_Badge_badge_c_ae55b5a3();
        *self.root.borrow_mut() = Some(root);
        self.render();
        Ok(())
    }

    fn render(self: &Rc<Self>) {
        let root_ref = self.root.borrow();
        let root = match root_ref.as_ref() {
            Some(r) => r,
            None => return,
        };
        while let Some(child) = root.first_child() {
            let _ = root.remove_child(&child);
        }
        let document = web_sys::window().unwrap().document().unwrap();
        let __el0 = document.create_element("div").unwrap();
        __el0.set_attribute("class", "badge badge-badge-c-ae55b5a3").unwrap();
        let __el1 = document.create_element("div").unwrap();
        __el1.set_attribute("class", "heading heading-badge-c-ae55b5a3").unwrap();
        let __interp2 = format!("{}", (*self.heading.borrow()));
        let __t3 = document.create_text_node(&__interp2);
        __el1.append_child(&__t3).unwrap();
        __el0.append_child(&__el1).unwrap();
        let __el4 = document.create_element("div").unwrap();
        __el4.set_attribute("class", "count count-badge-c-ae55b5a3").unwrap();
        let __t5 = document.create_text_node("parent bumps + 1 = ");
        __el4.append_child(&__t5).unwrap();
        let __interp6 = format!("{}", (*self.count.borrow()));
        let __t7 = document.create_text_node(&__interp6);
        __el4.append_child(&__t7).unwrap();
        __el0.append_child(&__el4).unwrap();
        root.append_child(&__el0).unwrap();
    }
}

fn __inject_style_Badge_badge_c_ae55b5a3() {
    static INJECTED: AtomicBool = AtomicBool::new(false);
    if INJECTED.swap(true, Ordering::SeqCst) { return; }
    let document = web_sys::window().unwrap().document().unwrap();
    let head = document.head().unwrap();
    let style_el = document.create_element("style").unwrap();
    style_el.set_text_content(Some("\n    .badge-badge-c-ae55b5a3 { border: 1px solid #ddd; border-radius: 8px; padding: 16px; margin-top: 16px; background: #fafafa; }\n    .heading-badge-c-ae55b5a3 { font-size: 0.85em; text-transform: uppercase; letter-spacing: 0.05em; color: #666; }\n    .count-badge-c-ae55b5a3 { font-size: 1.6em; font-weight: bold; margin: 8px 0 0; }\n  "));
    let _ = head.append_child(&style_el);
}



// Composed entry point — NOT part of emit_module output.
// `fitz build --target wasm-client` (Phase 11.5.c) appends this
// wrapper so the bundle mounts the root component when the
// browser calls the `start` export.
#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    console_error_panic_hook::set_once();
    let root = App::new();
    root.mount("#app")?;
    Ok(())
}
