// docker.rs — Phase 12.4 (autogenerated Dockerfile + `fitz docker`)
//
// The `fitz docker init` sub-command produces three files in the
// manifest directory:
//   - `Dockerfile` multi-stage: builder with the official Fitz image
//     (`ghcr.io/thegreekman76/fitz:<tag>`) that invokes `fitz build`, +
//     runtime `gcr.io/distroless/cc-debian12` with just the binary.
//   - `.dockerignore` with the typical entries that must NOT enter the
//     build context.
//   - `docker-compose.yml` smart: if the program uses `db.connect(...)`,
//     adds a `postgres:16-alpine` service with healthcheck + DATABASE_URL.
//
// 12.4.a — MVP scope: AST-only detection of `@server(port)` and
// `db.connect(...)`. Multi-file only on the entry point (the smart
// compose does not recurse into imported modules — the typical case has
// the decorators in the main file).
//
// 12.4.b — future: bundled Python (fallback to debian:bookworm-slim),
// healthchecks via `@healthz/@readyz`, restart policies via `@cron`,
// `fitz docker build [--tag X]` wrapper.

use crate::ast::{Expr, Program, Stmt, StrPart};
use std::fs;
use std::path::{Path, PathBuf};

/// Snapshot of the program shape relevant for Docker.
///
/// `package_name` comes from `fitz.toml`; the rest is inferred by walking
/// the entry point's AST.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct DockerShape {
    pub package_name: String,
    /// `Some(port)` if it finds `@server(N, ...)` with `N` Int literal in
    /// `[1, 65535]`. `None` if there is no `@server` (CLI program) or if
    /// the port is a non-literal expression.
    pub server_port: Option<u16>,
    /// `true` if it finds any `db.X(...)` call in the AST (typically
    /// `db.connect(...)`). Generous heuristic: any method call with
    /// receiver `db` counts.
    pub uses_db: bool,
    /// 12.4.b — `true` if the program imports Python (`import python` or
    /// `from python import X`). The binary emitted by `fitz build` with
    /// interop needs libpython3.X.so at runtime; distroless does not
    /// ship it, so the Dockerfile falls back to `python:3.12-slim-bookworm`.
    pub uses_python: bool,
    /// 12.4.b — `true` if the program has at least one `@cron`. The
    /// compose adds `restart: unless-stopped` to the main service so the
    /// scheduler survives crashes/redeploys.
    pub uses_cron: bool,
}

/// Walks the program's AST and produces a `DockerShape` with everything
/// needed to parametrize the templates.
pub fn detect_shape(program: &Program, package_name: String) -> DockerShape {
    let server_port = find_server_port(program);
    let uses_db = program.iter().any(stmt_uses_db);
    let uses_python = program.iter().any(stmt_uses_python);
    // Phase 3c — @every is also a long-running periodic service; fold it into
    // uses_cron so the compose gets `restart: unless-stopped`.
    let uses_cron = program.iter().any(stmt_uses_cron) || program.iter().any(stmt_uses_every);
    DockerShape {
        package_name,
        server_port,
        uses_db,
        uses_python,
        uses_cron,
    }
}

fn stmt_uses_python(s: &Stmt) -> bool {
    match s {
        Stmt::Import { path, .. } | Stmt::FromImport { path, .. } => {
            path.first().is_some_and(|p| p == "python")
        }
        _ => false,
    }
}

fn stmt_uses_cron(s: &Stmt) -> bool {
    match s {
        Stmt::FnDef { decorators, .. } => decorators.iter().any(|d| d.name == "cron"),
        _ => false,
    }
}

fn stmt_uses_every(s: &Stmt) -> bool {
    match s {
        Stmt::FnDef { decorators, .. } => decorators.iter().any(|d| d.name == "every"),
        _ => false,
    }
}

fn find_server_port(program: &Program) -> Option<u16> {
    for stmt in program {
        if let Stmt::FnDef { decorators, .. } = stmt {
            for deco in decorators {
                if deco.name != "server" {
                    continue;
                }
                if let Some(Expr::Int(n, _)) = deco.args.first() {
                    if (1..=65535).contains(n) {
                        return Some(*n as u16);
                    }
                }
            }
        }
    }
    None
}

fn stmt_uses_db(s: &Stmt) -> bool {
    match s {
        Stmt::Expr(e, _) | Stmt::Return(e, _) => expr_uses_db(e),
        Stmt::Assign { value, .. } => expr_uses_db(value),
        Stmt::FnDef { body, .. } => body.iter().any(stmt_uses_db),
        Stmt::While {
            condition, body, ..
        } => expr_uses_db(condition) || body.iter().any(stmt_uses_db),
        Stmt::For { iter, body, .. } => expr_uses_db(iter) || body.iter().any(stmt_uses_db),
        _ => false,
    }
}

fn expr_uses_db(e: &Expr) -> bool {
    match e {
        Expr::Call { callee, args, .. } => {
            if let Expr::Field { object, .. } = callee.as_ref() {
                if let Expr::Ident(recv, _) = object.as_ref() {
                    if recv == "db" {
                        return true;
                    }
                }
            }
            expr_uses_db(callee) || args.iter().any(expr_uses_db)
        }
        Expr::Field { object, .. } => expr_uses_db(object),
        Expr::Index { object, index, .. } => expr_uses_db(object) || expr_uses_db(index),
        Expr::BinOp { left, right, .. } => expr_uses_db(left) || expr_uses_db(right),
        Expr::UnaryOp { operand, .. } => expr_uses_db(operand),
        Expr::Await(inner, _) | Expr::Try(inner, _) | Expr::Ok(inner, _) | Expr::Err(inner, _) => {
            expr_uses_db(inner)
        }
        Expr::FnExpr { body, .. } => body.iter().any(stmt_uses_db),
        Expr::If {
            condition,
            then,
            else_,
            ..
        } => {
            expr_uses_db(condition)
                || then.iter().any(stmt_uses_db)
                || else_.as_ref().is_some_and(|b| b.iter().any(stmt_uses_db))
        }
        Expr::Match { value, arms, .. } => {
            expr_uses_db(value) || arms.iter().any(|a| a.body.iter().any(stmt_uses_db))
        }
        Expr::StrInterp(parts, _) => parts.iter().any(|p| match p {
            StrPart::Lit(_) => false,
            StrPart::Expr(inner, _) => expr_uses_db(inner),
        }),
        _ => false,
    }
}

// ---------------------------------------------------------------------------
// Templates
// ---------------------------------------------------------------------------

/// Base image of the runtime stage. Distroless by default (~22 MB);
/// `python:3.12-slim-bookworm` when `uses_python` (libpython3.12 +
/// wget for healthcheck, ~55 MB).
fn runtime_image(shape: &DockerShape) -> &'static str {
    if shape.uses_python {
        "python:3.12-slim-bookworm"
    } else {
        "gcr.io/distroless/cc-debian12"
    }
}

/// Renders the multi-stage `Dockerfile`. The runtime is
/// `gcr.io/distroless/cc-debian12` by default; when the program uses
/// `from python import X`, it falls back to `python:3.12-slim-bookworm`
/// which already ships libpython3.12 + wget (needed for the HTTP
/// healthcheck emitted by compose). `EXPOSE` only when there is a
/// `@server(port)`.
pub fn render_dockerfile(shape: &DockerShape) -> String {
    let runtime = runtime_image(shape);
    let mut out = String::new();
    out.push_str("# Dockerfile generated by `fitz docker init` (Phase 12.4).\n");
    out.push_str("#\n");
    out.push_str("# Multi-stage:\n");
    out.push_str("#   Stage 1 (builder) — official Fitz image with `fitz` + Rust toolchain\n");
    out.push_str("#     pre-installed; compiles the `.fitz` source to a native Linux binary.\n");
    if shape.uses_python {
        out.push_str("#   Stage 2 (runtime) — `python:3.12-slim-bookworm`. Ships libpython3.12\n");
        out.push_str("#     (the binary emitted by `fitz build` with `from python import X`\n");
        out.push_str("#     dynamic-links to it) + wget for HTTP healthcheck. ~55 MB base.\n");
    } else {
        out.push_str(
            "#   Stage 2 (runtime) — `gcr.io/distroless/cc-debian12` minimal. Only glibc +\n",
        );
        out.push_str("#     libgcc + ca-certificates. No shell, no package manager.\n");
    }
    out.push_str("#\n");
    out.push_str("# Build:\n");
    out.push_str(&format!("#   docker build -t {} .\n", shape.package_name));
    if let Some(port) = shape.server_port {
        out.push_str("#\n");
        out.push_str(&format!(
            "# Run (HTTP):\n#   docker run --rm -p {0}:{0} {1}\n",
            port, shape.package_name,
        ));
    }
    out.push_str("#\n");
    out.push_str("# Pin the Fitz version for reproducibility:\n");
    out.push_str(&format!(
        "#   docker build --build-arg FITZ_TAG=v0.12.2 -t {} .\n",
        shape.package_name,
    ));
    out.push('\n');

    out.push_str("ARG FITZ_TAG=latest\n\n");

    out.push_str("# ---- Stage 1: builder ----------------------------------------------\n");
    out.push_str("FROM ghcr.io/thegreekman76/fitz:${FITZ_TAG} AS builder\n\n");
    out.push_str("WORKDIR /app\n");
    out.push_str("COPY fitz.toml ./\n");
    out.push_str("COPY src/ ./src/\n\n");
    out.push_str("# `fitz build` reads the manifest from cwd (Phase 9.y.2) and emits the\n");
    out.push_str("# binary to `target/release/<package.name>`.\n");
    if shape.uses_python {
        out.push_str("# `--features python` enables the opt-in PyO3 feature for Python\n");
        out.push_str("# interop (chapter 21 of the guide).\n");
        out.push_str("RUN fitz build\n\n");
    } else {
        out.push_str("RUN fitz build\n\n");
    }

    out.push_str("# ---- Stage 2: runtime ----------------------------------------------\n");
    out.push_str(&format!("FROM {}\n\n", runtime));
    out.push_str(&format!(
        "COPY --from=builder /app/target/release/{} /usr/local/bin/app\n\n",
        shape.package_name,
    ));

    if let Some(port) = shape.server_port {
        out.push_str(&format!(
            "# The program declares `@server({}, ...)`. So that `-p {0}:{0}` from the\n",
            port,
        ));
        out.push_str(
            "# host routes requests into the container, declare `@server(N, \"0.0.0.0\")`\n",
        );
        out.push_str("# in the Fitz source (bind to all interfaces).\n");
        out.push_str(&format!("EXPOSE {}\n\n", port));
    }

    out.push_str("ENTRYPOINT [\"/usr/local/bin/app\"]\n");

    out
}

/// `.dockerignore` with the typical entries that must NOT enter the
/// build context: compiler outputs, local configs, secrets, editor
/// files. Independent from the program shape.
pub fn render_dockerignore() -> String {
    let mut out = String::new();
    out.push_str("# Generated by `fitz docker init` (Phase 12.4).\n");
    out.push_str("# Files that must NOT enter the Dockerfile build context.\n\n");
    out.push_str("# Compiler outputs\n");
    out.push_str("target/\n");
    out.push_str(".fitz/\n");
    out.push_str("fitz.lock\n\n");
    out.push_str("# Git + local configs\n");
    out.push_str(".git/\n");
    out.push_str(".gitignore\n");
    out.push_str(".github/\n\n");
    out.push_str("# Local secrets / env\n");
    out.push_str(".env\n");
    out.push_str(".env.*\n");
    out.push_str("!.env.example\n\n");
    out.push_str("# Editor + OS\n");
    out.push_str(".vscode/\n");
    out.push_str(".idea/\n");
    out.push_str(".DS_Store\n");
    out.push_str("Thumbs.db\n\n");
    out.push_str("# Docker itself (no need to be in the build context)\n");
    out.push_str("Dockerfile\n");
    out.push_str("docker-compose.yml\n");
    out.push_str(".dockerignore\n\n");
    out.push_str("# Python (if the program uses interop)\n");
    out.push_str("__pycache__/\n");
    out.push_str("*.pyc\n");
    out.push_str(".venv/\n");
    out.push_str("venv/\n\n");
    out.push_str("# Boilerplate misc\n");
    out.push_str("node_modules/\n");
    out
}

/// Smart `docker-compose.yml`:
/// - If `uses_db`, adds a `db` service with `postgres:16-alpine` +
///   healthcheck and `DATABASE_URL` in the main service's env.
/// - If `server_port` is `Some`, maps that port. If `None`, no `ports:`
///   (CLI program inside a container).
/// - 12.4.b: if `uses_cron`, adds `restart: unless-stopped` to the main
///   service so the scheduler survives crashes/redeploys.
/// - 12.4.b: if there is HTTP (`server_port = Some`) AND the runtime
///   has wget available (`uses_python` → `python:3.12-slim-bookworm`),
///   adds an HTTP `healthcheck:` against `/healthz` (auto-mounted by
///   Phase 12.1.b). With distroless (no wget), the healthcheck is not
///   emitted and a comment is included explaining how to add it by hand.
pub fn render_compose(shape: &DockerShape) -> String {
    let mut out = String::new();
    out.push_str("# Generated by `fitz docker init` (Phase 12.4).\n");
    out.push_str("#\n");
    out.push_str("# Usage:\n");
    out.push_str("#   docker compose up --build\n");
    if shape.uses_db {
        out.push_str("#\n");
        out.push_str("# Postgres ships with default credentials fitz/fitz/fitz. Override them\n");
        out.push_str(
            "# with an adjacent `.env` (POSTGRES_USER / POSTGRES_PASSWORD / POSTGRES_DB).\n",
        );
    }
    if shape.uses_cron {
        out.push_str("#\n");
        out.push_str("# The program declares `@cron(...)` — `restart: unless-stopped` keeps the\n");
        out.push_str("# scheduler alive across crashes or redeploys.\n");
    }
    let emit_app_healthcheck = shape.server_port.is_some() && shape.uses_python;
    if shape.server_port.is_some() && !shape.uses_python {
        out.push_str("#\n");
        out.push_str(
            "# HTTP healthcheck NOT emitted — the distroless runtime does not ship wget/curl.\n",
        );
        out.push_str("# The `/healthz` endpoint is auto-mounted by the binary (Phase 12.1.b).\n");
        out.push_str("# If you want a healthcheck, switch the Dockerfile runtime to\n");
        out.push_str(
            "# `python:3.12-slim-bookworm` or `debian:bookworm-slim` with `apt-get install\n",
        );
        out.push_str("# wget` and add the healthcheck block with `wget --spider /healthz`.\n");
    }
    out.push_str("\nservices:\n");

    if shape.uses_db {
        out.push_str("  db:\n");
        out.push_str("    image: postgres:16-alpine\n");
        out.push_str(&format!("    container_name: {}-db\n", shape.package_name,));
        out.push_str("    environment:\n");
        out.push_str("      POSTGRES_USER: ${POSTGRES_USER:-fitz}\n");
        out.push_str("      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fitz}\n");
        out.push_str("      POSTGRES_DB: ${POSTGRES_DB:-fitz}\n");
        out.push_str("    volumes:\n");
        out.push_str("      - pgdata:/var/lib/postgresql/data\n");
        out.push_str("    healthcheck:\n");
        out.push_str(
            "      test: [\"CMD-SHELL\", \"pg_isready -U ${POSTGRES_USER:-fitz} -d ${POSTGRES_DB:-fitz}\"]\n",
        );
        out.push_str("      interval: 5s\n");
        out.push_str("      timeout: 5s\n");
        out.push_str("      retries: 5\n\n");
    }

    out.push_str("  app:\n");
    out.push_str("    build: .\n");
    out.push_str(&format!("    container_name: {}\n", shape.package_name));

    if shape.uses_db {
        out.push_str("    environment:\n");
        out.push_str(
            "      DATABASE_URL: \"postgres://${POSTGRES_USER:-fitz}:${POSTGRES_PASSWORD:-fitz}@db:5432/${POSTGRES_DB:-fitz}?sslmode=disable\"\n",
        );
    }

    if let Some(port) = shape.server_port {
        out.push_str("    ports:\n");
        out.push_str(&format!("      - \"{0}:{0}\"\n", port));
    }

    if shape.uses_cron {
        out.push_str("    restart: unless-stopped\n");
    }

    if emit_app_healthcheck {
        let port = shape.server_port.expect("checked above");
        out.push_str("    healthcheck:\n");
        out.push_str(&format!(
            "      test: [\"CMD\", \"wget\", \"--quiet\", \"--spider\", \"http://localhost:{}/healthz\"]\n",
            port,
        ));
        out.push_str("      interval: 30s\n");
        out.push_str("      timeout: 5s\n");
        out.push_str("      retries: 3\n");
        out.push_str("      start_period: 10s\n");
    }

    if shape.uses_db {
        out.push_str("    depends_on:\n");
        out.push_str("      db:\n");
        out.push_str("        condition: service_healthy\n");
    }

    if shape.uses_db {
        out.push_str("\nvolumes:\n");
        out.push_str("  pgdata:\n");
    }

    out
}

// ---------------------------------------------------------------------------
// Init — writes the 3 files
// ---------------------------------------------------------------------------

/// Result of `init`: what was written and what was skipped because it
/// already existed (and `force = true` was not passed).
#[derive(Debug, Clone, Default, PartialEq)]
pub struct InitResult {
    pub written: Vec<PathBuf>,
    pub skipped: Vec<PathBuf>,
}

/// Writes `Dockerfile` + `.dockerignore` + `docker-compose.yml` into
/// `target_dir`. If a file already exists and `force == false`, it is
/// skipped (recorded in `skipped`); if `force == true`, it is overwritten.
pub fn init(target_dir: &Path, shape: &DockerShape, force: bool) -> Result<InitResult, String> {
    if !target_dir.is_dir() {
        return Err(format!(
            "target directory does not exist or is not a directory: {}",
            target_dir.display(),
        ));
    }

    let mut result = InitResult::default();

    let files: Vec<(&str, String)> = vec![
        ("Dockerfile", render_dockerfile(shape)),
        (".dockerignore", render_dockerignore()),
        ("docker-compose.yml", render_compose(shape)),
    ];

    for (filename, contents) in files {
        let path = target_dir.join(filename);
        if path.exists() && !force {
            result.skipped.push(path);
            continue;
        }
        fs::write(&path, contents).map_err(|e| format!("escribiendo {}: {}", path.display(), e))?;
        result.written.push(path);
    }

    Ok(result)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{lexer, parser};
    use tempfile::tempdir;

    fn shape_from_source(source: &str, name: &str) -> DockerShape {
        let tokens = lexer::tokenize(source).expect("lex");
        let program = parser::parse(tokens).expect("parse");
        detect_shape(&program, name.to_string())
    }

    #[test]
    fn detect_shape_cli_only_without_server_without_db() {
        let shape = shape_from_source("print(\"hola\")", "demo");
        assert_eq!(shape.package_name, "demo");
        assert_eq!(shape.server_port, None);
        assert!(!shape.uses_db);
    }

    #[test]
    fn detect_shape_server_with_port_literal() {
        let src = r#"
@server(3000)
fn main() => 0

@get("/")
fn root() => "ok"
"#;
        let shape = shape_from_source(src, "demo");
        assert_eq!(shape.server_port, Some(3000));
        assert!(!shape.uses_db);
    }

    #[test]
    fn detect_shape_server_with_port_and_host() {
        let src = r#"
@server(8080, "0.0.0.0")
fn main() => 0
"#;
        let shape = shape_from_source(src, "demo");
        assert_eq!(shape.server_port, Some(8080));
    }

    #[test]
    fn detect_shape_server_without_port_defaults_to_none() {
        // `@server()` without valid args → no literal port detected; the
        // template uses the default logic (no EXPOSE / no ports).
        let src = r#"
@server()
fn main() => 0
"#;
        let shape = shape_from_source(src, "demo");
        assert_eq!(shape.server_port, None);
    }

    #[test]
    fn detect_shape_uses_db_connect() {
        let src = r#"
async fn main() -> Null {
    let conn = db.connect("postgres://x")
    print("ok")
}
"#;
        let shape = shape_from_source(src, "demo");
        assert!(shape.uses_db);
    }

    #[test]
    fn detect_shape_uses_db_query_chain() {
        // `db.X(...)` inside any expression counts.
        let src = r#"
async fn run() -> Null {
    let xs = db.query("select 1")
    print("ok")
}
"#;
        let shape = shape_from_source(src, "demo");
        assert!(shape.uses_db);
    }

    #[test]
    fn detect_shape_db_local_is_not_global() {
        // `db.X(...)` where `db` is a local ident: the heuristic still
        // marks it as `uses_db = true` (same as codegen). 12.4.a favors
        // simplicity over precision — the Docker helper is inference,
        // not static checking.
        let src = r#"
fn run(db) -> Int {
    let _ = db.query("x")
    0
}
"#;
        let shape = shape_from_source(src, "demo");
        assert!(shape.uses_db);
    }

    #[test]
    fn render_dockerfile_without_server_does_not_emit_expose() {
        let shape = DockerShape {
            package_name: "demo".into(),
            server_port: None,
            uses_db: false,
            ..Default::default()
        };
        let dockerfile = render_dockerfile(&shape);
        assert!(!dockerfile.contains("EXPOSE"));
        assert!(dockerfile.contains("FROM ghcr.io/thegreekman76/fitz:${FITZ_TAG} AS builder"));
        assert!(dockerfile.contains("FROM gcr.io/distroless/cc-debian12"));
        assert!(
            dockerfile.contains("COPY --from=builder /app/target/release/demo /usr/local/bin/app")
        );
        assert!(dockerfile.contains("ENTRYPOINT [\"/usr/local/bin/app\"]"));
    }

    #[test]
    fn render_dockerfile_with_server_emits_expose_and_port_runtime() {
        let shape = DockerShape {
            package_name: "myapp".into(),
            server_port: Some(8080),
            uses_db: false,
            ..Default::default()
        };
        let dockerfile = render_dockerfile(&shape);
        assert!(dockerfile.contains("EXPOSE 8080"));
        // Comment with the `docker run -p` example.
        assert!(dockerfile.contains("docker run --rm -p 8080:8080 myapp"));
    }

    #[test]
    fn render_dockerignore_excludes_target_env_and_git() {
        let dockerignore = render_dockerignore();
        assert!(dockerignore.contains("target/"));
        assert!(dockerignore.contains(".git/"));
        assert!(dockerignore.contains(".env"));
        assert!(dockerignore.contains("!.env.example"));
        assert!(dockerignore.contains("Dockerfile"));
        assert!(dockerignore.contains("__pycache__/"));
    }

    #[test]
    fn render_compose_without_db_without_server_only_app() {
        let shape = DockerShape {
            package_name: "cli".into(),
            server_port: None,
            uses_db: false,
            ..Default::default()
        };
        let compose = render_compose(&shape);
        assert!(compose.contains("services:"));
        assert!(compose.contains("  app:"));
        assert!(compose.contains("    build: ."));
        assert!(compose.contains("container_name: cli"));
        // No DB → no db service, no pgdata volume, no DATABASE_URL.
        assert!(!compose.contains("  db:"));
        assert!(!compose.contains("postgres:16-alpine"));
        assert!(!compose.contains("DATABASE_URL"));
        assert!(!compose.contains("volumes:"));
        // No server → no ports.
        assert!(!compose.contains("    ports:"));
    }

    #[test]
    fn render_compose_with_server_emits_ports() {
        let shape = DockerShape {
            package_name: "web".into(),
            server_port: Some(3000),
            uses_db: false,
            ..Default::default()
        };
        let compose = render_compose(&shape);
        assert!(compose.contains("    ports:\n      - \"3000:3000\""));
    }

    #[test]
    fn render_compose_with_db_emits_postgres_and_database_url() {
        let shape = DockerShape {
            package_name: "api".into(),
            server_port: Some(3000),
            uses_db: true,
            ..Default::default()
        };
        let compose = render_compose(&shape);
        assert!(compose.contains("  db:"));
        assert!(compose.contains("image: postgres:16-alpine"));
        assert!(compose.contains("container_name: api-db"));
        assert!(compose.contains("pg_isready"));
        assert!(compose.contains("healthcheck:"));
        assert!(compose.contains("DATABASE_URL:"));
        assert!(compose.contains("postgres://${POSTGRES_USER:-fitz}"));
        assert!(compose.contains("@db:5432"));
        assert!(compose.contains("depends_on:"));
        assert!(compose.contains("service_healthy"));
        assert!(compose.contains("\nvolumes:\n  pgdata:"));
    }

    #[test]
    fn render_compose_with_db_without_server_does_not_emit_ports() {
        let shape = DockerShape {
            package_name: "worker".into(),
            server_port: None,
            uses_db: true,
            ..Default::default()
        };
        let compose = render_compose(&shape);
        assert!(compose.contains("  db:"));
        assert!(!compose.contains("    ports:"));
    }

    #[test]
    fn init_writes_three_files_in_empty_dir() {
        let dir = tempdir().expect("tempdir");
        let shape = DockerShape {
            package_name: "demo".into(),
            server_port: Some(3000),
            uses_db: false,
            ..Default::default()
        };
        let result = init(dir.path(), &shape, false).expect("init ok");
        assert_eq!(result.written.len(), 3);
        assert!(result.skipped.is_empty());
        assert!(dir.path().join("Dockerfile").exists());
        assert!(dir.path().join(".dockerignore").exists());
        assert!(dir.path().join("docker-compose.yml").exists());
    }

    #[test]
    fn init_skips_existing_files_without_force() {
        let dir = tempdir().expect("tempdir");
        fs::write(dir.path().join("Dockerfile"), "viejo contenido").unwrap();
        let shape = DockerShape {
            package_name: "demo".into(),
            server_port: None,
            uses_db: false,
            ..Default::default()
        };
        let result = init(dir.path(), &shape, false).expect("init ok");
        assert_eq!(result.written.len(), 2);
        assert_eq!(result.skipped.len(), 1);
        assert_eq!(
            result.skipped[0].file_name().and_then(|s| s.to_str()),
            Some("Dockerfile"),
        );
        // And the old file is preserved.
        let viejo = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert_eq!(viejo, "viejo contenido");
    }

    #[test]
    fn init_force_overwrites_existing_files() {
        let dir = tempdir().expect("tempdir");
        fs::write(dir.path().join(".dockerignore"), "viejo").unwrap();
        let shape = DockerShape {
            package_name: "demo".into(),
            server_port: None,
            uses_db: false,
            ..Default::default()
        };
        let result = init(dir.path(), &shape, true).expect("init ok");
        assert_eq!(result.written.len(), 3);
        assert!(result.skipped.is_empty());
        let nuevo = fs::read_to_string(dir.path().join(".dockerignore")).unwrap();
        assert!(nuevo.contains("target/"));
    }

    #[test]
    fn init_error_if_target_dir_does_not_exist() {
        let shape = DockerShape {
            package_name: "demo".into(),
            server_port: None,
            uses_db: false,
            ..Default::default()
        };
        let result = init(Path::new("/no/existe/aca"), &shape, false);
        assert!(result.is_err());
    }

    // ---- 12.4.b — uses_python / uses_cron / conditional healthcheck ----

    #[test]
    fn detect_shape_uses_python_with_from_import() {
        let src = r#"
from python import math

fn area(r: Float) -> Float => math.pi * r * r
"#;
        let shape = shape_from_source(src, "demo");
        assert!(shape.uses_python);
        assert!(!shape.uses_cron);
    }

    #[test]
    fn detect_shape_uses_python_with_direct_import() {
        let src = r#"
import python
"#;
        let shape = shape_from_source(src, "demo");
        assert!(shape.uses_python);
    }

    #[test]
    fn detect_shape_without_python_does_not_trigger_uses_python() {
        let src = r#"
import utils
from helpers import double
"#;
        // Imports to other modules are not Python interop.
        let shape = shape_from_source(src, "demo");
        assert!(!shape.uses_python);
    }

    #[test]
    fn detect_shape_uses_cron_with_decorator() {
        let src = r#"
@cron("0 * * * *")
fn limpiar() => 0
"#;
        let shape = shape_from_source(src, "demo");
        assert!(shape.uses_cron);
    }

    #[test]
    fn detect_shape_without_cron_does_not_trigger_uses_cron() {
        let src = r#"
@get("/")
fn root() => "ok"

@server(3000)
fn main() => 0
"#;
        let shape = shape_from_source(src, "demo");
        assert!(!shape.uses_cron);
    }

    #[test]
    fn render_dockerfile_with_python_runtime_is_slim_bookworm() {
        let shape = DockerShape {
            package_name: "demo".into(),
            server_port: Some(3000),
            uses_python: true,
            ..Default::default()
        };
        let dockerfile = render_dockerfile(&shape);
        assert!(dockerfile.contains("FROM python:3.12-slim-bookworm"));
        assert!(!dockerfile.contains("FROM gcr.io/distroless/cc-debian12"));
        // Comment explaining why the runtime is different.
        assert!(dockerfile.contains("libpython3.12"));
    }

    #[test]
    fn render_dockerfile_without_python_runtime_is_distroless() {
        let shape = DockerShape {
            package_name: "demo".into(),
            server_port: Some(3000),
            uses_python: false,
            ..Default::default()
        };
        let dockerfile = render_dockerfile(&shape);
        assert!(dockerfile.contains("FROM gcr.io/distroless/cc-debian12"));
        assert!(!dockerfile.contains("python:3.12-slim-bookworm"));
    }

    #[test]
    fn render_compose_with_cron_emits_restart_unless_stopped() {
        let shape = DockerShape {
            package_name: "scheduler".into(),
            server_port: None,
            uses_cron: true,
            ..Default::default()
        };
        let compose = render_compose(&shape);
        assert!(compose.contains("    restart: unless-stopped"));
        // Comment explaining why.
        assert!(compose.contains("@cron"));
    }

    #[test]
    fn render_compose_without_cron_does_not_emit_restart() {
        let shape = DockerShape {
            package_name: "cli".into(),
            server_port: None,
            uses_cron: false,
            ..Default::default()
        };
        let compose = render_compose(&shape);
        assert!(!compose.contains("restart: unless-stopped"));
    }

    #[test]
    fn render_compose_with_python_and_server_emits_healthcheck_http() {
        let shape = DockerShape {
            package_name: "api-py".into(),
            server_port: Some(3000),
            uses_python: true,
            ..Default::default()
        };
        let compose = render_compose(&shape);
        assert!(compose.contains("    healthcheck:"));
        assert!(compose.contains("wget"));
        assert!(compose.contains("--spider"));
        assert!(compose.contains("http://localhost:3000/healthz"));
        assert!(compose.contains("start_period: 10s"));
    }

    #[test]
    fn render_compose_with_distroless_does_not_emit_healthcheck_http() {
        // Without uses_python, the runtime is distroless (no wget) — we
        // cannot emit a shell-based healthcheck. A comment explaining how
        // to add it by hand is included instead.
        let shape = DockerShape {
            package_name: "api".into(),
            server_port: Some(3000),
            uses_python: false,
            ..Default::default()
        };
        let compose = render_compose(&shape);
        // No healthcheck inside the app service.
        // (The "healthcheck:" of the db service does stay if uses_db=true,
        // that's why we check the app-specific block — the top-level
        // comment explains why.)
        assert!(compose.contains("HTTP healthcheck NOT emitted"));
        assert!(compose.contains("/healthz"));
    }

    #[test]
    fn render_compose_cli_only_does_not_emit_healthcheck_nor_comment() {
        // Without server_port there is no HTTP request to check. Neither
        // healthcheck nor explanatory comment.
        let shape = DockerShape {
            package_name: "cli".into(),
            server_port: None,
            uses_python: false,
            ..Default::default()
        };
        let compose = render_compose(&shape);
        assert!(!compose.contains("healthcheck:"));
        assert!(!compose.contains("Healthcheck HTTP NO emitido"));
    }

    #[test]
    fn render_compose_complete_combination() {
        // HTTP + DB + cron + python: all the smart bits enabled.
        let shape = DockerShape {
            package_name: "fullstack".into(),
            server_port: Some(8080),
            uses_db: true,
            uses_python: true,
            uses_cron: true,
        };
        let compose = render_compose(&shape);
        assert!(compose.contains("  db:"));
        assert!(compose.contains("    restart: unless-stopped"));
        assert!(compose.contains("    healthcheck:"));
        assert!(compose.contains("http://localhost:8080/healthz"));
        assert!(compose.contains("DATABASE_URL"));
        assert!(compose.contains("depends_on:"));
    }
}
