//! Launcher template for `fitz build --bundle-python` (Phase 8.b.3).
//!
//! When `--bundle-python` is active, the output of `fitz build` is a
//! standalone Rust binary ("launcher") that internally embeds:
//!  - The PBS tarball (CPython 3.13.x install_only_stripped)
//!  - The "real binary" (standard transpile of the Fitz program with
//!    the `python` feature, links libpython as today)
//!
//! On the first run, the launcher extracts everything to
//! `$TMPDIR/fitz-py-<hash>/`, sets `PYTHONHOME` +
//! `LD_LIBRARY_PATH`/`DYLD_FALLBACK_LIBRARY_PATH`/`PATH` depending on
//! the OS, and exec/spawn-and-wait of the real binary. Subsequent runs
//! reuse the extracted dir (the `.extracted` sentinel marks completion).
//!
//! **Timing observed on Windows 11 SSD** (CPython 3.14.5 install_only_stripped,
//! 21 MB compressed → 61 MB extracted, native bsdtar):
//!  - Cold first run (empty TMP cache): ~3-5s (tar extraction +
//!    CPython boot inside the real binary).
//!  - Warm subsequent runs: ~50-100ms (cache hit, `.extracted` sentinel
//!    present, only exec/spawn of the real binary).
//!
//! **Pattern validated in production**: Datasette Desktop (Simon
//! Willison, 2021) ships this way with bsdtar + PBS. It is the model
//! recommended by the 2026-05-23 research after discarding:
//!  - "Extract on first run + set PYTHONHOME in main()": does not
//!    work, the OS resolves libpython BEFORE main() (Linux: `DT_NEEDED`
//!    via ld.so; macOS: `LC_LOAD_DYLIB` via dyld; Windows: import
//!    table).
//!  - Static linking with "full" PBS: "multi-month rabbit hole",
//!    PyOxidizer slowed down since 2024.
//!  - Manual delay-load/dlopen: no documented support in PyO3,
//!    brittle across versions.
//!
//! **Technical decisions made**:
//!
//! - **`tar -xzf` subprocess**: zero Rust deps in the launcher.
//!   bsdtar/GNU tar available natively on Windows 11
//!   (`C:\WINDOWS\system32\tar.exe`), macOS, and all modern Linux.
//! - **`__FITZ_REPLACE_*__` placeholders**: valid Rust string
//!   literals. If the template is not substituted (codegen bug),
//!   `include_bytes!` fails with "no such file" — good error signal
//!   at build time, not runtime.
//! - **`exec` on Unix vs `Command::status` on Windows**: on Unix
//!   `execv` replaces the process (transparent signals/stdin/stdout,
//!   the OS forwards everything). On Windows there is no real exec;
//!   we use `Command::status` with inherit handles + propagate the
//!   exit code.
//! - **`.extracted` sentinel**: the last thing we write. If we crash
//!   during extract, the sentinel does not exist and the next run
//!   re-extracts (no persistent corruption).
//! - **Atomic rename**: we extract to `<base>.tmp` + `fs::rename` to
//!   `<base>`. If another concurrent run beat us (race), the second
//!   rename fails and we discard our tmp — the result of the first
//!   one is the same because the tarball is deterministic.
//! - **TARBALL_HASH as string**: computed by `fitz build` (SHA256
//!   truncated to 16 chars) and embedded. Tarball change = hash
//!   change = new extract dir (automatic cache per version).

/// Placeholder replaced by codegen with the absolute path to the PBS
/// tarball (resolved via `pbs::ensure_tarball(triple)?`).
pub const PLACEHOLDER_TARBALL_PATH: &str = "__FITZ_REPLACE_PBS_TARBALL_PATH__";

/// Placeholder replaced with the absolute path to the real binary
/// (just built by the codegen of sub-step 8.b.2).
pub const PLACEHOLDER_REAL_BINARY_PATH: &str = "__FITZ_REPLACE_REAL_BINARY_PATH__";

/// Placeholder replaced with a short hash of the tarball (16 hex
/// chars). Identifies the extract dir in `$TMPDIR`. When there are
/// pip packages, this hash combines PBS + pip so that two projects
/// with different packages have different extract dirs.
pub const PLACEHOLDER_TARBALL_HASH: &str = "__FITZ_REPLACE_TARBALL_HASH__";

/// Placeholder where the pip-packages tarball declaration is injected
/// (Phase 8.c). Without `--bundle-pip` it stays as an empty string.
/// With `--bundle-pip`, it is replaced with an extra line:
/// `const PIP_PACKAGES: &[u8] = include_bytes!("<path>");`
pub const PLACEHOLDER_PIP_DECL_BLOCK: &str = "__FITZ_REPLACE_PIP_DECL_BLOCK__";

/// Placeholder where the extraction of pip packages into
/// `python/Lib/site-packages/` is injected. Without `--bundle-pip` it
/// stays empty. With `--bundle-pip`, the extraction block is injected.
pub const PLACEHOLDER_PIP_EXTRACT_BLOCK: &str = "__FITZ_REPLACE_PIP_EXTRACT_BLOCK__";

/// Rust template of the launcher's `main.rs`. The placeholders are
/// replaced via `gen_launcher_main_rs()` before writing it to the
/// launcher's Cargo project.
pub const LAUNCHER_MAIN_RS_TEMPLATE: &str = r#"// Auto-generated by `fitz build --bundle-python`.
// DO NOT edit — regenerated on every build.
//
// Launcher: extracts the embedded CPython + real binary into $TMPDIR on
// the first run, sets env vars (PYTHONHOME + LD_LIBRARY_PATH/DYLD/PATH),
// and execs the real binary. Subsequent runs are instant (TMP cache).

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{exit, Command};

/// v0.9.46 — In-memory tar.gz extraction without invoking a system
/// subprocess. Enables minimal runtimes like distroless
/// (`gcr.io/distroless/cc-debian12` ~22 MB base) that do NOT ship
/// shell utilities. Pre-fix, extraction used a subprocess and the
/// minimum viable runtime was `debian:bookworm-slim` (~85 MB base).
/// `tar` + `flate2` crates add ~80-100 KB to the final launcher binary
/// (LTO + strip are enabled in release).
fn extract_tar_gz(tarball_path: &Path, dest: &Path) -> std::io::Result<()> {
    let f = fs::File::open(tarball_path)?;
    let gz = flate2::read::GzDecoder::new(f);
    let mut archive = tar::Archive::new(gz);
    // `unpack` validates paths: rejects absolute paths and `../` that
    // would escape `dest` (CVE protection from the `tar` crate). PBS
    // and pip tarballs are trusted (generated by `fitz build`), but
    // the defensive check does not hurt.
    archive.unpack(dest)?;
    Ok(())
}

const PBS_TARBALL: &[u8] = include_bytes!("__FITZ_REPLACE_PBS_TARBALL_PATH__");
const REAL_BINARY: &[u8] = include_bytes!("__FITZ_REPLACE_REAL_BINARY_PATH__");
const TARBALL_HASH: &str = "__FITZ_REPLACE_TARBALL_HASH__";
__FITZ_REPLACE_PIP_DECL_BLOCK__

#[cfg(windows)]
const REAL_BINARY_NAME: &str = "fitz-real.exe";
#[cfg(not(windows))]
const REAL_BINARY_NAME: &str = "fitz-real";

fn main() {
    let extracted = ensure_extracted()
        .unwrap_or_else(|e| die(&format!("failed to extract bundled Python: {e}")));

    let real_binary = extracted.join(REAL_BINARY_NAME);
    let python_home = extracted.join("python");

    env::set_var("PYTHONHOME", &python_home);

    #[cfg(target_os = "linux")]
    prepend_path_env("LD_LIBRARY_PATH", &python_home.join("lib"));
    #[cfg(target_os = "macos")]
    prepend_path_env("DYLD_FALLBACK_LIBRARY_PATH", &python_home.join("lib"));
    #[cfg(windows)]
    prepend_path_env("PATH", &python_home);

    let args: Vec<String> = env::args().skip(1).collect();

    #[cfg(unix)]
    {
        use std::os::unix::process::CommandExt;
        let err = Command::new(&real_binary).args(&args).exec();
        die(&format!("exec failed: {err}"));
    }

    #[cfg(windows)]
    {
        let status = Command::new(&real_binary)
            .args(&args)
            .status()
            .unwrap_or_else(|e| die(&format!("spawn failed: {e}")));
        exit(status.code().unwrap_or(127));
    }
}

fn die(msg: &str) -> ! {
    eprintln!("fitz: {msg}");
    exit(127);
}

fn ensure_extracted() -> std::io::Result<PathBuf> {
    let base = env::temp_dir().join(format!("fitz-py-{}", TARBALL_HASH));
    let sentinel = base.join(".extracted");

    if sentinel.exists() {
        return Ok(base);
    }

    let tmp = base.with_extension("tmp");
    if tmp.exists() {
        fs::remove_dir_all(&tmp)?;
    }
    fs::create_dir_all(&tmp)?;

    let tarball_path = tmp.join("__fitz_pbs.tar.gz");
    fs::write(&tarball_path, PBS_TARBALL)?;

    // v0.9.46 — extract via crates `tar` + `flate2` inline (sin
    // subprocess `tar`). Habilita runtimes minimalistas estilo
    // distroless que NO traen `tar` ni shell.
    extract_tar_gz(&tarball_path, &tmp).map_err(|e| {
        std::io::Error::new(
            std::io::ErrorKind::Other,
            format!("PBS tar extraction failed: {e}"),
        )
    })?;

    let _ = fs::remove_file(&tarball_path);
__FITZ_REPLACE_PIP_EXTRACT_BLOCK__

    let real_binary_dest = tmp.join(REAL_BINARY_NAME);
    fs::write(&real_binary_dest, REAL_BINARY)?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&real_binary_dest)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&real_binary_dest, perms)?;
    }

    fs::write(tmp.join(".extracted"), b"")?;

    if base.exists() {
        let _ = fs::remove_dir_all(&tmp);
    } else if let Err(e) = fs::rename(&tmp, &base) {
        let _ = fs::remove_dir_all(&tmp);
        if !base.exists() {
            return Err(e);
        }
    }

    Ok(base)
}

fn prepend_path_env(name: &str, dir: &Path) {
    #[cfg(windows)]
    const SEP: &str = ";";
    #[cfg(not(windows))]
    const SEP: &str = ":";

    let new = match env::var(name) {
        Ok(existing) if !existing.is_empty() => {
            format!("{}{}{}", dir.display(), SEP, existing)
        }
        _ => dir.display().to_string(),
    };
    env::set_var(name, new);
}
"#;

/// The launcher's Cargo.toml. Zero external deps — std only. The
/// package name is `__fitz_launcher__` (placeholder) to avoid a
/// collision with the real binary (which uses the sanitized package
/// name from the `.fitz` source).
pub const LAUNCHER_CARGO_TOML_TEMPLATE: &str = r#"[package]
name = "fitz_launcher"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "__FITZ_REPLACE_BIN_NAME__"
path = "src/main.rs"

# v0.9.46 — Deps para extraer tar.gz embebido sin subprocess `tar`.
# Habilita `gcr.io/distroless/cc-debian12` como runtime (~22 MB base
# vs ~85 MB de `debian:bookworm-slim` que era requisito por la
# dependencia de `tar` nativo). Costo: ~80-100 KB sumados al binario
# final del launcher con LTO + strip activos.
[dependencies]
tar = "0.4"
flate2 = "1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
"#;

/// Placeholder in `LAUNCHER_CARGO_TOML_TEMPLATE` for the final
/// binary name (sanitized from the stem of the original `.fitz`).
pub const PLACEHOLDER_BIN_NAME: &str = "__FITZ_REPLACE_BIN_NAME__";

/// Customizes the launcher's `main.rs` template with real paths and
/// the tarball hash. Returns the Rust code ready to write to the
/// launcher's Cargo project.
///
/// Paths are escaped to be valid Rust string literals (Windows
/// backslashes → `\\`, double quotes → `\"`).
///
/// Phase 8.c — If `pip_packages_path` is `Some(<path>)`, the launcher
/// embeds a second tarball with pre-installed pip packages and
/// extracts them into `python/Lib/site-packages/` after the base PBS
/// extract. If `None` (without `--bundle-pip`), the pip blocks are
/// replaced with empty strings — the resulting launcher is
/// bit-by-bit identical to 8.b.
pub fn gen_launcher_main_rs(
    tarball_path: &str,
    real_binary_path: &str,
    tarball_hash: &str,
    pip_packages_path: Option<&str>,
) -> String {
    let (pip_decl_block, pip_extract_block) = match pip_packages_path {
        Some(path) => (
            format!(
                "const PIP_PACKAGES: &[u8] = include_bytes!(\"{}\");",
                escape_rust_string_literal(path)
            ),
            // Block emitted after `let _ = fs::remove_file(&tarball_path);`.
            // Writes the pip tarball to a temp .tar.gz + extracts it to
            // python/Lib/site-packages/. Assumes `python/` already exists
            // after the base PBS extraction. strip-components=0 preserves
            // the tarball's relative hierarchy (it must contain the
            // package dirs directly).
            r#"
    // Phase 8.c — extraction of embedded pip packages.
    let pip_tarball_path = tmp.join("__fitz_pip.tar.gz");
    fs::write(&pip_tarball_path, PIP_PACKAGES)?;

    let site_packages = tmp.join("python").join("Lib").join("site-packages");
    if !site_packages.exists() {
        // Linux/macOS: the dir lives at python/lib/python3.X/site-packages/.
        // Look for any python3* dir inside python/lib/.
        let py_lib = tmp.join("python").join("lib");
        if py_lib.exists() {
            for entry in fs::read_dir(&py_lib)? {
                let entry = entry?;
                let name = entry.file_name();
                let name_str = name.to_string_lossy();
                if name_str.starts_with("python3") {
                    let sp = entry.path().join("site-packages");
                    if !sp.exists() {
                        fs::create_dir_all(&sp)?;
                    }
                    // v0.9.46 — extract via tar+flate2 inline (sin subprocess).
                    extract_tar_gz(&pip_tarball_path, &sp).map_err(|e| {
                        std::io::Error::new(
                            std::io::ErrorKind::Other,
                            format!("pip packages tar extraction failed: {e}"),
                        )
                    })?;
                    break;
                }
            }
        }
    } else {
        // Windows: python/Lib/site-packages/ ya existe en el PBS.
        // v0.9.46 — extract via tar+flate2 inline (sin subprocess).
        extract_tar_gz(&pip_tarball_path, &site_packages).map_err(|e| {
            std::io::Error::new(
                std::io::ErrorKind::Other,
                format!("pip packages tar extraction failed: {e}"),
            )
        })?;
    }
    let _ = fs::remove_file(&pip_tarball_path);"#
                .to_string(),
        ),
        None => (String::new(), String::new()),
    };

    LAUNCHER_MAIN_RS_TEMPLATE
        .replace(
            PLACEHOLDER_TARBALL_PATH,
            &escape_rust_string_literal(tarball_path),
        )
        .replace(
            PLACEHOLDER_REAL_BINARY_PATH,
            &escape_rust_string_literal(real_binary_path),
        )
        .replace(
            PLACEHOLDER_TARBALL_HASH,
            &escape_rust_string_literal(tarball_hash),
        )
        .replace(PLACEHOLDER_PIP_DECL_BLOCK, &pip_decl_block)
        .replace(PLACEHOLDER_PIP_EXTRACT_BLOCK, &pip_extract_block)
}

/// Customizes the launcher's Cargo.toml template with the final
/// binary name.
pub fn gen_launcher_cargo_toml(bin_name: &str) -> String {
    LAUNCHER_CARGO_TOML_TEMPLATE.replace(PLACEHOLDER_BIN_NAME, bin_name)
}

/// Escapes a string so it is a valid Rust string literal. Handles
/// backslash (Windows paths), double quote, and newlines.
fn escape_rust_string_literal(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
}

/// Computes a deterministic short hash (16 hex chars) of the PBS
/// tarball. Uses a simple 64-bit FNV-1a implementation — it does not
/// need to be cryptographic, just uniquely identify the tarball
/// contents for the dir name in `$TMPDIR`.
///
/// FNV-1a is enough because:
///  - The input is a known PBS tarball (no adversarial attacker).
///  - Accidental collision between two different PBS tarballs is
///    astronomically improbable.
///  - Zero deps: 8-LoC implementation.
pub fn tarball_hash_short(tarball_bytes: &[u8]) -> String {
    const FNV_OFFSET: u64 = 0xcbf2_9ce4_8422_2325;
    const FNV_PRIME: u64 = 0x100_0000_01b3;
    let mut hash: u64 = FNV_OFFSET;
    for b in tarball_bytes {
        hash ^= *b as u64;
        hash = hash.wrapping_mul(FNV_PRIME);
    }
    format!("{:016x}", hash)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn placeholders_are_valid_rust_strings() {
        // The placeholders must be identifiers between double quotes,
        // valid as Rust string literals.
        assert!(PLACEHOLDER_TARBALL_PATH.starts_with("__FITZ_REPLACE_"));
        assert!(PLACEHOLDER_REAL_BINARY_PATH.starts_with("__FITZ_REPLACE_"));
        assert!(PLACEHOLDER_TARBALL_HASH.starts_with("__FITZ_REPLACE_"));
        assert!(PLACEHOLDER_BIN_NAME.starts_with("__FITZ_REPLACE_"));
    }

    #[test]
    fn template_main_rs_contains_the_3_placeholders() {
        assert!(LAUNCHER_MAIN_RS_TEMPLATE.contains(PLACEHOLDER_TARBALL_PATH));
        assert!(LAUNCHER_MAIN_RS_TEMPLATE.contains(PLACEHOLDER_REAL_BINARY_PATH));
        assert!(LAUNCHER_MAIN_RS_TEMPLATE.contains(PLACEHOLDER_TARBALL_HASH));
    }

    #[test]
    fn template_cargo_toml_contains_bin_name_placeholder() {
        assert!(LAUNCHER_CARGO_TOML_TEMPLATE.contains(PLACEHOLDER_BIN_NAME));
    }

    // ---- v0.9.46 distroless-tar-embedded ----

    #[test]
    fn template_cargo_toml_includes_deps_tar_and_flate2() {
        // The launcher needs `tar` + `flate2` to extract the PBS
        // (and optionally the pip tarball) without invoking the
        // system's `tar` binary. Enables distroless minimal runtimes.
        assert!(
            LAUNCHER_CARGO_TOML_TEMPLATE.contains("tar = \"0.4\""),
            "launcher Cargo.toml must declare `tar = \"0.4\"`"
        );
        assert!(
            LAUNCHER_CARGO_TOML_TEMPLATE.contains("flate2 = \"1\""),
            "launcher Cargo.toml must declare `flate2 = \"1\"`"
        );
    }

    #[test]
    fn template_main_rs_defines_extract_tar_gz_and_does_not_invoke_tar_subprocess() {
        // The helper must exist.
        assert!(
            LAUNCHER_MAIN_RS_TEMPLATE.contains("fn extract_tar_gz"),
            "template must define `fn extract_tar_gz`"
        );
        // And no `Command::new("tar")` must remain — that was the
        // pre-fix pattern that broke on distroless.
        assert!(
            !LAUNCHER_MAIN_RS_TEMPLATE.contains("Command::new(\"tar\")"),
            "template must NOT invoke `Command::new(\"tar\")` (subprocess would fail in distroless)"
        );
    }

    #[test]
    fn gen_launcher_main_rs_pip_block_uses_extract_tar_gz() {
        // When pip is embedded, the injected block must use the
        // native Rust helper, not a subprocess.
        let result = gen_launcher_main_rs(
            "/tmp/pbs.tar.gz",
            "/tmp/fitz-real",
            "abc123",
            Some("/tmp/pip_packages.tar.gz"),
        );
        assert!(
            result.contains("extract_tar_gz(&pip_tarball_path"),
            "pip block must invoke `extract_tar_gz` to extract the pip tarball"
        );
        assert!(
            !result.contains("Command::new(\"tar\")"),
            "pip block must NOT invoke `Command::new(\"tar\")`"
        );
    }

    #[test]
    fn gen_launcher_main_rs_substitutes_the_3_placeholders() {
        let result = gen_launcher_main_rs("/tmp/tarball.tar.gz", "/tmp/fitz-real", "abc123", None);

        // The placeholders must no longer appear in the output.
        assert!(!result.contains(PLACEHOLDER_TARBALL_PATH));
        assert!(!result.contains(PLACEHOLDER_REAL_BINARY_PATH));
        assert!(!result.contains(PLACEHOLDER_TARBALL_HASH));
        // Without pip, the pip blocks must also be replaced (with empty).
        assert!(!result.contains(PLACEHOLDER_PIP_DECL_BLOCK));
        assert!(!result.contains(PLACEHOLDER_PIP_EXTRACT_BLOCK));

        // The replaced values must appear.
        assert!(result.contains("/tmp/tarball.tar.gz"));
        assert!(result.contains("/tmp/fitz-real"));
        assert!(result.contains("abc123"));

        // Without pip, there must be NO reference to PIP_PACKAGES in the output.
        assert!(!result.contains("PIP_PACKAGES"));
    }

    #[test]
    fn gen_launcher_main_rs_escapes_windows_backslashes() {
        let result = gen_launcher_main_rs(
            r"C:\Users\test\tarball.tar.gz",
            r"C:\Users\test\fitz-real.exe",
            "abc123",
            None,
        );

        // In the Rust source, backslashes must appear escaped.
        assert!(
            result.contains(r"C:\\Users\\test\\tarball.tar.gz"),
            "the Windows path should have backslashes escaped"
        );
        assert!(result.contains(r"C:\\Users\\test\\fitz-real.exe"));

        // Raw backslashes must NOT appear in the include_bytes!
        // (a Rust string literal with raw `\` is illegal outside raw strings).
        let include_bytes_line = result
            .lines()
            .find(|l| l.contains("PBS_TARBALL: &[u8]"))
            .expect("there should be an include_bytes! line for the tarball");
        assert!(!include_bytes_line.contains(r"C:\Users"));
        assert!(include_bytes_line.contains(r"C:\\Users"));
    }

    #[test]
    fn gen_launcher_main_rs_escapes_double_quotes() {
        // Improbable but possible edge case (paths with spaces and
        // quotes on Windows — not typical but valid).
        let result = gen_launcher_main_rs("/tmp/a\"b.tar.gz", "/tmp/real", "h", None);
        assert!(result.contains("/tmp/a\\\"b.tar.gz"));
    }

    #[test]
    fn gen_launcher_main_rs_with_pip_packages_injects_blocks() {
        let result = gen_launcher_main_rs(
            "/tmp/pbs.tar.gz",
            "/tmp/fitz-real",
            "abc123",
            Some("/tmp/pip_packages.tar.gz"),
        );

        // Placeholders must be resolved.
        assert!(!result.contains(PLACEHOLDER_PIP_DECL_BLOCK));
        assert!(!result.contains(PLACEHOLDER_PIP_EXTRACT_BLOCK));

        // Declaration block: const PIP_PACKAGES + include_bytes!.
        assert!(
            result.contains("const PIP_PACKAGES: &[u8] = include_bytes!"),
            "must declare PIP_PACKAGES as include_bytes!"
        );
        assert!(
            result.contains("/tmp/pip_packages.tar.gz"),
            "must include the path of the pip tarball"
        );

        // Extraction block: writes + tar.
        assert!(
            result.contains("__fitz_pip.tar.gz"),
            "must write the pip tarball to a temp file"
        );
        assert!(
            result.contains("site-packages"),
            "must mention the target site-packages for extraction"
        );
    }

    #[test]
    fn gen_launcher_main_rs_pip_packages_escapes_windows_path() {
        let result = gen_launcher_main_rs(
            "/tmp/pbs.tar.gz",
            "/tmp/fitz-real",
            "abc123",
            Some(r"C:\Users\test\pip_packages.tar.gz"),
        );

        // The Windows pip path must be escaped inside include_bytes!.
        assert!(result.contains(r"C:\\Users\\test\\pip_packages.tar.gz"));
        // A raw backslash must NOT appear in the generated code.
        let pip_line = result
            .lines()
            .find(|l| l.contains("PIP_PACKAGES: &[u8]"))
            .expect("there should be an include_bytes! line for the pip tarball");
        assert!(!pip_line.contains(r"C:\Users"));
    }

    #[test]
    fn gen_launcher_cargo_toml_substitutes_bin_name() {
        let result = gen_launcher_cargo_toml("hola");
        assert!(!result.contains(PLACEHOLDER_BIN_NAME));
        assert!(result.contains("name = \"hola\""));
    }

    #[test]
    fn tarball_hash_short_returns_16_hex_chars() {
        let h = tarball_hash_short(b"hello world");
        assert_eq!(h.len(), 16);
        assert!(h.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn tarball_hash_short_is_deterministic() {
        let h1 = tarball_hash_short(b"foo bar baz");
        let h2 = tarball_hash_short(b"foo bar baz");
        assert_eq!(h1, h2);
    }

    #[test]
    fn tarball_hash_short_changes_with_different_input() {
        let h1 = tarball_hash_short(b"hello");
        let h2 = tarball_hash_short(b"world");
        assert_ne!(h1, h2);
    }

    #[test]
    fn tarball_hash_short_empty_input_returns_offset() {
        // FNV-1a over empty input returns the offset basis.
        let h = tarball_hash_short(b"");
        assert_eq!(h, "cbf29ce484222325");
    }

    // NOTE: that the generated code COMPILES as valid Rust is
    // validated in `tests/cli_e2e.rs` with a real `cargo build` over
    // the output of `gen_launcher_main_rs` (sub-step 8.b.4/8.b.5).
}
