// py_types.rs — Phase 8.5: auto-mapping of SQLAlchemy models to Fitz
// `type`s.
//
// The `fitz py-types <file.py> [--out <file.fitz>]` sub-command
// invokes `generate_from_file(path)` which:
//
//   1. Takes the GIL via `Python::attach`.
//   2. Imports the Python file as a dynamic module via
//      `importlib.util.spec_from_file_location` + `module_from_spec`.
//   3. Iterates the module's `__dict__` looking for (top-level) classes with
//      `__table__.columns` attribute. Duck typing: compatible with
//      real SQLAlchemy (`DeclarativeBase` subclasses) and with mocks that
//      satisfy the same contract (`column.name`, `column.type`,
//      `column.nullable`, `column.default`).
//   4. For each class, emits a `type ClassName { f1: T1, ... }` block
//      following the roadmap mapping.
//
// Design decisions (aligned with the 8.5 roadmap):
//
//   - **In-process via PyO3** (no subprocess). Reuses the GIL + PyO3
//     dep already available with `--features python`. Without the feature
//     the sub-command aborts before getting here.
//   - **Duck typing** (`__table__.columns`) instead of `isinstance`
//     against `DeclarativeBase`. Allows tests with mocks without requiring
//     real SQLAlchemy installed; works the same with real SQLAlchemy.
//   - **Only top-level of the imported file**. Models inherited
//     from external bases (`from app.models_base import Base`) are
//     detected by shape, not by inheritance.
//   - **Conservative mapping**: direct primitive types, DateTime
//     → Str (ISO 8601), unknowns → `Any` with a `// ?` comment
//     so the user can mark them by hand.
//   - **Only literal defaults** (Int/Float/Str/Bool/None). Callable
//     defaults (`default=datetime.utcnow`) are silently ignored
//     — emitting `= func()` adds no value and can confuse.

use std::path::Path;

use pyo3::prelude::*;
use pyo3::types::{PyDict, PyList, PyString};

/// Entry point. Imports `source` with PyO3 + introspects +
/// generates the Fitz text. Returns the generated text or a readable
/// error for the caller (which decides stdout vs file).
pub fn generate_from_file(source: &Path) -> Result<String, String> {
    let abs = source
        .canonicalize()
        .map_err(|e| format!("could not resolve path `{}`: {}", source.display(), e))?;
    let abs_str = abs.to_string_lossy().to_string();
    let module_name = source
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("module")
        .to_string();

    Python::attach(|py| {
        let module = import_file_as_module(py, &abs_str, &module_name)
            .map_err(|e| pyerr_to_string(py, e))?;
        let models = collect_models(py, &module).map_err(|e| pyerr_to_string(py, e))?;
        let mut out = String::new();
        out.push_str("// Generated by `fitz py-types` — do not edit by hand.\n");
        out.push_str(&format!("// Source: {}\n\n", source.display(),));
        for model in &models {
            emit_type(model, &mut out);
            out.push('\n');
        }
        if models.is_empty() {
            return Err(format!(
                "the file `{}` exposes no class with `__table__.columns` \
                 (expected: SQLAlchemy models or mocks with that shape)",
                source.display()
            ));
        }
        Ok(out)
    })
}

/// Imports a Python file as a dynamic module using
/// `importlib.util`. The module name is only cosmetic — what
/// matters is the absolute path. The import runs the top-level
/// code (class definitions, etc.), so if the file
/// has heavy side-effects (DB connections, etc.) they will run.
fn import_file_as_module<'py>(
    py: Python<'py>,
    abs_path: &str,
    module_name: &str,
) -> PyResult<Bound<'py, PyAny>> {
    let importlib_util = py.import("importlib.util")?;
    let spec = importlib_util.call_method1("spec_from_file_location", (module_name, abs_path))?;
    if spec.is_none() {
        return Err(pyo3::exceptions::PyImportError::new_err(format!(
            "could not build the import spec for `{}`",
            abs_path
        )));
    }
    let module = importlib_util.call_method1("module_from_spec", (&spec,))?;
    let loader = spec.getattr("loader")?;
    loader.call_method1("exec_module", (&module,))?;
    Ok(module)
}

/// Collects models from the imported module. A "model" is
/// any top-level class with `__table__.columns` attribute.
fn collect_models<'py>(py: Python<'py>, module: &Bound<'py, PyAny>) -> PyResult<Vec<Model>> {
    let module_name: String = module.getattr("__name__")?.extract()?;
    let dict = module.getattr("__dict__")?;
    let dict = dict.cast::<PyDict>()?;
    let mut models: Vec<Model> = Vec::new();
    for (name_obj, value_obj) in dict.iter() {
        let name: String = match name_obj.cast::<PyString>() {
            Ok(s) => s.to_string(),
            Err(_) => continue,
        };
        // Filter dunders.
        if name.starts_with('_') {
            continue;
        }
        // Has to be a class.
        let builtins = py.import("builtins")?;
        let isinstance: bool = builtins
            .call_method1("isinstance", (&value_obj, builtins.getattr("type")?))?
            .extract()?;
        if !isinstance {
            continue;
        }
        // Only classes defined IN this module (filters out re-exports
        // of SQLAlchemy itself: `Base`, `Column`, `Integer`, etc.).
        let cls_module: String = match value_obj.getattr("__module__") {
            Ok(m) => m.extract().unwrap_or_default(),
            Err(_) => continue,
        };
        if cls_module != module_name {
            continue;
        }
        // Duck typing: does it have __table__.columns?
        let table = match value_obj.getattr("__table__") {
            Ok(t) => t,
            Err(_) => continue,
        };
        let columns = match table.getattr("columns") {
            Ok(c) => c,
            Err(_) => continue,
        };
        let fields = collect_fields(py, &columns)?;
        models.push(Model { name, fields });
    }
    Ok(models)
}

/// Collects the fields of a table's `columns` collection. The
/// collection must be iterable and yield objects with
/// `(name, type, nullable, default)`.
fn collect_fields<'py>(py: Python<'py>, columns: &Bound<'py, PyAny>) -> PyResult<Vec<Field>> {
    let iter = columns.try_iter()?;
    let mut fields: Vec<Field> = Vec::new();
    for col in iter {
        let col = col?;
        let name: String = col.getattr("name")?.extract()?;
        let py_type_obj = col.getattr("type")?;
        let fitz_type = python_type_to_fitz_type(py, &py_type_obj)?;
        let nullable: bool = col
            .getattr("nullable")
            .and_then(|v| v.extract::<bool>())
            .unwrap_or(false);
        let default = extract_default(py, &col)?;
        fields.push(Field {
            name,
            fitz_type,
            nullable,
            default,
        });
    }
    Ok(fields)
}

/// Maps a SQLAlchemy type to a Fitz type name. Inspection
/// is by the class name of the `Column.type` object so we do not need
/// to import sqlalchemy directly. Unknown types produce
/// `Any` (with `// ?` in the output as a hint to the user).
fn python_type_to_fitz_type<'py>(
    _py: Python<'py>,
    py_type: &Bound<'py, PyAny>,
) -> PyResult<FitzType> {
    let cls = py_type.get_type();
    let cls_name: String = cls.name()?.to_string();
    // The mapping is by the canonical SQLAlchemy class name.
    // Supports both `Column(Integer)` (where `type` is an instance
    // of `Integer`) and type-as-class (rare but possible).
    let mapped = match cls_name.as_str() {
        "Integer" | "BigInteger" | "SmallInteger" | "INTEGER" | "BIGINT" | "SMALLINT" => {
            FitzType::Int
        }
        "Float" | "Numeric" | "Double" | "REAL" | "FLOAT" | "NUMERIC" => FitzType::Float,
        "String" | "Text" | "Unicode" | "VARCHAR" | "TEXT" | "CHAR" | "CLOB" => FitzType::Str,
        "Boolean" | "BOOLEAN" => FitzType::Bool,
        "DateTime" | "Date" | "Time" | "TIMESTAMP" | "DATE" | "TIME" => FitzType::Str,
        other => FitzType::Unknown(other.to_string()),
    };
    Ok(mapped)
}

/// Extracts the default value if it is a simple literal (Int/Float/
/// Str/Bool/None). Callable defaults (`default=datetime.utcnow`) are
/// silently ignored. SQLAlchemy wraps defaults in
/// `ColumnDefault(arg=<value>)` — we access `.arg` and filter out
/// callables with `inspect.isfunction`/`callable`.
fn extract_default<'py>(
    py: Python<'py>,
    column: &Bound<'py, PyAny>,
) -> PyResult<Option<FitzLiteral>> {
    let default = match column.getattr("default") {
        Ok(d) if !d.is_none() => d,
        _ => return Ok(None),
    };
    // SQLAlchemy: `default` can be a `ColumnDefault` with `.arg`,
    // or a direct literal. We try both.
    let value = match default.getattr("arg") {
        Ok(arg) => arg,
        Err(_) => default,
    };
    // If it is callable, we ignore it.
    let builtins = py.import("builtins")?;
    let is_callable: bool = builtins.call_method1("callable", (&value,))?.extract()?;
    if is_callable {
        return Ok(None);
    }
    if value.is_none() {
        return Ok(Some(FitzLiteral::Null));
    }
    // Python type → Fitz literal. Care: bool before int.
    if let Ok(b) = value.extract::<bool>() {
        let bool_type = builtins.getattr("bool")?;
        let is_bool: bool = builtins
            .call_method1("isinstance", (&value, &bool_type))?
            .extract()?;
        if is_bool {
            return Ok(Some(FitzLiteral::Bool(b)));
        }
    }
    if let Ok(n) = value.extract::<i64>() {
        return Ok(Some(FitzLiteral::Int(n)));
    }
    if let Ok(f) = value.extract::<f64>() {
        return Ok(Some(FitzLiteral::Float(f)));
    }
    if let Ok(s) = value.extract::<String>() {
        return Ok(Some(FitzLiteral::Str(s)));
    }
    // Type not representable as a Fitz literal — we ignore it.
    Ok(None)
}

/// Emits a `type Name { ... }` block with the fields.
fn emit_type(model: &Model, out: &mut String) {
    out.push_str(&format!("type {} {{\n", model.name));
    let n = model.fields.len();
    for (i, f) in model.fields.iter().enumerate() {
        let ty_str = match &f.fitz_type {
            FitzType::Int => "Int".to_string(),
            FitzType::Float => "Float".to_string(),
            FitzType::Str => "Str".to_string(),
            FitzType::Bool => "Bool".to_string(),
            FitzType::Unknown(_) => "Any".to_string(),
        };
        let ty_str = if f.nullable {
            format!("{}?", ty_str)
        } else {
            ty_str
        };
        let default_str = match &f.default {
            Some(lit) => format!(" = {}", emit_literal(lit)),
            None => String::new(),
        };
        // Comment for unknown types: hint for the user.
        let comment = match &f.fitz_type {
            FitzType::Unknown(name) => format!("  // ? tipo SQLAlchemy `{}` mapeado a Any", name),
            _ => String::new(),
        };
        let sep = if i + 1 < n { "," } else { "" };
        out.push_str(&format!(
            "    {}: {}{}{}{}\n",
            f.name, ty_str, default_str, sep, comment,
        ));
    }
    out.push_str("}\n");
}

fn emit_literal(lit: &FitzLiteral) -> String {
    match lit {
        FitzLiteral::Int(n) => n.to_string(),
        FitzLiteral::Float(f) => {
            if f.fract() == 0.0 && f.is_finite() {
                format!("{:.1}", f)
            } else {
                f.to_string()
            }
        }
        FitzLiteral::Str(s) => format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\"")),
        FitzLiteral::Bool(b) => b.to_string(),
        FitzLiteral::Null => "null".to_string(),
    }
}

fn pyerr_to_string(py: Python<'_>, err: PyErr) -> String {
    let class = err
        .get_type(py)
        .qualname()
        .ok()
        .map(|s| s.to_string())
        .unwrap_or_else(|| "PyError".to_string());
    let msg = err.value(py).to_string();
    if msg.is_empty() {
        class
    } else {
        format!("{}: {}", class, msg)
    }
}

/// Suppresses unused warnings — used only in the introspection
/// path that iterates the module's `__dict__`.
#[allow(dead_code)]
fn _suppress_unused(_pl: &PyList) {}

// ---------------------------------------------------------------------------
// Internal data
// ---------------------------------------------------------------------------

struct Model {
    name: String,
    fields: Vec<Field>,
}

struct Field {
    name: String,
    fitz_type: FitzType,
    nullable: bool,
    default: Option<FitzLiteral>,
}

enum FitzType {
    Int,
    Float,
    Str,
    Bool,
    Unknown(String),
}

enum FitzLiteral {
    Int(i64),
    Float(f64),
    Str(String),
    Bool(bool),
    Null,
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::NamedTempFile;

    /// Helper: writes `code` Python to a temp file and runs
    /// `generate_from_file` against it. Returns the emitted output or
    /// the error message.
    fn run(code: &str) -> Result<String, String> {
        let mut f = NamedTempFile::with_suffix(".py").expect("tempfile");
        f.write_all(code.as_bytes()).expect("write");
        f.flush().expect("flush");
        generate_from_file(f.path())
    }

    /// Mock of a SQLAlchemy model. Satisfies the `__table__.columns`
    /// contract that introspection expects, without requiring SQLAlchemy installed.
    const MOCK_BOILERPLATE: &str = "\
class Column:
    def __init__(self, type_, nullable=False, default=None):
        self.type = type_
        self.nullable = nullable
        self.default = default

class _Columns:
    def __init__(self, items):
        self._items = items
        for c in items:
            # Hack so the iter yields the name: the caller sets
            # `name` before putting the Column into _Columns.
            pass
    def __iter__(self):
        return iter(self._items)

class _Table:
    def __init__(self, columns):
        self.columns = _Columns(columns)

def _named(name, col):
    col.name = name
    return col

class Integer: pass
class BigInteger: pass
class String: pass
class Float: pass
class Boolean: pass
class DateTime: pass
";

    #[test]
    fn simple_model_emits_type_with_primitive_fields() {
        let code = format!(
            "{}\nclass User:\n    __table__ = _Table([\n        _named('id', Column(Integer())),\n        _named('email', Column(String())),\n    ])\n",
            MOCK_BOILERPLATE
        );
        let out = run(&code).expect("generate ok");
        assert!(out.contains("type User {"), "out:\n{}", out);
        assert!(out.contains("id: Int"), "out:\n{}", out);
        assert!(out.contains("email: Str"), "out:\n{}", out);
    }

    #[test]
    fn mapping_of_primitive_types() {
        let code = format!(
            "{}\nclass T:\n    __table__ = _Table([\n        _named('a', Column(Integer())),\n        _named('b', Column(BigInteger())),\n        _named('c', Column(Float())),\n        _named('d', Column(String())),\n        _named('e', Column(Boolean())),\n        _named('f', Column(DateTime())),\n    ])\n",
            MOCK_BOILERPLATE
        );
        let out = run(&code).expect("generate ok");
        assert!(out.contains("a: Int"));
        assert!(out.contains("b: Int"));
        assert!(out.contains("c: Float"));
        assert!(out.contains("d: Str"));
        assert!(out.contains("e: Bool"));
        assert!(out.contains("f: Str")); // DateTime → Str ISO 8601
    }

    #[test]
    fn nullable_annotates_with_question_suffix() {
        let code = format!(
            "{}\nclass T:\n    __table__ = _Table([\n        _named('a', Column(Integer(), nullable=True)),\n        _named('b', Column(String(), nullable=False)),\n    ])\n",
            MOCK_BOILERPLATE
        );
        let out = run(&code).expect("generate ok");
        assert!(out.contains("a: Int?"), "out:\n{}", out);
        assert!(out.contains("b: Str"), "out:\n{}", out);
        assert!(!out.contains("b: Str?"), "b should not be nullable");
    }

    #[test]
    fn default_literal_emits_inline() {
        let code = format!(
            "{}\nclass T:\n    __table__ = _Table([\n        _named('a', Column(Integer(), default=42)),\n        _named('b', Column(String(), default='hola')),\n        _named('c', Column(Boolean(), default=True)),\n    ])\n",
            MOCK_BOILERPLATE
        );
        let out = run(&code).expect("generate ok");
        assert!(out.contains("a: Int = 42"), "out:\n{}", out);
        assert!(out.contains("b: Str = \"hola\""), "out:\n{}", out);
        assert!(out.contains("c: Bool = true"), "out:\n{}", out);
    }

    #[test]
    fn default_callable_is_ignored() {
        // `default=callable` is common in SQLAlchemy (`default=datetime.utcnow`);
        // emitting `= func()` adds nothing, we ignore it.
        let code = format!(
            "{}\nimport datetime\nclass T:\n    __table__ = _Table([\n        _named('created_at', Column(DateTime(), default=datetime.datetime.utcnow)),\n    ])\n",
            MOCK_BOILERPLATE
        );
        let out = run(&code).expect("generate ok");
        assert!(out.contains("created_at: Str"), "out:\n{}", out);
        assert!(
            !out.contains("created_at: Str ="),
            "callable default should be ignored"
        );
    }

    #[test]
    fn unknown_type_falls_back_to_any_with_comment() {
        let code = format!(
            "{}\nclass JSON: pass\nclass T:\n    __table__ = _Table([\n        _named('payload', Column(JSON())),\n    ])\n",
            MOCK_BOILERPLATE
        );
        let out = run(&code).expect("generate ok");
        assert!(out.contains("payload: Any"), "out:\n{}", out);
        assert!(
            out.contains("// ?"),
            "expected comment citing SQLA type, out:\n{}",
            out
        );
        assert!(
            out.contains("JSON"),
            "comment should cite the original name"
        );
    }

    #[test]
    fn varios_modelos_emiten_varios_types() {
        let code = format!(
            "{}\nclass User:\n    __table__ = _Table([_named('id', Column(Integer()))])\nclass Order:\n    __table__ = _Table([_named('id', Column(Integer())), _named('total', Column(Float()))])\n",
            MOCK_BOILERPLATE
        );
        let out = run(&code).expect("generate ok");
        assert!(out.contains("type User {"));
        assert!(out.contains("type Order {"));
        assert!(out.contains("total: Float"));
    }

    #[test]
    fn file_without_models_is_clear_error() {
        let code = "x = 1\n";
        let err = run(code).expect_err("should not have models");
        assert!(
            err.contains("no class") || err.contains("__table__"),
            "msg: {}",
            err,
        );
    }

    #[test]
    fn classes_without_table_attribute_are_ignored() {
        // `Helper` does not have `__table__` — must be filtered out.
        let code = format!(
            "{}\nclass Helper:\n    def hello(self): pass\nclass User:\n    __table__ = _Table([_named('id', Column(Integer()))])\n",
            MOCK_BOILERPLATE
        );
        let out = run(&code).expect("generate ok");
        assert!(out.contains("type User {"));
        assert!(
            !out.contains("type Helper {"),
            "Helper should not be emitted"
        );
    }

    #[test]
    fn header_cites_source_file() {
        let code = format!(
            "{}\nclass User:\n    __table__ = _Table([_named('id', Column(Integer()))])\n",
            MOCK_BOILERPLATE
        );
        let out = run(&code).expect("generate ok");
        assert!(out.starts_with("// Generated by `fitz py-types`"));
        assert!(out.contains("// Source:"));
    }
}
